
create table if not exists public.closerflow_workspaces (
  workspace_id text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.closerflow_backups (
  id bigint generated by default as identity primary key,
  label text not null,
  snapshot jsonb not null,
  created_at timestamptz not null default now()
);
alter table public.closerflow_workspaces enable row level security;
alter table public.closerflow_backups enable row level security;
create index if not exists closerflow_backups_created_idx on public.closerflow_backups(created_at desc);
