import { useMemo, useRef, useState } from 'react';
import { Download, FileSpreadsheet, FileUp, Landmark, ReceiptText, Trash2, WalletCards } from 'lucide-react';
import { useAppData } from '../context/AppDataContext';
import { money } from '../lib/documents';
import { createId } from '../lib/id';

type LedgerTransaction={id:string;date:string;label:string;amount:number;reference:string;source:'csv'|'ofx'|'camt';importedAt:string};
const STORAGE_KEY='closerflow.accounting.transactions.v10_3';
const loadTransactions=():LedgerTransaction[]=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}};
const saveFile=(name:string,content:string,type='text/csv;charset=utf-8')=>{const blob=new Blob(['\uFEFF'+content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)};
const normalize=(value:string)=>value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const parseAmount=(value:string)=>Number(value.replace(/\s/g,'').replace(',','.').replace(/[^0-9.-]/g,''));
const toIsoDate=(raw:string)=>{const trimmed=raw.trim();const fr=trimmed.match(/(\d{2})[\/.\-](\d{2})[\/.\-](\d{4})/);if(fr)return `${fr[3]}-${fr[2]}-${fr[1]}`;const ofx=trimmed.match(/^(\d{4})(\d{2})(\d{2})/);if(ofx)return `${ofx[1]}-${ofx[2]}-${ofx[3]}`;return trimmed.slice(0,10)||new Date().toISOString().slice(0,10)};
const invoiceHt=(invoice:any)=>invoice.lines.reduce((sum:number,line:any)=>sum+line.quantity*line.unit_price_ht,0)*(1-(invoice.discount_percent??0)/100);
const invoiceTtc=(invoice:any)=>invoiceHt(invoice)*(1+invoice.vat_rate/100);
const paidAmount=(invoice:any)=>invoice.payments.reduce((sum:number,p:any)=>sum+p.amount,0);

function parseCsv(text:string):LedgerTransaction[]{
 const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];
 const sep=[';',',','\t'].sort((a,b)=>lines[0].split(b).length-lines[0].split(a).length)[0];
 const split=(line:string)=>line.split(sep).map(x=>x.trim().replace(/^"|"$/g,''));
 const headers=split(lines[0]).map(normalize);const find=(terms:string[])=>headers.findIndex(h=>terms.some(t=>h.includes(t)));
 const di=find(['date','operation']);const li=find(['libelle','label','description','intitule']);const ai=find(['montant','amount']);const deb=find(['debit']);const cre=find(['credit']);const ri=find(['reference','ref']);
 return lines.slice(1).map(line=>{const c=split(line);const amount=ai>=0?parseAmount(c[ai]||'0'):(cre>=0?parseAmount(c[cre]||'0'):0)-Math.abs(deb>=0?parseAmount(c[deb]||'0'):0);return{id:createId(),date:toIsoDate(c[di]||''),label:c[li]||'Opération bancaire',amount,reference:c[ri]||'',source:'csv' as const,importedAt:new Date().toISOString()}}).filter(x=>Number.isFinite(x.amount)&&x.amount!==0);
}
function tag(text:string,name:string){const match=text.match(new RegExp(`<${name}>([^<\\r\\n]+)`,'i'));return match?.[1]?.trim()||''}
function parseOfx(text:string):LedgerTransaction[]{return text.split(/<STMTTRN>/i).slice(1).map(block=>({id:createId(),date:toIsoDate(tag(block,'DTPOSTED')),label:tag(block,'NAME')||tag(block,'MEMO')||'Opération OFX',amount:parseAmount(tag(block,'TRNAMT')),reference:tag(block,'FITID'),source:'ofx' as const,importedAt:new Date().toISOString()})).filter(x=>Number.isFinite(x.amount)&&x.amount!==0)}
function firstText(node:Element,names:string[]){for(const name of names){const el=node.getElementsByTagNameNS('*',name)[0]||node.getElementsByTagName(name)[0];if(el?.textContent)return el.textContent.trim()}return''}
function parseCamt(text:string):LedgerTransaction[]{
 const xml=new DOMParser().parseFromString(text,'application/xml');const entries=Array.from(xml.getElementsByTagNameNS('*','Ntry'));
 return entries.map(node=>{const amount=parseAmount(firstText(node,['Amt']));const indicator=firstText(node,['CdtDbtInd']);return{id:createId(),date:toIsoDate(firstText(node,['BookgDt','Dt','DtTm'])),label:firstText(node,['AddtlNtryInf','Ustrd','Nm'])||'Opération CAMT',amount:indicator==='DBIT'?-Math.abs(amount):Math.abs(amount),reference:firstText(node,['AcctSvcrRef','EndToEndId']),source:'camt' as const,importedAt:new Date().toISOString()}}).filter(x=>Number.isFinite(x.amount)&&x.amount!==0);
}

export function AccountingTreasuryPage(){
 const {invoices,clients,businessExpenses}=useAppData();const [transactions,setTransactions]=useState<LedgerTransaction[]>(loadTransactions);const inputRef=useRef<HTMLInputElement>(null);
 const persist=(next:LedgerTransaction[])=>{setTransactions(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next))};
 const onFile=async(file?:File)=>{if(!file)return;const text=await file.text();const lower=file.name.toLowerCase();const parsed=lower.endsWith('.ofx')||lower.endsWith('.qfx')?parseOfx(text):lower.endsWith('.xml')?parseCamt(text):parseCsv(text);persist([...parsed,...transactions]);if(inputRef.current)inputRef.current.value=''};
 const stats=useMemo(()=>{
  const receivables=invoices.reduce((sum,i)=>sum+Math.max(0,invoiceTtc(i)-paidAmount(i)),0);const payables=businessExpenses.filter(e=>!e.paid).reduce((sum,e)=>sum+e.amount_ht*(1+e.vat_rate/100),0);
  const vatCollected=invoices.reduce((sum,i)=>sum+invoiceHt(i)*i.vat_rate/100,0);const vatDeductible=businessExpenses.reduce((sum,e)=>sum+e.amount_ht*e.vat_rate/100,0);
  const importedBalance=transactions.reduce((sum,t)=>sum+t.amount,0);return{receivables,payables,vatCollected,vatDeductible,vatBalance:vatCollected-vatDeductible,importedBalance};
 },[invoices,businessExpenses,transactions]);
 const clientBalances=useMemo(()=>clients.map(client=>{const rows=invoices.filter(i=>i.client_id===client.id);const due=rows.reduce((sum,i)=>sum+Math.max(0,invoiceTtc(i)-paidAmount(i)),0);return{id:client.id,name:client.company_name||`${client.first_name} ${client.last_name}`.trim()||'Client',count:rows.length,due}}).filter(x=>x.due>0).sort((a,b)=>b.due-a.due),[clients,invoices]);
 const supplierBalances=useMemo(()=>Object.values(businessExpenses.filter(e=>!e.paid).reduce<Record<string,{name:string;count:number;due:number}>>((acc,e)=>{const key=e.supplier||'Fournisseur non renseigné';acc[key]??={name:key,count:0,due:0};acc[key].count++;acc[key].due+=e.amount_ht*(1+e.vat_rate/100);return acc},{})).sort((a,b)=>b.due-a.due),[businessExpenses]);
 const exportAccounting=()=>{const rows=[['Journal','Date','Pièce','Compte','Libellé','Débit','Crédit']];invoices.forEach(i=>{const ttc=invoiceTtc(i);rows.push(['VE',i.created_at.slice(0,10),i.number,'411000',i.title,ttc.toFixed(2),'']);rows.push(['VE',i.created_at.slice(0,10),i.number,'706000',i.title,'',invoiceHt(i).toFixed(2)]);rows.push(['VE',i.created_at.slice(0,10),i.number,'445710','TVA collectée','',(ttc-invoiceHt(i)).toFixed(2)])});businessExpenses.forEach(e=>{const ttc=e.amount_ht*(1+e.vat_rate/100);rows.push(['AC',e.expense_date,e.id.slice(0,8),'401000',`${e.supplier} · ${e.label}`,'',ttc.toFixed(2)]);rows.push(['AC',e.expense_date,e.id.slice(0,8),'606000',e.label,e.amount_ht.toFixed(2),'']);rows.push(['AC',e.expense_date,e.id.slice(0,8),'445660','TVA déductible',(ttc-e.amount_ht).toFixed(2),''])});saveFile(`closerflow-export-comptable-${new Date().toISOString().slice(0,10)}.csv`,rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\n'))};
 const exportTransactions=()=>saveFile(`closerflow-releve-${new Date().toISOString().slice(0,10)}.csv`,[['Date','Libellé','Référence','Montant','Source'],...transactions.map(t=>[t.date,t.label,t.reference,t.amount.toFixed(2),t.source.toUpperCase()])].map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\n'));
 return <><div className="section-heading"><div><p className="eyebrow">V10.3 · FINANCE</p><h1>Comptabilité & trésorerie</h1></div><div className="inline-actions"><button className="secondary" onClick={exportAccounting}><FileSpreadsheet/>Export comptable</button><button className="primary" onClick={()=>inputRef.current?.click()}><FileUp/>Importer relevé</button><input ref={inputRef} hidden type="file" accept=".csv,.ofx,.qfx,.xml,text/csv,application/xml" onChange={e=>onFile(e.target.files?.[0])}/></div></div>
 <div className="kpi-grid"><article className="kpi-card"><span>Créances clients</span><strong>{money(stats.receivables)}</strong></article><article className="kpi-card"><span>Dettes fournisseurs</span><strong>{money(stats.payables)}</strong></article><article className="kpi-card"><span>TVA nette estimée</span><strong>{money(stats.vatBalance)}</strong></article><article className="kpi-card"><span>Solde relevés importés</span><strong>{money(stats.importedBalance)}</strong></article></div>
 <div className="two-columns"><section className="panel"><div className="section-heading compact"><div><h2>Balance clients</h2><p>Factures restant à encaisser</p></div><ReceiptText/></div><div className="list-stack">{clientBalances.length===0?<p className="muted">Aucune créance client.</p>:clientBalances.map(x=><article className="list-card" key={x.id}><div><strong>{x.name}</strong><small>{x.count} facture{x.count>1?'s':''}</small></div><strong>{money(x.due)}</strong></article>)}</div></section>
 <section className="panel"><div className="section-heading compact"><div><h2>Balance fournisseurs</h2><p>Dépenses restant à payer</p></div><WalletCards/></div><div className="list-stack">{supplierBalances.length===0?<p className="muted">Aucune dette fournisseur.</p>:supplierBalances.map(x=><article className="list-card" key={x.name}><div><strong>{x.name}</strong><small>{x.count} dépense{x.count>1?'s':''}</small></div><strong>{money(x.due)}</strong></article>)}</div></section></div>
 <section className="panel"><div className="section-heading compact"><div><h2>TVA</h2><p>Indicateur de préparation, à valider avec la comptabilité</p></div><Landmark/></div><div className="stats-grid"><div className="stat-card"><small>TVA collectée</small><strong>{money(stats.vatCollected)}</strong></div><div className="stat-card"><small>TVA déductible</small><strong>{money(stats.vatDeductible)}</strong></div><div className="stat-card"><small>TVA nette</small><strong>{money(stats.vatBalance)}</strong></div></div></section>
 <section className="panel"><div className="section-heading compact"><div><h2>Relevés bancaires</h2><p>CSV, OFX/QFX et CAMT.053 XML</p></div><div className="inline-actions">{transactions.length>0&&<><button className="secondary" onClick={exportTransactions}><Download/>Exporter</button><button className="icon-button danger" title="Supprimer les imports" onClick={()=>{if(confirm('Supprimer tous les relevés importés ?'))persist([])}}><Trash2/></button></>}</div></div><div className="list-stack">{transactions.length===0?<div className="empty-state"><Landmark/><h2>Aucun relevé importé</h2><p>Importe un CSV, un fichier OFX/QFX ou un relevé CAMT.053 au format XML.</p></div>:transactions.slice(0,100).map(t=><article className="list-card" key={t.id}><div><strong>{t.label}</strong><small>{new Date(t.date).toLocaleDateString('fr-FR')} · {t.source.toUpperCase()} {t.reference&&`· ${t.reference}`}</small></div><strong className={t.amount>=0?'positive':'negative'}>{money(t.amount)}</strong></article>)}</div></section>
 </>;
}
