import { Clipboard, RefreshCw, ShieldCheck, UserPlus, UserRound, Users } from 'lucide-react';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { useAuth, type AccountRole, type AccountUser } from '../context/AuthContext';

type Invitation={id:string;email:string;role:AccountRole;workspaceId:string;code:string;createdAt:string;expiresAt:string;acceptedAt:string|null};
const roleLabel:Record<AccountRole,string>={admin:'Administrateur',manager:'Manager',employee:'Employé'};

export function AccountsPage(){
 const {apiUrl,token,user}=useAuth();
 const [users,setUsers]=useState<AccountUser[]>([]); const [invitations,setInvitations]=useState<Invitation[]>([]);
 const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
 const load=useCallback(async()=>{setError('');try{const [u,i]=await Promise.all([fetch(`${apiUrl}/api/users`,{headers}),fetch(`${apiUrl}/api/invitations`,{headers})]);const ub=await u.json();const ib=await i.json();if(!u.ok)throw new Error(ub.error);if(!i.ok)throw new Error(ib.error);setUsers(ub.users);setInvitations(ib.invitations)}catch(err){setError(err instanceof Error?err.message:'Chargement impossible.')}},[apiUrl,token]);
 useEffect(()=>{void load()},[load]);
 const invite=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');setMessage('');const fd=new FormData(e.currentTarget);try{const response=await fetch(`${apiUrl}/api/invitations`,{method:'POST',headers,body:JSON.stringify({email:String(fd.get('email')||''),role:String(fd.get('role')||'employee')})});const body=await response.json();if(!response.ok)throw new Error(body.error);setInvitations(current=>[...current.filter(item=>item.email!==body.invitation.email),body.invitation]);setMessage('Invitation créée. Copie le code et envoie-le à la personne.');e.currentTarget.reset()}catch(err){setError(err instanceof Error?err.message:'Invitation impossible.')}finally{setBusy(false)}};
 const changeRole=async(id:string,role:AccountRole)=>{setError('');try{const response=await fetch(`${apiUrl}/api/users/${id}/role`,{method:'PUT',headers,body:JSON.stringify({role})});const body=await response.json();if(!response.ok)throw new Error(body.error);setUsers(current=>current.map(item=>item.id===id?body.user:item));setMessage('Rôle mis à jour.')}catch(err){setError(err instanceof Error?err.message:'Modification impossible.')}};
 const copy=async(code:string)=>{await navigator.clipboard.writeText(code);setMessage('Code copié dans le presse-papiers.')};
 const canInvite=user?.role==='admin'||user?.role==='manager';
 return <><div className="page-title"><div><p className="eyebrow">ÉQUIPE SAAS</p><h1>Comptes utilisateurs</h1><p>Gère les accès de l’espace <strong>{user?.workspaceId}</strong>.</p></div><Users/></div>
 {error&&<p className="form-error">{error}</p>}{message&&<p className="form-success">{message}</p>}
 <section className="account-summary"><ShieldCheck/><div><strong>Session serveur active</strong><small>Connecté en tant que {user?.email} · {user?roleLabel[user.role]:''}</small></div><button className="icon-button" onClick={()=>void load()} aria-label="Actualiser"><RefreshCw/></button></section>
 {canInvite&&<section className="panel"><div className="section-heading"><div><p className="eyebrow">INVITER</p><h2>Ajouter un membre</h2></div><UserPlus/></div><form className="form-grid invite-form" onSubmit={invite}><label>Adresse e-mail<input name="email" type="email" required placeholder="collaborateur@entreprise.fr"/></label><label>Rôle<select name="role" defaultValue="employee"><option value="employee">Employé</option><option value="manager">Manager</option></select></label><button className="primary" disabled={busy}><UserPlus/>{busy?'Création…':'Créer l’invitation'}</button></form></section>}
 {invitations.length>0&&<section><div className="section-heading"><div><p className="eyebrow">EN ATTENTE</p><h2>Invitations actives</h2></div></div><div className="list-stack">{invitations.map(item=><article className="invite-card" key={item.id}><div><strong>{item.email}</strong><span>{roleLabel[item.role]} · expire le {new Date(item.expiresAt).toLocaleDateString('fr-FR')}</span><code>{item.code}</code></div><button className="secondary" onClick={()=>void copy(item.code)}><Clipboard/>Copier</button></article>)}</div></section>}
 <section><div className="section-heading"><div><p className="eyebrow">MEMBRES</p><h2>{users.length} utilisateur{users.length>1?'s':''}</h2></div></div><div className="list-stack">{users.map(item=><article className="account-card" key={item.id}><div className="account-avatar"><UserRound/></div><div><strong>{item.displayName}{item.id===user?.id?' (vous)':''}</strong><span>{item.email}</span><small>Créé le {new Date(item.createdAt).toLocaleDateString('fr-FR')}</small></div>{user?.role==='admin'?<select className="role-select" value={item.role} onChange={e=>void changeRole(item.id,e.target.value as AccountRole)}><option value="admin">Administrateur</option><option value="manager">Manager</option><option value="employee">Employé</option></select>:<span className="role-chip">{roleLabel[item.role]}</span>}</article>)}</div></section>
 <aside className="cloud-warning"><strong>Version alpha locale.</strong><p>Les invitations sont générées par ton serveur Termux. Il faut transmettre manuellement le code au collaborateur. L’envoi automatique par e-mail viendra avec l’hébergement cloud.</p></aside></>;
}
