import { ChangeEvent, useMemo, useState } from 'react';
import { AlertTriangle, ArchiveRestore, CheckCircle2, Download, HardDriveDownload, History, RefreshCw, ShieldCheck, ShieldQuestion, Trash2, Upload } from 'lucide-react';
import { APP_VERSION, BACKUP_FORMAT, type BackupSnapshot, collectCloserFlowEntries, createSnapshot, inspectEntries, parseBackup, readRestorePoints, restoreEntries, saveRestorePoint } from '../lib/mobileSafety';

function download(name:string,data:string,type='application/json'){
 const blob=new Blob([data],{type}); const url=URL.createObjectURL(blob); const a=document.createElement('a');
 a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);
}
const reasonLabel:Record<BackupSnapshot['reason'],string>={manual:'Manuelle',automatic:'Automatique','before-restore':'Avant restauration','before-reset':'Avant réinitialisation'};

export function BackupCenterPage(){
 const [message,setMessage]=useState(''); const [pending,setPending]=useState<BackupSnapshot|null>(null); const [revision,setRevision]=useState(0);
 const entries=useMemo(()=>collectCloserFlowEntries(),[message,revision]);
 const report=useMemo(()=>inspectEntries(entries),[entries]);
 const restorePoints=useMemo(()=>readRestorePoints(),[revision]);
 const healthy=report.invalidKeys.length===0&&report.criticalMissing.length===0;
 const exportBackup=()=>{const snapshot=createSnapshot('manual');download(`CloserFlow-${APP_VERSION}-sauvegarde-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(snapshot,null,2));saveRestorePoint('manual');setRevision(x=>x+1);setMessage('Sauvegarde téléchargée et point de restauration local créé.');};
 const onFile=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const snap=parseBackup(await file.text());const check=inspectEntries(snap.entries);if(check.invalidKeys.length)throw new Error(`Sauvegarde endommagée : ${check.invalidKeys.length} valeur(s) illisible(s).`);setPending(snap);setMessage(`Sauvegarde vérifiée : ${Object.keys(snap.entries).length} éléments, version ${snap.version}, créée le ${new Date(snap.createdAt).toLocaleString('fr-FR')}.`)}catch(err){setPending(null);setMessage(err instanceof Error?err.message:'Fichier illisible.')}e.target.value='';};
 const restore=()=>{if(!pending)return;if(!confirm('Restaurer cette sauvegarde ? Les données actuelles seront remplacées.'))return;saveRestorePoint('before-restore');restoreEntries(pending.entries);setMessage('Restauration terminée. Rechargement…');setTimeout(()=>location.reload(),700)};
 const restoreLocal=(snapshot:BackupSnapshot)=>{if(!confirm(`Revenir au point du ${new Date(snapshot.createdAt).toLocaleString('fr-FR')} ?`))return;saveRestorePoint('before-restore');restoreEntries(snapshot.entries);setTimeout(()=>location.reload(),500)};
 const clear=()=>{if(!confirm('Effacer les données locales CloserFlow ? Un point de restauration sera conservé.'))return;saveRestorePoint('before-reset');restoreEntries({});location.reload()};
 const clearHistory=()=>{if(!confirm('Supprimer les points de restauration locaux ?'))return;localStorage.removeItem('closerflow.safety.snapshots.v13_2');setRevision(x=>x+1);setMessage('Historique local supprimé. Les données métier sont intactes.');};
 return <><div className="page-title"><div><p className="eyebrow">SÉCURITÉ MOBILE · V{APP_VERSION}</p><h1>Sauvegarde & restauration</h1><p className="muted-copy">Protection locale quotidienne, contrôle d’intégrité et retour arrière avant toute opération sensible.</p></div></div>
 <div className="stat-grid"><article className="stat-card"><HardDriveDownload/><small>Données locales</small><strong>{report.checked}</strong><span>{Math.max(1,Math.round(report.sizeBytes/1024))} Ko enregistrés</span></article><article className="stat-card"><ShieldCheck/><small>Intégrité</small><strong>{healthy?'OK':'À vérifier'}</strong><span>{report.validJson}/{report.checked} valeurs JSON lisibles</span></article><article className="stat-card"><History/><small>Retours arrière</small><strong>{restorePoints.length}/5</strong><span>Rotation automatique locale</span></article></div>
 {message&&<div className="notice"><CheckCircle2/><span>{message}</span></div>}
 {!healthy&&<section className="panel danger-zone"><h2><ShieldQuestion/> Diagnostic des données</h2>{report.invalidKeys.length>0&&<p><strong>{report.invalidKeys.length} clé(s) illisible(s) :</strong> {report.invalidKeys.join(', ')}</p>}{report.criticalMissing.length>0&&<p><strong>Jeux de données absents :</strong> {report.criticalMissing.join(', ')}</p>}<p>Crée une sauvegarde avant toute correction. Les données absentes peuvent être normales sur une installation neuve.</p></section>}
 <section className="panel"><h2><Download/> Créer une sauvegarde complète</h2><p>Exporte les données locales au format {BACKUP_FORMAT}. Le fichier reste sur ton appareil et peut être conservé dans Drive.</p><button className="primary-button" onClick={exportBackup}><Download/> Télécharger et sécuriser</button></section>
 <section className="panel"><h2><Upload/> Restaurer un fichier</h2><p>Le contenu est contrôlé avant le remplacement des données. Un point de retour arrière est créé automatiquement.</p><label className="secondary-button"><Upload/> Choisir un fichier JSON<input hidden type="file" accept="application/json,.json" onChange={onFile}/></label>{pending&&<div className="action-row"><button className="primary-button" onClick={restore}><ArchiveRestore/> Restaurer maintenant</button><button className="secondary-button" onClick={()=>{setPending(null);setMessage('Restauration annulée.')}}>Annuler</button></div>}</section>
 <section className="panel"><div className="section-heading"><div><h2><History/> Points de restauration locaux</h2><p className="muted-copy">Un point automatique est créé une fois par jour et avant chaque opération sensible.</p></div>{restorePoints.length>0&&<button className="secondary-button" onClick={clearHistory}><Trash2/> Vider</button>}</div>{restorePoints.length===0?<p>Aucun point local disponible.</p>:<div className="stack">{restorePoints.map((snapshot,index)=><article className="absence-card" key={`${snapshot.createdAt}-${index}`}><div><strong>{reasonLabel[snapshot.reason]}</strong><small>{new Date(snapshot.createdAt).toLocaleString('fr-FR')} · v{snapshot.version}</small><p>{Object.keys(snapshot.entries).length} éléments protégés</p></div><button className="secondary-button" onClick={()=>restoreLocal(snapshot)}><ArchiveRestore/> Restaurer</button></article>)}</div>}</section>
 <section className="panel danger-zone"><h2><AlertTriangle/> Zone sensible</h2><p>La réinitialisation crée d’abord un point de restauration local, puis efface les données métier de cet appareil.</p><button className="secondary-button" onClick={clear}><RefreshCw/> Réinitialiser les données locales</button></section></>;
}
