import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, Bot, CalendarClock, CheckCircle2, CircleDollarSign, FileCheck2, Gauge, HandCoins, PackageSearch, Play, RefreshCcw, Rocket, ShieldCheck, Sparkles, Target, UsersRound, WandSparkles } from 'lucide-react';
import { useAppData } from '../context/AppDataContext';

const DAY=86_400_000;
const euro=(v:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number.isFinite(v)?v:0);
const total=(d:any)=>{const ht=(d.lines||[]).reduce((s:number,l:any)=>s+(+l.quantity||0)*(+l.unit_price_ht||0),0)*(1-(+d.discount_percent||0)/100);return ht*(1+(+d.vat_rate||0)/100)};
const KEY='closerflow.autopilot.v13.6';
const clientLabel=(c:any)=>c?(c.company_name||`${c.first_name||''} ${c.last_name||''}`.trim()||'Client'):'Client';
const terminal=(status:string)=>['completed','invoiced','paid','archived'].includes(status);
type RuleKey='collections'|'acceptedQuotes'|'planning'|'assignment'|'stock'|'closeout';
type Config={enabled:Record<RuleKey,boolean>;overdueDays:number;planningDays:number;stockMultiplier:number};
const DEFAULT:Config={enabled:{collections:true,acceptedQuotes:true,planning:true,assignment:true,stock:true,closeout:true},overdueDays:1,planningDays:7,stockMultiplier:1};
function load():Config{try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...DEFAULT,...x,enabled:{...DEFAULT.enabled,...x.enabled}}}catch{return DEFAULT}}

type Action={id:string;rule:RuleKey;severity:'critical'|'warning'|'info';title:string;detail:string;amount?:number;href:string;entityId?:string};
export function BusinessAutopilotPage(){
 const {clients,missions,quotes,invoices,team,inventory,timeEntries,convertQuoteToInvoice,assignMission,updateMissionSchedule}=useAppData();
 const [config,setConfig]=useState<Config>(load);
 const [lastRun,setLastRun]=useState<string>(()=>localStorage.getItem(`${KEY}.lastRun`)||'');
 const [log,setLog]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem(`${KEY}.log`)||'[]')}catch{return []}});
 const now=Date.now();
 const actions=useMemo<Action[]>(()=>{
   const rows:Action[]=[];
   if(config.enabled.collections) invoices.forEach(i=>{const due=i.due_date?new Date(i.due_date).getTime():0;const paid=(i.payments||[]).reduce((s,p)=>s+(+p.amount||0),0);const remaining=Math.max(0,total(i)-paid);const days=due?Math.floor((now-due)/DAY):0;if(remaining>0&&due&&days>=config.overdueDays)rows.push({id:`pay-${i.id}`,rule:'collections',severity:days>30?'critical':'warning',title:`Relancer ${i.number}`,detail:`${days} j de retard · ${clientLabel(clients.find(c=>c.id===i.client_id))}`,amount:remaining,href:`/invoices/${i.id}`,entityId:i.id})});
   if(config.enabled.acceptedQuotes) quotes.filter(q=>q.status==='accepted'&&!invoices.some(i=>i.quote_id===q.id)).forEach(q=>rows.push({id:`quote-${q.id}`,rule:'acceptedQuotes',severity:'critical',title:`Facturer ${q.number}`,detail:`Devis accepté non facturé · ${clientLabel(clients.find(c=>c.id===q.client_id))}`,amount:total(q),href:`/quotes/${q.id}`,entityId:q.id}));
   if(config.enabled.assignment) missions.filter(m=>!m.assigned_user_id&&!terminal(m.status)).forEach(m=>rows.push({id:`assign-${m.id}`,rule:'assignment',severity:'warning',title:`Affecter ${m.title}`,detail:'Aucun responsable désigné',href:`/missions/${m.id}`,entityId:m.id}));
   if(config.enabled.planning) missions.filter(m=>!m.scheduled_start&&!terminal(m.status)).forEach(m=>rows.push({id:`plan-${m.id}`,rule:'planning',severity:'info',title:`Planifier ${m.title}`,detail:`À placer dans les ${config.planningDays} prochains jours`,href:`/missions/${m.id}`,entityId:m.id}));
   if(config.enabled.stock) inventory.filter(x=>x.quantity<=x.minimum_quantity*config.stockMultiplier).forEach(x=>rows.push({id:`stock-${x.id}`,rule:'stock',severity:x.quantity<=0?'critical':'warning',title:`Réapprovisionner ${x.name}`,detail:`Stock ${x.quantity} ${x.unit} · seuil ${x.minimum_quantity}`,href:'/inventory',entityId:x.id}));
   if(config.enabled.closeout) missions.filter(m=>m.status==='completed'&&!invoices.some(i=>i.mission_id===m.id)).forEach(m=>rows.push({id:`close-${m.id}`,rule:'closeout',severity:'warning',title:`Clôturer financièrement ${m.title}`,detail:'Chantier terminé sans facture associée',href:`/missions/${m.id}`,entityId:m.id}));
   const order={critical:0,warning:1,info:2}; return rows.sort((a,b)=>order[a.severity]-order[b.severity]);
 },[clients,missions,quotes,invoices,inventory,config,now]);
 const metrics=useMemo(()=>{const overdue=actions.filter(a=>a.rule==='collections').reduce((s,a)=>s+(a.amount||0),0);const pipeline=actions.filter(a=>a.rule==='acceptedQuotes').reduce((s,a)=>s+(a.amount||0),0);const active=timeEntries.filter(t=>!t.ended_at).length;const critical=actions.filter(a=>a.severity==='critical').length;const score=Math.max(0,100-critical*12-actions.filter(a=>a.severity==='warning').length*4-Math.min(20,actions.filter(a=>a.severity==='info').length*2));return {overdue,pipeline,active,critical,score}},[actions,timeEntries]);
 function save(next:Config){setConfig(next);localStorage.setItem(KEY,JSON.stringify(next))}
 function addLog(text:string){const next=[`${new Date().toLocaleString('fr-FR')} — ${text}`,...log].slice(0,40);setLog(next);localStorage.setItem(`${KEY}.log`,JSON.stringify(next))}
 function execute(a:Action){try{
   if(a.rule==='acceptedQuotes'&&a.entityId){convertQuoteToInvoice(a.entityId,new Date(Date.now()+30*DAY).toISOString());addLog(`${a.title} : facture créée`);return}
   if(a.rule==='assignment'&&a.entityId){const active=team.filter(t=>t.active);if(!active.length){alert('Aucun membre actif.');return}const loads=new Map(active.map(t=>[t.id,missions.filter(m=>m.assigned_user_id===t.id&&!terminal(m.status)).length]));active.sort((x,y)=>(loads.get(x.id)||0)-(loads.get(y.id)||0));assignMission(a.entityId,active[0].id);addLog(`${a.title} → ${active[0].name}`);return}
   if(a.rule==='planning'&&a.entityId){const d=new Date();d.setDate(d.getDate()+1);d.setHours(8,0,0,0);const end=new Date(d);end.setHours(12);updateMissionSchedule(a.entityId,d.toISOString(),end.toISOString());addLog(`${a.title} → demain 08:00`);return}
   addLog(`${a.title} : action ouverte`);
  }catch(e){alert(e instanceof Error?e.message:'Action impossible')}}
 function runSafe(){const stamp=new Date().toISOString();setLastRun(stamp);localStorage.setItem(`${KEY}.lastRun`,stamp);addLog(`Analyse terminée : ${actions.length} action(s), ${metrics.critical} critique(s)`)}
 function executeSafeBatch(){const batch=actions.filter(a=>['acceptedQuotes','assignment','planning'].includes(a.rule)).slice(0,10);if(!batch.length){alert('Aucune automatisation sûre à exécuter.');return}if(!confirm(`Exécuter ${batch.length} automatisation(s) sûres ?`))return;batch.forEach(execute);runSafe()}
 const labels:Record<RuleKey,string>={collections:'Relances impayés',acceptedQuotes:'Devis acceptés → factures',planning:'Planning automatique',assignment:'Affectation équipe',stock:'Alertes stock',closeout:'Clôture chantier'};
 return <div className="page"><div className="page-header"><div><span className="eyebrow">CloserFlow v13.6</span><h1><Bot/> Business Autopilot</h1><p>Détecte ce qui bloque l’entreprise et prépare les prochaines actions sans masquer les décisions sensibles.</p></div><button className="primary" onClick={runSafe}><RefreshCcw/> Analyser</button></div>
 <div className="stats-grid"><div className="stat-card"><Gauge/><span>Score opérationnel</span><strong>{metrics.score}/100</strong></div><div className="stat-card"><CircleDollarSign/><span>Impayés détectés</span><strong>{euro(metrics.overdue)}</strong></div><div className="stat-card"><FileCheck2/><span>À facturer</span><strong>{euro(metrics.pipeline)}</strong></div><div className="stat-card"><AlertTriangle/><span>Critiques</span><strong>{metrics.critical}</strong></div></div>
 <section className="panel"><div className="section-title"><div><h2><WandSparkles/> Automatisation contrôlée</h2><p>Les actions financières sensibles restent manuelles. Les tâches organisationnelles peuvent être exécutées en lot.</p></div><button className="primary" onClick={executeSafeBatch}><Play/> Exécuter le lot sûr</button></div><div className="grid-2">{(Object.keys(labels) as RuleKey[]).map(k=><label className="menu-card" key={k}><input type="checkbox" checked={config.enabled[k]} onChange={e=>save({...config,enabled:{...config.enabled,[k]:e.target.checked}})}/><div><strong>{labels[k]}</strong><small>{k==='collections'||k==='stock'||k==='closeout'?'Détection + validation humaine':'Automatisation disponible'}</small></div></label>)}</div></section>
 <section className="panel"><div className="section-title"><div><h2><Rocket/> File d’actions</h2><p>{actions.length} action(s) classée(s) par impact.</p></div></div>{actions.length===0?<div className="empty-state"><CheckCircle2/><h3>Tout est sous contrôle</h3><p>Aucun blocage détecté avec les règles actives.</p></div>:<div className="list">{actions.slice(0,30).map(a=><div className={`list-row ${a.severity}`} key={a.id}><div><strong>{a.title}</strong><small>{a.detail}{a.amount?` · ${euro(a.amount)}`:''}</small></div><div className="row-actions">{['acceptedQuotes','assignment','planning'].includes(a.rule)&&<button onClick={()=>execute(a)}><Sparkles/> Exécuter</button>}<Link className="button" to={a.href}>Ouvrir</Link></div></div>)}</div>}</section>
 <div className="grid-2"><section className="panel"><h2><Target/> Paramètres moteur</h2><label>Retard minimum impayé<input type="number" min="0" value={config.overdueDays} onChange={e=>save({...config,overdueDays:+e.target.value||0})}/></label><label>Horizon planning (jours)<input type="number" min="1" max="60" value={config.planningDays} onChange={e=>save({...config,planningDays:+e.target.value||7})}/></label><label>Multiplicateur seuil stock<input type="number" min="0.5" max="5" step="0.5" value={config.stockMultiplier} onChange={e=>save({...config,stockMultiplier:+e.target.value||1})}/></label></section>
 <section className="panel"><h2><ShieldCheck/> Journal Autopilot</h2><p>Dernière analyse : {lastRun?new Date(lastRun).toLocaleString('fr-FR'):'jamais'}</p>{log.length?<div className="list">{log.slice(0,8).map((x,i)=><div className="list-row" key={`${x}-${i}`}><small>{x}</small></div>)}</div>:<p>Aucune exécution enregistrée.</p>}</section></div>
 <section className="panel"><h2><UsersRound/> Raccourcis de pilotage</h2><div className="quick-actions"><Link to="/revenue-ops"><HandCoins/> Revenue Ops</Link><Link to="/execution-suite"><Gauge/> Centre d’exécution</Link><Link to="/planning"><CalendarClock/> Planning</Link><Link to="/inventory"><PackageSearch/> Stock</Link></div></section></div>
}
