import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, ArrowRight, BadgeEuro, CalendarClock, CheckCircle2, CircleDollarSign, Gauge, PiggyBank, RefreshCw, ShieldCheck, Target, TrendingDown, TrendingUp, WalletCards } from 'lucide-react';
import { useAppData } from '../context/AppDataContext';
import { totals } from '../lib/documents';
type Scenario='prudent'|'base'|'ambitious'; type CashEvent={id:string;date:string;label:string;amount:number;kind:'in'|'out';route:string;confidence:number};
const euro=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}), KEY='closerflow.v21.cash.settings', defaults={openingCash:5000,monthlyFixedCosts:1800,scenario:'base' as Scenario};
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return defaults}} function day(v:string|null|undefined){const d=v?new Date(v):new Date();return Number.isNaN(d.getTime())?new Date():d} const iso=(d:Date)=>d.toISOString().slice(0,10);
export function CashPilotV21Page(){const {invoices,quotes,missions,businessExpenses,maintenanceContracts}=useAppData();const [settings,setSettings]=useState(load);const save=(x:typeof defaults)=>{setSettings(x);localStorage.setItem(KEY,JSON.stringify(x))};
const model=useMemo(()=>{const now=new Date(),horizon=new Date(now);horizon.setDate(horizon.getDate()+90);const factor=settings.scenario==='prudent'?.65:settings.scenario==='ambitious'?1.12:.88;const events:CashEvent[]=[];
invoices.forEach(i=>{const t=totals(i.lines,i.discount_percent,i.vat_rate).ttc,p=(i.payments??[]).reduce((s,x)=>s+x.amount,0),r=Math.max(0,t-p);if(r>.01&&i.status!=='paid')events.push({id:'i'+i.id,date:iso(day(i.due_date||i.created_at)),label:`${i.number} · ${i.title}`,amount:r,kind:'in',route:`/invoices/${i.id}`,confidence:i.status==='overdue'?95:90})});
quotes.filter(q=>q.status==='accepted'||q.status==='sent').forEach(q=>{const d=day(q.created_at);d.setDate(d.getDate()+(q.status==='accepted'?30:45));events.push({id:'q'+q.id,date:iso(d),label:`Pipeline ${q.number} · ${q.title}`,amount:totals(q.lines,q.discount_percent,q.vat_rate).ttc*factor*(q.status==='accepted'?.9:.35),kind:'in',route:`/quotes/${q.id}`,confidence:q.status==='accepted'?80:35})});
maintenanceContracts.filter(c=>c.active).forEach(c=>{const d=day(c.next_due_date);if(d<=horizon)events.push({id:'c'+c.id,date:iso(d),label:`Contrat · ${c.title}`,amount:c.amount_ht*(1+c.vat_rate/100),kind:'in',route:'/contracts',confidence:85})});
businessExpenses.filter(e=>!e.paid).forEach(e=>events.push({id:'e'+e.id,date:e.expense_date,label:`${e.supplier||'Dépense'} · ${e.label}`,amount:e.amount_ht*(1+e.vat_rate/100),kind:'out',route:'/expenses',confidence:95}));
for(let m=0;m<3;m++){const d=new Date(now.getFullYear(),now.getMonth()+m+1,1);events.push({id:'f'+m,date:iso(d),label:'Charges fixes estimées',amount:settings.monthlyFixedCosts,kind:'out',route:'/expenses',confidence:100})}
const rows=events.filter(e=>day(e.date)<=horizon).sort((a,b)=>a.date.localeCompare(b.date));let balance=settings.openingCash,minimum=balance,minDate=iso(now);const projected=rows.map(e=>{balance+=e.kind==='in'?e.amount:-e.amount;if(balance<minimum){minimum=balance;minDate=e.date}return {...e,balance}});
const incoming=rows.filter(e=>e.kind==='in').reduce((s,e)=>s+e.amount,0),outgoing=rows.filter(e=>e.kind==='out').reduce((s,e)=>s+e.amount,0);const overdue=invoices.reduce((s,i)=>{if(i.status!=='overdue')return s;const t=totals(i.lines,i.discount_percent,i.vat_rate).ttc,p=(i.payments??[]).reduce((a,x)=>a+x.amount,0);return s+Math.max(0,t-p)},0);const unbilled=missions.filter(m=>m.status==='completed'&&!invoices.some(i=>i.mission_id===m.id)).reduce((s,m)=>s+(m.price_ht||0),0);
const alerts=[] as {level:'critical'|'warning'|'good';title:string;detail:string;route:string}[];if(minimum<0)alerts.push({level:'critical',title:'Risque de trésorerie négative',detail:`Point bas ${euro.format(minimum)} vers le ${new Date(minDate).toLocaleDateString('fr-FR')}.`,route:'/cashflow'});if(overdue>0)alerts.push({level:'warning',title:'Encaissements à accélérer',detail:`${euro.format(overdue)} actuellement en retard.`,route:'/follow-ups'});if(unbilled>0)alerts.push({level:'warning',title:'CA terminé non facturé',detail:`Environ ${euro.format(unbilled)} HT de missions terminées à facturer.`,route:'/invoices'});if(!alerts.length)alerts.push({level:'good',title:'Projection saine',detail:'Aucun risque majeur détecté sur les données actuelles.',route:'/cashflow'});return {rows:projected,incoming,outgoing,ending:balance,minimum,alerts,overdue,unbilled}},[invoices,quotes,missions,businessExpenses,maintenanceContracts,settings]);
const health=Math.max(0,Math.min(100,Math.round(100-(model.minimum<0?45:0)-(model.overdue>0?20:0)-(model.unbilled>0?10:0))));
return <><div className="page-title"><div><p className="eyebrow">CLOSERFLOW 21 · CASH PILOT</p><h1>Trésorerie prédictive</h1><p>Projection à 90 jours, scénarios et priorités financières à partir des données CloserFlow.</p></div><Link className="primary" to="/finance-autopilot"><WalletCards/>Finance Autopilot</Link></div>
<section className="v21-kpis"><article><PiggyBank/><span>Trésorerie de départ</span><strong>{euro.format(settings.openingCash)}</strong></article><article><TrendingUp/><span>Entrées projetées</span><strong>{euro.format(model.incoming)}</strong></article><article><TrendingDown/><span>Sorties projetées</span><strong>{euro.format(model.outgoing)}</strong></article><article><CircleDollarSign/><span>Solde à 90 jours</span><strong>{euro.format(model.ending)}</strong></article><article><Gauge/><span>Score cash</span><strong>{health}/100</strong></article></section>
<section className="v21-grid"><div className="panel"><div className="section-heading"><div><p className="eyebrow">SCÉNARIO</p><h2>Hypothèses</h2></div><Target/></div><div className="v21-settings"><label>Trésorerie disponible<input type="number" value={settings.openingCash} onChange={e=>save({...settings,openingCash:Number(e.target.value)})}/></label><label>Charges fixes / mois<input type="number" value={settings.monthlyFixedCosts} onChange={e=>save({...settings,monthlyFixedCosts:Number(e.target.value)})}/></label><label>Scénario<select value={settings.scenario} onChange={e=>save({...settings,scenario:e.target.value as Scenario})}><option value="prudent">Prudent</option><option value="base">Base</option><option value="ambitious">Ambitieux</option></select></label></div><button className="ghost" onClick={()=>save(defaults)}><RefreshCw/>Réinitialiser</button></div>
<div className="panel"><div className="section-heading"><div><p className="eyebrow">PRIORITÉS</p><h2>Actions cash</h2></div><ShieldCheck/></div><div className="v21-alerts">{model.alerts.map((a,i)=><Link to={a.route} key={i} className={`v21-alert ${a.level}`}>{a.level==='critical'?<AlertTriangle/>:a.level==='good'?<CheckCircle2/>:<BadgeEuro/>}<div><strong>{a.title}</strong><small>{a.detail}</small></div><ArrowRight/></Link>)}</div></div></section>
<section className="panel"><div className="section-heading"><div><p className="eyebrow">90 JOURS</p><h2>Échéancier prévisionnel</h2></div><CalendarClock/></div><div className="v21-timeline">{model.rows.slice(0,40).map(e=><Link to={e.route} key={e.id} className="v21-row"><span>{new Date(e.date).toLocaleDateString('fr-FR')}</span><div><strong>{e.label}</strong><small>Confiance {e.confidence}%</small></div><b className={e.kind}>{e.kind==='in'?'+':'−'}{euro.format(e.amount)}</b><em>{euro.format(e.balance)}</em></Link>)}</div></section></>;}
