import { useMemo, useState } from 'react';
import { CalendarPlus, CheckCircle2, Clock3, MessageSquareText, ReceiptText, Sparkles, UserRoundCheck } from 'lucide-react';
import { useAppData } from '../context/AppDataContext';
import { totals } from '../lib/documents';

const euro=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n);
const date=(v:string)=>new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));
export function ClientExperienceV17Page(){
 const {clients,missions,quotes,invoices,portalMessages,portalPaymentIntents,portalEvents,appointmentRequests,addPortalMessage,updateAppointmentRequestStatus}=useAppData();
 const [clientId,setClientId]=useState(clients[0]?.id??''); const [message,setMessage]=useState('');
 const client=clients.find(c=>c.id===clientId);
 const stats=useMemo(()=>{const cq=quotes.filter(q=>q.client_id===clientId);const ci=invoices.filter(i=>i.client_id===clientId);const due=ci.reduce((s,i)=>s+Math.max(0,totals(i.lines,i.discount_percent,i.vat_rate).ttc-(i.payments??[]).reduce((a,p)=>a+p.amount,0)),0);return {missions:missions.filter(m=>m.client_id===clientId),quotes:cq,invoices:ci,due}},[clientId,missions,quotes,invoices]);
 const requests=appointmentRequests.filter(r=>r.client_id===clientId); const events=portalEvents.filter(e=>e.client_id===clientId).slice(0,8); const messages=portalMessages.filter(m=>m.client_id===clientId).slice(0,8); const pending=portalPaymentIntents.filter(p=>p.client_id===clientId&&p.status==='submitted');
 return <><div className="page-title"><div><p className="eyebrow">CLOSERFLOW 17 · EXPÉRIENCE CLIENT</p><h1>Relation client 360°</h1><p className="muted">Portail, demandes de rendez-vous, messages, signatures et paiements réunis.</p></div></div>
 <section className="detail-card v17-hero"><Sparkles/><div><strong>Un dossier client lisible de bout en bout</strong><p>Cette vue entreprise complète le portail public : elle centralise les actions du client et les prochaines réponses à traiter.</p></div></section>
 <section className="detail-card"><label>Client<select value={clientId} onChange={e=>setClientId(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name||`${c.first_name} ${c.last_name}`}</option>)}</select></label></section>
 <div className="portal-stats"><article><UserRoundCheck/><strong>{stats.missions.length}</strong><span>Chantiers</span></article><article><ReceiptText/><strong>{stats.invoices.length}</strong><span>Factures</span></article><article><Clock3/><strong>{requests.filter(r=>r.status==='pending').length}</strong><span>RDV à traiter</span></article><article><CheckCircle2/><strong>{euro(stats.due)}</strong><span>Reste à encaisser</span></article></div>
 <div className="v17-grid"><section className="detail-card"><h2><CalendarPlus/> Demandes de rendez-vous</h2><div className="stack-list">{requests.length===0?<p className="muted">Aucune demande.</p>:requests.map(r=><article className="portal-row" key={r.id}><div><strong>{r.preferred_date} · {r.preferred_period==='morning'?'Matin':r.preferred_period==='afternoon'?'Après-midi':r.preferred_period==='evening'?'Soir':'Indifférent'}</strong><small>{r.note||'Sans précision'} · {r.status}</small></div>{r.status==='pending'&&<div className="portal-actions"><button className="primary compact" onClick={()=>updateAppointmentRequestStatus(r.id,'accepted')}>Accepter</button><button className="secondary compact" onClick={()=>updateAppointmentRequestStatus(r.id,'rejected')}>Refuser</button></div>}</article>)}</div></section>
 <section className="detail-card"><h2><MessageSquareText/> Conversation</h2><div className="stack-list">{messages.map(m=><article className="portal-row" key={m.id}><div><strong>{m.author==='client'?'Client':'Entreprise'}</strong><small>{m.text} · {date(m.created_at)}</small></div></article>)}</div><div className="inline-form"><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Répondre au client"/><button className="primary compact" disabled={!message.trim()||!client} onClick={()=>{addPortalMessage(clientId,'company',message);setMessage('')}}>Envoyer</button></div></section></div>
 <section className="detail-card"><h2>Activité client récente</h2><div className="stack-list">{pending.map(p=><article className="portal-row" key={p.id}><div><strong>Paiement soumis · {euro(p.amount)}</strong><small>À confirmer depuis le portail client.</small></div></article>)}{events.length===0?<p className="muted">L’activité apparaîtra ici à mesure des interactions.</p>:events.map(e=><article className="portal-row" key={e.id}><div><strong>{e.label}</strong><small>{date(e.created_at)}</small></div></article>)}</div></section></>;
}
