import { useMemo, useState } from 'react';
import { CheckCircle2, CircleDollarSign, Download, FileText, LogOut, MessageSquareText, ReceiptText, ShieldCheck, Wrench, XCircle, Clock3, Images, CreditCard, Landmark, BadgeCheck } from 'lucide-react';
import { useAppData } from '../context/AppDataContext';
import { totals } from '../lib/documents';
import { SignaturePad } from '../components/SignaturePad';
import type { Invoice, PortalPaymentIntent, Quote } from '../types/domain';

const euros=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n);
const date=(value:string|null)=>value?new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:value.includes('T')?'short':undefined}).format(new Date(value)):'—';
const escapeHtml=(value:string)=>value.replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]||char));
const missionSteps=['prospect','visit','quote','accepted','planned','in_progress','completed','invoiced','paid'];
const missionLabels:Record<string,string>={prospect:'Demande reçue',visit:'Visite',quote:'Devis',accepted:'Accepté',planned:'Planifié',in_progress:'En cours',completed:'Terminé',invoiced:'Facturé',paid:'Payé',archived:'Archivé'};

function downloadDocument(kind:'Devis'|'Facture',doc:Quote|Invoice,companyName:string,clientName:string){
 const amount=totals(doc.lines,doc.discount_percent,doc.vat_rate);
 const rows=doc.lines.map(line=>`<tr><td>${escapeHtml(line.description)}</td><td>${line.quantity} ${escapeHtml(line.unit)}</td><td>${euros(line.unit_price_ht)}</td><td>${euros(line.quantity*line.unit_price_ht)}</td></tr>`).join('');
 const html=`<!doctype html><html lang="fr"><meta charset="utf-8"><title>${kind} ${escapeHtml(doc.number)}</title><style>body{font-family:Arial,sans-serif;max-width:850px;margin:40px auto;color:#172033}h1{margin-bottom:4px}.muted{color:#64748b}table{width:100%;border-collapse:collapse;margin-top:28px}th,td{padding:12px;border-bottom:1px solid #ddd;text-align:left}.totals{margin:28px 0 0 auto;width:320px}.totals div{display:flex;justify-content:space-between;padding:7px}.total{font-weight:800;font-size:18px;border-top:2px solid #172033}</style><body><h1>${kind} ${escapeHtml(doc.number)}</h1><p class="muted">${escapeHtml(companyName)} · Client : ${escapeHtml(clientName)}</p><h2>${escapeHtml(doc.title)}</h2><table><thead><tr><th>Description</th><th>Quantité</th><th>Prix unitaire HT</th><th>Total HT</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><div><span>HT</span><strong>${euros(amount.ht)}</strong></div><div><span>TVA</span><strong>${euros(amount.vat)}</strong></div><div class="total"><span>TTC</span><strong>${euros(amount.ttc)}</strong></div></div><p class="muted">Document généré depuis le portail CloserFlow.</p></body></html>`;
 const blob=new Blob([html],{type:'text/html;charset=utf-8'}); const url=URL.createObjectURL(blob); const link=document.createElement('a');link.href=url;link.download=`${doc.number}.html`;link.click();URL.revokeObjectURL(url);
}

export function ClientPortalPage(){
 const {company,clients,missions,quotes,invoices,quoteApprovals,portalMessages,portalPaymentIntents,approveQuote,addPortalMessage,markPortalMessagesRead,requestPortalPayment,submitPortalPayment,confirmPortalPayment,cancelPortalPayment,addAppointmentRequest,appointmentRequests,logPortalEvent}=useAppData();
 const [clientId,setClientId]=useState(''); const [code,setCode]=useState(''); const [session,setSession]=useState<string|null>(null);
 const [decision,setDecision]=useState<{quoteId:string;kind:'accepted'|'rejected'}|null>(null); const [comment,setComment]=useState(''); const [message,setMessage]=useState(''); const [payment,setPayment]=useState<{invoiceId:string;method:PortalPaymentIntent['method']}|null>(null); const [paymentNote,setPaymentNote]=useState(''); const [appointmentDate,setAppointmentDate]=useState(''); const [appointmentPeriod,setAppointmentPeriod]=useState<'morning'|'afternoon'|'evening'|'any'>('any'); const [appointmentNote,setAppointmentNote]=useState('');
 const client=clients.find(c=>c.id===session)??null; const expectedCode=(clients.find(c=>c.id===clientId)?.phone||'').replace(/\D/g,'').slice(-4)||'0000';
 const data=useMemo(()=>({missions:missions.filter(m=>m.client_id===session),quotes:quotes.filter(q=>q.client_id===session),invoices:invoices.filter(i=>i.client_id===session),messages:portalMessages.filter(m=>m.client_id===session).sort((a,b)=>a.created_at.localeCompare(b.created_at)),payments:portalPaymentIntents.filter(p=>p.client_id===session)}),[missions,quotes,invoices,portalMessages,portalPaymentIntents,session]);
 const pendingCompany=portalPaymentIntents.filter(p=>p.status==='submitted');
 if(!session)return <div className="portal-wrap"><section className="portal-login"><div className="portal-logo">C</div><p className="eyebrow">PORTAIL CLIENT V10.2</p><h1>{company.name}</h1><p>Suivi de chantier, documents, signature, paiements et messagerie dans un seul espace.</p><label>Votre dossier<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Sélectionner votre nom</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name||`${c.first_name} ${c.last_name}`}</option>)}</select></label><label>Code d’accès<input inputMode="numeric" maxLength={4} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="4 chiffres"/></label><button className="primary" disabled={!clientId||code.length!==4} onClick={()=>{if(code===expectedCode){setSession(clientId);markPortalMessagesRead(clientId);logPortalEvent(clientId,'view','Ouverture du portail client')}else alert('Code incorrect. En démonstration : les 4 derniers chiffres du téléphone client, ou 0000.')}}><ShieldCheck/>Accéder à mon espace</button><small>Version locale de démonstration. Une ouverture publique doit utiliser HTTPS et une authentification serveur.</small>{pendingCompany.length>0&&<div className="portal-company-review"><strong>Validation entreprise · {pendingCompany.length} paiement(s)</strong>{pendingCompany.map(intent=>{const invoice=invoices.find(i=>i.id===intent.invoice_id);return <div key={intent.id}><span>{invoice?.number||'Facture'} · {euros(intent.amount)}</span><button className="primary compact" onClick={()=>confirmPortalPayment(intent.id)}><BadgeCheck/>Confirmer</button><button className="ghost compact" onClick={()=>cancelPortalPayment(intent.id)}>Annuler</button></div>})}</div>}</section></div>;
 const clientName=client?.company_name||`${client?.first_name||''} ${client?.last_name||''}`.trim();
 return <><div className="page-title"><div><p className="eyebrow">PORTAIL CLIENT V10.2</p><h1>Bonjour {client?.first_name||client?.company_name}</h1><p className="muted">Votre dossier chez {company.name}</p></div><button className="secondary compact" onClick={()=>{setSession(null);setCode('')}}><LogOut/>Quitter</button></div>
 <div className="portal-stats"><article><Wrench/><strong>{data.missions.length}</strong><span>Interventions</span></article><article><FileText/><strong>{data.quotes.length}</strong><span>Devis</span></article><article><ReceiptText/><strong>{data.invoices.length}</strong><span>Factures</span></article><article><CircleDollarSign/><strong>{data.payments.filter(p=>p.status==='submitted').length}</strong><span>Paiements à valider</span></article></div>
 <section className="detail-card"><h2><Clock3/> Avancement des chantiers</h2><div className="stack-list">{data.missions.length===0?<p className="muted">Aucune intervention.</p>:data.missions.map(m=>{const step=Math.max(0,missionSteps.indexOf(m.status));const progress=m.status==='archived'?100:Math.round(((step+1)/missionSteps.length)*100);return <article className="portal-project" key={m.id}><div className="portal-row"><div><strong>{m.title}</strong><small>{date(m.scheduled_start)} · {m.address||'Adresse non renseignée'}</small></div><span>{missionLabels[m.status]||m.status}</span></div><div className="portal-progress"><i style={{width:`${progress}%`}}/></div><div className="portal-project-meta"><span>{progress}%</span><span><Images/> {(m.photos??[]).length} photo(s)</span><span>{(m.tasks??[]).filter(t=>t.done).length}/{(m.tasks??[]).length} tâches</span></div>{(m.photos??[]).length>0&&<div className="portal-photo-strip">{(m.photos??[]).slice(-4).map(photo=><img key={photo.id} src={photo.data_url} alt={photo.caption||m.title}/>)}</div>}</article>})}</div></section>
 <section className="detail-card"><h2><Clock3/> Demander un rendez-vous</h2><p className="muted">Proposez une date à l’entreprise. Elle pourra confirmer ou refuser depuis CloserFlow.</p><div className="inline-form"><input type="date" value={appointmentDate} onChange={e=>setAppointmentDate(e.target.value)}/><select value={appointmentPeriod} onChange={e=>setAppointmentPeriod(e.target.value as any)}><option value="any">Indifférent</option><option value="morning">Matin</option><option value="afternoon">Après-midi</option><option value="evening">Soir</option></select><input value={appointmentNote} onChange={e=>setAppointmentNote(e.target.value)} placeholder="Motif ou disponibilité"/><button className="primary compact" disabled={!appointmentDate} onClick={()=>{addAppointmentRequest(session,data.missions[0]?.id??null,appointmentDate,appointmentPeriod,appointmentNote);setAppointmentDate('');setAppointmentNote('')}}>Envoyer la demande</button></div><div className="stack-list">{appointmentRequests.filter(r=>r.client_id===session).slice(0,3).map(r=><article className="portal-row" key={r.id}><div><strong>{r.preferred_date}</strong><small>{r.note||'Demande de rendez-vous'} · {r.status}</small></div></article>)}</div></section>
 <section className="detail-card"><h2>Devis et signature électronique</h2><div className="stack-list">{data.quotes.length===0?<p className="muted">Aucun devis.</p>:data.quotes.map(q=>{const total=totals(q.lines,q.discount_percent,q.vat_rate).ttc;const approval=quoteApprovals.find(a=>a.quote_id===q.id);return <article className="portal-row" key={q.id}><div><strong>{q.number} · {q.title}</strong><small>{date(q.created_at)} · {euros(total)} TTC{approval?` · signé par ${approval.signer_name} le ${date(approval.decided_at)}`:''}</small></div><div className="portal-actions"><button className="secondary compact" onClick={()=>downloadDocument('Devis',q,company.name,clientName)}><Download/>Télécharger</button>{q.status==='sent'&&<><button className="primary compact" onClick={()=>setDecision({quoteId:q.id,kind:'accepted'})}><CheckCircle2/>Signer et accepter</button><button className="secondary compact" onClick={()=>setDecision({quoteId:q.id,kind:'rejected'})}><XCircle/>Refuser</button></>}<span>{q.status}</span></div></article>})}</div></section>
 <section className="detail-card"><h2>Factures et paiements</h2><div className="stack-list">{data.invoices.length===0?<p className="muted">Aucune facture.</p>:data.invoices.map(i=>{const total=totals(i.lines,i.discount_percent,i.vat_rate).ttc;const paid=(i.payments||[]).reduce((s,p)=>s+p.amount,0);const remaining=Math.max(0,total-paid);const intent=data.payments.find(p=>p.invoice_id===i.id&&p.status!=='cancelled');return <article className="portal-invoice" key={i.id}><div className="portal-row"><div><strong>{i.number} · {i.title}</strong><small>{euros(total)} TTC · payé {euros(paid)} · reste {euros(remaining)} · échéance {date(i.due_date)}</small>{company.iban&&remaining>0&&<small>Virement : {company.iban}</small>}</div><div className="portal-actions"><button className="secondary compact" onClick={()=>downloadDocument('Facture',i,company.name,clientName)}><Download/>Télécharger</button>{remaining>0&&!intent&&<button className="primary compact" onClick={()=>setPayment({invoiceId:i.id,method:'transfer'})}><CreditCard/>Déclarer un paiement</button>}<span>{i.status}</span></div></div>{intent&&<div className={`payment-intent ${intent.status}`}><strong>{intent.status==='requested'?'Paiement préparé':intent.status==='submitted'?'Paiement déclaré, en attente de validation':intent.status==='confirmed'?'Paiement confirmé':'Demande annulée'}</strong><small>{euros(intent.amount)} · {intent.method} · {date(intent.submitted_at||intent.created_at)}</small>{intent.status==='requested'&&<button className="primary compact" onClick={()=>submitPortalPayment(intent.id,intent.note)}>Confirmer que le paiement est effectué</button>}</div>}</article>})}</div></section>
 <section className="detail-card"><h2><MessageSquareText/> Messagerie chantier</h2><div className="portal-thread">{data.messages.length===0?<p className="muted">Aucun message.</p>:data.messages.map(m=><div key={m.id} className={`portal-message ${m.author}`}><strong>{m.author==='client'?'Vous':company.name}</strong><p>{m.text}</p><small>{date(m.created_at)}</small></div>)}</div><div className="portal-compose"><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Écrire un message à l’entreprise"/><button className="primary" disabled={!message.trim()} onClick={()=>{addPortalMessage(session,'client',message);setMessage('')}}>Envoyer</button></div></section>
 {decision&&<div className="modal-backdrop"><section className="modal-card"><h2>{decision.kind==='accepted'?'Signer et accepter le devis':'Refuser le devis'}</h2><label>Commentaire<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Facultatif"/></label><SignaturePad onSave={(dataUrl,name)=>{approveQuote(decision.quoteId,session,decision.kind,name,dataUrl,comment);setDecision(null);setComment('')}}/><button className="ghost" onClick={()=>setDecision(null)}>Annuler</button></section></div>}
 {payment&&<div className="modal-backdrop"><section className="modal-card"><h2>Déclarer un paiement</h2><label>Moyen de paiement<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value as PortalPaymentIntent['method']})}><option value="transfer">Virement bancaire</option><option value="card_link">Lien de paiement externe</option><option value="cash">Espèces</option><option value="check">Chèque</option></select></label><label>Référence ou commentaire<textarea value={paymentNote} onChange={e=>setPaymentNote(e.target.value)} placeholder="Ex. virement effectué le 21/07"/></label><div className="payment-help">{payment.method==='transfer'?<><Landmark/><span>Utilisez l’IBAN affiché sur la facture puis confirmez votre déclaration.</span></>:<><CreditCard/><span>CloserFlow prépare le suivi. La transaction réelle reste gérée par le prestataire choisi.</span></>}</div><button className="primary" onClick={()=>{const invoice=invoices.find(i=>i.id===payment.invoiceId);if(!invoice)return;const total=totals(invoice.lines,invoice.discount_percent,invoice.vat_rate).ttc;const paid=(invoice.payments||[]).reduce((s,p)=>s+p.amount,0);const intent=requestPortalPayment(invoice.id,session,Math.max(0,total-paid),payment.method,paymentNote);submitPortalPayment(intent.id,paymentNote);setPayment(null);setPaymentNote('')}}>J’ai effectué le paiement</button><button className="ghost" onClick={()=>setPayment(null)}>Annuler</button></section></div>}
 </>;
}
