import { useMemo, useState } from 'react';
import { Bell, CalendarClock, Check, ChevronRight, Download, Mail, MessageSquare, Phone, Plus, Trash2, TrendingUp, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAppData } from '../context/AppDataContext';
import { createId } from '../lib/id';
import { money, totals } from '../lib/documents';

type Stage='prospect'|'qualified'|'quote'|'won'|'lost';
type Opportunity={id:string;clientId:string;title:string;amount:number;stage:Stage;probability:number;nextAction:string;nextActionAt:string;createdAt:string};
type Activity={id:string;clientId:string;type:'call'|'email'|'meeting'|'note';text:string;createdAt:string};
const OP_KEY='closerflow.crm.opportunities.v9_4'; const ACT_KEY='closerflow.crm.activities.v9_4';
const stages:{id:Stage;label:string}[]=[{id:'prospect',label:'Prospects'},{id:'qualified',label:'Qualifiés'},{id:'quote',label:'Devis envoyés'},{id:'won',label:'Gagnés'},{id:'lost',label:'Perdus'}];
function read<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)??'') as T}catch{return fallback}}
function save<T>(key:string,value:T){localStorage.setItem(key,JSON.stringify(value))}
export function CommercialCrmPage(){
 const {clients,quotes,invoices,missions}=useAppData();
 const seed=useMemo<Opportunity[]>(()=>quotes.slice(0,4).map(q=>({id:`quote-${q.id}`,clientId:q.client_id??'',title:q.title,amount:totals(q.lines,q.discount_percent,q.vat_rate).ttc,stage:q.status==='accepted'?'won':q.status==='rejected'?'lost':'quote',probability:q.status==='accepted'?100:60,nextAction:'Relancer le devis',nextActionAt:new Date(Date.now()+3*86400000).toISOString().slice(0,10),createdAt:q.created_at})),[quotes]);
 const [opportunities,setOpportunities]=useState<Opportunity[]>(()=>read(OP_KEY,seed));
 const [activities,setActivities]=useState<Activity[]>(()=>read(ACT_KEY,[]));
 const [showForm,setShowForm]=useState(false); const [activityClient,setActivityClient]=useState('');
 const [form,setForm]=useState({clientId:clients[0]?.id??'',title:'',amount:'',stage:'prospect' as Stage,nextAction:'',nextActionAt:''});
 const name=(id:string)=>{const c=clients.find(x=>x.id===id);return c?.company_name||`${c?.first_name??''} ${c?.last_name??''}`.trim()||'Client'};
 const persistOps=(rows:Opportunity[])=>{setOpportunities(rows);save(OP_KEY,rows)}; const persistActs=(rows:Activity[])=>{setActivities(rows);save(ACT_KEY,rows)};
 function addOpportunity(e:React.FormEvent){e.preventDefault();if(!form.clientId||!form.title.trim())return;persistOps([{id:createId(),clientId:form.clientId,title:form.title.trim(),amount:Number(form.amount)||0,stage:form.stage,probability:form.stage==='won'?100:form.stage==='lost'?0:form.stage==='quote'?60:30,nextAction:form.nextAction.trim(),nextActionAt:form.nextActionAt,createdAt:new Date().toISOString()},...opportunities]);setShowForm(false);setForm({...form,title:'',amount:'',nextAction:'',nextActionAt:''})}
 function move(id:string,dir:number){persistOps(opportunities.map(o=>{if(o.id!==id)return o;const i=stages.findIndex(s=>s.id===o.stage);const stage=stages[Math.max(0,Math.min(stages.length-1,i+dir))].id;return {...o,stage,probability:stage==='won'?100:stage==='lost'?0:stage==='quote'?60:stage==='qualified'?45:25}}))}
 function logActivity(type:Activity['type'],text:string){if(!activityClient||!text.trim())return;persistActs([{id:createId(),clientId:activityClient,type,text:text.trim(),createdAt:new Date().toISOString()},...activities])}
 const open=opportunities.filter(o=>!['won','lost'].includes(o.stage)); const weighted=open.reduce((s,o)=>s+o.amount*o.probability/100,0); const won=opportunities.filter(o=>o.stage==='won').reduce((s,o)=>s+o.amount,0); const conversion=opportunities.length?Math.round(opportunities.filter(o=>o.stage==='won').length/opportunities.length*100):0;
 const due=open.filter(o=>o.nextActionAt&&new Date(o.nextActionAt).getTime()<=Date.now()+7*86400000).sort((a,b)=>a.nextActionAt.localeCompare(b.nextActionAt));
 function exportCsv(){const rows=[['Client','Opportunité','Montant','Étape','Probabilité','Prochaine action','Échéance'],...opportunities.map(o=>[name(o.clientId),o.title,String(o.amount),o.stage,String(o.probability),o.nextAction,o.nextActionAt])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='closerflow-crm.csv';a.click();URL.revokeObjectURL(a.href)}
 return <><div className="page-title"><div><p className="eyebrow">CRM COMMERCIAL v9.4</p><h1>Pipeline commercial</h1><p>Prospects, relances, historique et conversion dans une seule vue.</p></div><div className="team-actions"><button className="ghost" onClick={exportCsv}><Download/>Export CSV</button><button className="primary" onClick={()=>setShowForm(!showForm)}><Plus/>Opportunité</button></div></div>
 <section className="crm-kpis"><article><Users/><span>Pipeline ouvert</span><strong>{money(open.reduce((s,o)=>s+o.amount,0))}</strong></article><article><TrendingUp/><span>Prévision pondérée</span><strong>{money(weighted)}</strong></article><article><Check/><span>Ventes gagnées</span><strong>{money(won)}</strong></article><article><ChevronRight/><span>Conversion</span><strong>{conversion}%</strong></article></section>
 {showForm&&<form className="panel crm-form" onSubmit={addOpportunity}><h2>Nouvelle opportunité</h2><label>Client<select value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}>{clients.map(c=><option key={c.id} value={c.id}>{name(c.id)}</option>)}</select></label><label>Projet<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Montant estimé<input type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Étape<select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value as Stage})}>{stages.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label>Prochaine action<input value={form.nextAction} onChange={e=>setForm({...form,nextAction:e.target.value})}/></label><label>Échéance<input type="date" value={form.nextActionAt} onChange={e=>setForm({...form,nextActionAt:e.target.value})}/></label><button className="primary" type="submit">Enregistrer</button></form>}
 <section className="crm-board">{stages.map((stage,stageIndex)=><div className="crm-column" key={stage.id}><header><strong>{stage.label}</strong><span>{opportunities.filter(o=>o.stage===stage.id).length}</span></header>{opportunities.filter(o=>o.stage===stage.id).map(o=><article className="crm-card" key={o.id}><div><small>{name(o.clientId)}</small><h3>{o.title}</h3><strong>{money(o.amount)}</strong></div>{o.nextAction&&<p><CalendarClock/>{o.nextAction}{o.nextActionAt&&` · ${new Date(o.nextActionAt).toLocaleDateString('fr-FR')}`}</p>}<footer>{stageIndex>0&&<button className="icon-button" onClick={()=>move(o.id,-1)}>←</button>}{stageIndex<stages.length-1&&<button className="icon-button" onClick={()=>move(o.id,1)}>→</button>}<button className="icon-button danger" onClick={()=>persistOps(opportunities.filter(x=>x.id!==o.id))}><Trash2/></button></footer></article>)}</div>)}</section>
 <section className="crm-bottom"><div className="panel"><h2><Bell/>Actions à venir</h2>{due.map(o=><div className="crm-reminder" key={o.id}><div><strong>{name(o.clientId)}</strong><span>{o.nextAction||o.title}</span></div><time>{new Date(o.nextActionAt).toLocaleDateString('fr-FR')}</time></div>)}{!due.length&&<p className="muted">Aucune relance prévue dans les 7 prochains jours.</p>}<Link className="ghost" to="/follow-ups">Ouvrir le centre de relance</Link></div>
 <div className="panel"><h2><MessageSquare/>Historique client</h2><select value={activityClient} onChange={e=>setActivityClient(e.target.value)}><option value="">Choisir un client</option>{clients.map(c=><option key={c.id} value={c.id}>{name(c.id)}</option>)}</select>{activityClient&&<div className="crm-quick-actions"><button onClick={()=>logActivity('call','Appel client effectué')}><Phone/>Appel</button><button onClick={()=>logActivity('email','E-mail envoyé au client')}><Mail/>E-mail</button><button onClick={()=>{const text=prompt('Note commerciale');if(text)logActivity('note',text)}}><MessageSquare/>Note</button></div>}{activities.filter(a=>!activityClient||a.clientId===activityClient).slice(0,8).map(a=><div className="crm-activity" key={a.id}><strong>{name(a.clientId)}</strong><span>{a.text}</span><small>{new Date(a.createdAt).toLocaleString('fr-FR')}</small></div>)}</div></section>
 <section className="crm-data-summary"><span>{clients.length} clients</span><span>{quotes.length} devis</span><span>{missions.length} chantiers</span><span>{invoices.length} factures</span></section></>;
}
