import { useMemo, useState } from 'react';
import { CalendarClock, Plus, Trash2 } from 'lucide-react';
import { useAppData } from '../context/AppDataContext';
import { money } from '../lib/documents';

export function ContractsPage(){const {clients,maintenanceContracts,addMaintenanceContract,toggleMaintenanceContract,deleteMaintenanceContract}=useAppData();const [open,setOpen]=useState(false);const [clientId,setClientId]=useState('');const [title,setTitle]=useState('Entretien annuel');const [frequency,setFrequency]=useState<'monthly'|'quarterly'|'yearly'>('yearly');const [amount,setAmount]=useState(0);const [next,setNext]=useState(new Date().toISOString().slice(0,10));
 const annual=useMemo(()=>maintenanceContracts.filter(x=>x.active).reduce((sum,x)=>sum+x.amount_ht*(x.frequency==='monthly'?12:x.frequency==='quarterly'?4:1),0),[maintenanceContracts]);
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!title||amount<=0)return;addMaintenanceContract({client_id:clientId||null,title,frequency,amount_ht:amount,vat_rate:20,next_due_date:next,active:true,notes:''});setOpen(false)};
 return <><div className="section-heading"><div><p className="eyebrow">RÉCURRENCE</p><h1>Contrats d’entretien</h1></div><button className="primary" onClick={()=>setOpen(!open)}><Plus/>Nouveau</button></div><div className="kpi-grid"><article className="kpi-card"><span>Contrats actifs</span><strong>{maintenanceContracts.filter(x=>x.active).length}</strong></article><article className="kpi-card"><span>CA annuel récurrent HT</span><strong>{money(annual)}</strong></article><article className="kpi-card"><span>Prochaines échéances</span><strong>{maintenanceContracts.filter(x=>x.active&&new Date(x.next_due_date).getTime()<Date.now()+30*86400000).length}</strong></article></div>
 {open&&<form className="form-card form-grid" onSubmit={submit}><label>Client<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Sans client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name||`${c.first_name} ${c.last_name}`}</option>)}</select></label><label>Intitulé<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Fréquence<select value={frequency} onChange={e=>setFrequency(e.target.value as any)}><option value="monthly">Mensuelle</option><option value="quarterly">Trimestrielle</option><option value="yearly">Annuelle</option></select></label><label>Montant HT<input type="number" min="0" step="0.01" value={amount||''} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Prochaine échéance<input type="date" value={next} onChange={e=>setNext(e.target.value)}/></label><button className="primary">Créer</button></form>}
 <div className="stack">{maintenanceContracts.length===0?<article className="empty-state"><CalendarClock/><h2>Aucun contrat</h2><p>Crée des revenus récurrents d’entretien et de maintenance.</p></article>:maintenanceContracts.map(c=>{const client=clients.find(x=>x.id===c.client_id);return <article className="list-card" key={c.id}><div><strong>{c.title}</strong><span>{client?.company_name||[client?.first_name,client?.last_name].filter(Boolean).join(' ')||'Sans client'}</span><small>{money(c.amount_ht)} HT · {c.frequency==='monthly'?'mensuel':c.frequency==='quarterly'?'trimestriel':'annuel'} · échéance {new Date(c.next_due_date).toLocaleDateString('fr-FR')}</small></div><div className="row-actions"><button className={c.active?'success small':'secondary small'} onClick={()=>toggleMaintenanceContract(c.id)}>{c.active?'Actif':'Suspendu'}</button><button className="icon-button danger" onClick={()=>deleteMaintenanceContract(c.id)}><Trash2/></button></div></article>})}</div></>}
