import { useMemo, useState } from 'react';
import { CheckCircle2, Plus, Receipt, Trash2 } from 'lucide-react';
import { useAppData } from '../context/AppDataContext';
import { money } from '../lib/documents';
import type { ExpenseCategory } from '../types/domain';

const labels:Record<ExpenseCategory,string>={materials:'Matériaux',fuel:'Carburant',tools:'Outillage',subcontracting:'Sous-traitance',insurance:'Assurance',other:'Autre'};
export function ExpensesPage(){
 const {businessExpenses,missions,addBusinessExpense,toggleBusinessExpensePaid,deleteBusinessExpense}=useAppData();
 const [open,setOpen]=useState(false); const [label,setLabel]=useState(''); const [supplier,setSupplier]=useState(''); const [category,setCategory]=useState<ExpenseCategory>('materials'); const [amount,setAmount]=useState(0); const [vat,setVat]=useState(20); const [missionId,setMissionId]=useState('');
 const totals=useMemo(()=>businessExpenses.reduce((a,e)=>({ht:a.ht+e.amount_ht,tva:a.tva+e.amount_ht*e.vat_rate/100,unpaid:a.unpaid+(e.paid?0:e.amount_ht*(1+e.vat_rate/100))}),{ht:0,tva:0,unpaid:0}),[businessExpenses]);
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!label.trim()||amount<=0)return;addBusinessExpense({label:label.trim(),supplier:supplier.trim(),category,amount_ht:amount,vat_rate:vat,expense_date:new Date().toISOString().slice(0,10),mission_id:missionId||null,paid:false});setLabel('');setSupplier('');setAmount(0);setOpen(false)};
 return <><div className="section-heading"><div><p className="eyebrow">GESTION</p><h1>Dépenses</h1></div><button className="primary" onClick={()=>setOpen(!open)}><Plus/>Ajouter</button></div>
 <div className="kpi-grid"><article className="kpi-card"><span>Total HT</span><strong>{money(totals.ht)}</strong></article><article className="kpi-card"><span>TVA récupérable</span><strong>{money(totals.tva)}</strong></article><article className="kpi-card"><span>À payer TTC</span><strong>{money(totals.unpaid)}</strong></article></div>
 {open&&<form className="form-card form-grid" onSubmit={submit}><label>Libellé<input value={label} onChange={e=>setLabel(e.target.value)} required/></label><label>Fournisseur<input value={supplier} onChange={e=>setSupplier(e.target.value)}/></label><label>Catégorie<select value={category} onChange={e=>setCategory(e.target.value as ExpenseCategory)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Montant HT<input type="number" min="0" step="0.01" value={amount||''} onChange={e=>setAmount(Number(e.target.value))}/></label><label>TVA %<input type="number" min="0" step="0.1" value={vat} onChange={e=>setVat(Number(e.target.value))}/></label><label>Chantier<select value={missionId} onChange={e=>setMissionId(e.target.value)}><option value="">Aucun</option>{missions.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><button className="primary" type="submit">Enregistrer</button></form>}
 <div className="stack">{businessExpenses.length===0?<article className="empty-state"><Receipt/><h2>Aucune dépense</h2><p>Ajoute tes achats, carburants, outils et sous-traitants.</p></article>:businessExpenses.map(e=>{const ttc=e.amount_ht*(1+e.vat_rate/100);return <article className="list-card" key={e.id}><div><strong>{e.label}</strong><span>{e.supplier||labels[e.category]} · {new Date(e.expense_date).toLocaleDateString('fr-FR')}</span><small>{money(e.amount_ht)} HT · {money(ttc)} TTC {e.mission_id?'· chantier lié':''}</small></div><div className="row-actions"><button className={e.paid?'success small':'secondary small'} onClick={()=>toggleBusinessExpensePaid(e.id)}><CheckCircle2/>{e.paid?'Payée':'À payer'}</button><button className="icon-button danger" onClick={()=>deleteBusinessExpense(e.id)}><Trash2/></button></div></article>})}</div></>;
}
