import { useMemo, useState } from 'react';
import { AlertTriangle, Boxes, Minus, Plus, Trash2, ScanLine } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAppData } from '../context/AppDataContext';

export function InventoryPage(){
 const {inventory,addInventoryItem,adjustInventory,deleteInventoryItem}=useAppData();
 const [name,setName]=useState(''); const [sku,setSku]=useState(''); const [quantity,setQuantity]=useState(0); const [minimum,setMinimum]=useState(0); const [unit,setUnit]=useState('pièce'); const [location,setLocation]=useState('Atelier');
 const alerts=useMemo(()=>inventory.filter(i=>i.quantity<=i.minimum_quantity),[inventory]);
 function submit(e:React.FormEvent){e.preventDefault();if(!name.trim())return;addInventoryItem({name:name.trim(),sku:sku.trim(),unit,quantity,minimum_quantity:minimum,location});setName('');setSku('');setQuantity(0);setMinimum(0)}
 return <><div className="page-title"><div><p className="eyebrow">GESTION</p><h1>Stock</h1></div><div className="inventory-header-actions"><Link className="ghost" to="/stock-scanner"><ScanLine/>Scanner</Link><div className="stock-summary"><strong>{inventory.length}</strong><span>articles</span></div></div></div>
 {alerts.length>0&&<div className="alert-banner"><AlertTriangle/><div><strong>{alerts.length} alerte{alerts.length>1?'s':''} de stock</strong><small>Quantité minimale atteinte</small></div></div>}
 <form className="panel stock-form" onSubmit={submit}><h2>Nouvel article</h2><div className="form-grid"><label>Nom<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex. Raccord PER 16" required/></label><label>Référence<input value={sku} onChange={e=>setSku(e.target.value)} placeholder="SKU"/></label><label>Quantité<input type="number" min="0" step="0.01" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>Seuil minimum<input type="number" min="0" step="0.01" value={minimum} onChange={e=>setMinimum(Number(e.target.value))}/></label><label>Unité<input value={unit} onChange={e=>setUnit(e.target.value)}/></label><label>Emplacement<input value={location} onChange={e=>setLocation(e.target.value)}/></label></div><button className="primary-button" type="submit"><Plus/>Ajouter au stock</button></form>
 <div className="inventory-list">{inventory.map(item=><article className={`inventory-card ${item.quantity<=item.minimum_quantity?'low-stock':''}`} key={item.id}><div className="inventory-head"><div className="inventory-icon"><Boxes/></div><div><h3>{item.name}</h3><p>{item.sku||'Sans référence'} · {item.location}</p></div><button className="icon-danger" onClick={()=>confirm('Supprimer cet article ?')&&deleteInventoryItem(item.id)} aria-label="Supprimer"><Trash2/></button></div><div className="inventory-qty"><strong>{item.quantity}</strong><span>{item.unit}</span>{item.quantity<=item.minimum_quantity&&<em>Minimum : {item.minimum_quantity}</em>}</div><div className="inventory-actions"><button onClick={()=>{const q=Number(prompt('Quantité à sortir','1'));if(q>0)adjustInventory(item.id,q,'out','Sortie manuelle')}}><Minus/>Sortie</button><button onClick={()=>{const q=Number(prompt('Quantité à ajouter','1'));if(q>0)adjustInventory(item.id,q,'in','Entrée manuelle')}}><Plus/>Entrée</button><button onClick={()=>{const q=Number(prompt('Nouvelle quantité',String(item.quantity)));if(q>=0)adjustInventory(item.id,q,'adjustment','Inventaire')}}>Inventaire</button></div>{(item.movements??[]).length>0&&<details><summary>Derniers mouvements</summary>{item.movements.slice(0,5).map(m=><p className="movement" key={m.id}><span>{new Date(m.created_at).toLocaleString('fr-FR')}</span><strong>{m.type==='in'?'+':m.type==='out'?'-':'='}{m.quantity}</strong> {m.note}</p>)}</details>}</article>)}</div></>;
}
