import { KeyRound, LockKeyhole, Server, UserPlus } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Navigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
export function LoginPage(){
 const {signedIn,loading,signIn,register,acceptInvite,localSignIn,apiUrl,setApiUrl}=useAuth();
 const [mode,setMode]=useState<'login'|'register'|'invite'>('login'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 if(loading)return <main className="login-page"><section className="login-card"><div className="login-logo">C</div><h1>Chargement…</h1></section></main>;
 if(signedIn)return <Navigate to="/" replace/>;
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');setBusy(true);const fd=new FormData(e.currentTarget);try{
  if(mode==='login')await signIn({email:String(fd.get('email')||''),password:String(fd.get('password')||'')});
  else if(mode==='register')await register({displayName:String(fd.get('displayName')||''),email:String(fd.get('email')||''),password:String(fd.get('password')||''),workspaceId:String(fd.get('workspaceId')||'default')});
  else await acceptInvite({code:String(fd.get('code')||''),displayName:String(fd.get('displayName')||''),password:String(fd.get('password')||'')});
 }catch(err){setError(err instanceof Error?err.message:'Connexion impossible.')}finally{setBusy(false)}};
 return <main className="login-page"><section className="login-card"><div className="login-logo">C</div><p className="eyebrow">COMPTE CLOSERFLOW</p><h1>{mode==='login'?'Connexion':mode==='register'?'Créer le premier compte':'Rejoindre une équipe'}</h1><p className="muted-copy">Les comptes sont protégés par le serveur CloserFlow. Démarre <code>npm run server</code> avant de te connecter.</p>
 <div className="auth-tabs auth-tabs-three"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Connexion</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Créer</button><button className={mode==='invite'?'active':''} onClick={()=>setMode('invite')}>Invitation</button></div>
 <form onSubmit={submit}>{mode!=='login'&&<label>Nom affiché<input name="displayName" required minLength={2} autoComplete="name" placeholder="Corentin"/></label>}{mode==='register'&&<label>Espace de travail<input name="workspaceId" required defaultValue="default" pattern="[A-Za-z0-9_-]+" placeholder="mon-entreprise"/></label>}{mode==='invite'&&<label>Code d’invitation<div className="input-with-icon"><KeyRound/><input name="code" required minLength={10} autoCapitalize="none" placeholder="Colle le code reçu"/></div></label>}{mode!=='invite'&&<label>Adresse e-mail<input name="email" type="email" required autoComplete="email" placeholder="vous@entreprise.fr"/></label>}<label>Mot de passe<input name="password" type="password" minLength={6} required autoComplete={mode==='login'?'current-password':'new-password'} placeholder="6 caractères minimum"/></label><label>Adresse du serveur<div className="input-with-icon"><Server/><input value={apiUrl} onChange={e=>setApiUrl(e.target.value)} required placeholder="http://127.0.0.1:8787"/></div></label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={busy}>{mode==='login'?<LockKeyhole/>:<UserPlus/>}{busy?'Patiente…':mode==='login'?'Se connecter':mode==='register'?'Créer le compte':'Rejoindre l’équipe'}</button></form>
 <div className="offline-login"><button type="button" className="secondary" onClick={()=>localSignIn('Corentin')}>Utiliser l’application hors ligne</button><p className="auth-note">Mode téléphone : aucune API n’est nécessaire. Les données restent sur cet appareil jusqu’à une sauvegarde ou une synchronisation volontaire.</p></div><p className="auth-note">Le premier compte serveur devient administrateur. Les autres membres rejoignent l’espace avec un code d’invitation valable 7 jours.</p></section></main>
}
