import { Camera, CheckCircle2, CircleDollarSign, FileText, MapPin, Mic, PackagePlus, Phone, Play, Square, Trash2, ClipboardCheck } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { SignaturePad } from '../components/SignaturePad';
import { StatusBadge } from '../components/StatusBadge';
import { useAppData } from '../context/AppDataContext';
async function compress(file:File){return new Promise<string>((resolve,reject)=>{const img=new Image();img.onload=()=>{const max=1280;const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d')!.drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.72))};img.onerror=reject;img.src=URL.createObjectURL(file)})}
export function MissionDetailPage(){
 const {id}=useParams(); const {missions,updateMissionStatus,addMissionNote,addMissionMaterial,addMissionExpense,addMissionTask,toggleMissionTask,removeMissionTask,addMissionPhoto,updateMissionPhotoCaption,removeMissionPhoto,saveMissionSignature}=useAppData(); const m=missions.find(x=>x.id===id);
 const [now,setNow]=useState(Date.now()); const [note,setNote]=useState(''); const [panel,setPanel]=useState<'material'|'expense'|'task'|'signature'|null>(null); const [photoType,setPhotoType]=useState<'before'|'after'>('before'); const photoRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{ if(m?.status!=='in_progress') return; const t=setInterval(()=>setNow(Date.now()),1000); return()=>clearInterval(t);},[m?.status]);
 const expenseTotal=useMemo(()=>m?.expenses?.reduce((s,e)=>s+e.amount,0)??0,[m?.expenses]); if(!m)return <div className="empty"><h1>Mission introuvable</h1></div>;
 const elapsed=m.started_at?Math.max(0,Math.floor((now-new Date(m.started_at).getTime())/1000)):0; const clientName=m.client?(m.client.company_name||`${m.client.first_name} ${m.client.last_name}`):'Client non renseigné';
 const saveNote=()=>{const value=note.trim();if(value){addMissionNote(m.id,value);setNote('')}}; const submitQuick=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);if(panel==='material')addMissionMaterial(m.id,String(f.get('label')),Number(f.get('quantity')||1),String(f.get('unit')||'u'));if(panel==='expense')addMissionExpense(m.id,String(f.get('label')),Number(f.get('amount')||0));if(panel==='task')addMissionTask(m.id,String(f.get('label')));setPanel(null)};
 const choosePhoto=(type:'before'|'after')=>{setPhotoType(type);photoRef.current?.click()}; const photoChanged=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;const caption=window.prompt('Légende de la photo (facultatif)')??'';addMissionPhoto(m.id,await compress(file),photoType,caption.trim());e.target.value=''};
 return <><div className="mission-hero"><div><p className="eyebrow">{clientName}</p><h1>{m.title}</h1><StatusBadge status={m.status}/></div><button className="ghost" onClick={()=>m.client?.phone&&(location.href=`tel:${m.client.phone}`)}><Phone/>Appeler</button></div>
 <div className="address-card" onClick={()=>m.address&&window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(m.address)}`,'_blank')}><MapPin/><div><strong>{m.address||'Adresse à renseigner'}</strong><small>Ouvrir l’itinéraire</small></div></div>
 <section className="timer-card"><span>Temps chantier</span><strong>{String(Math.floor(elapsed/3600)).padStart(2,'0')}:{String(Math.floor((elapsed%3600)/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}</strong>{m.status==='in_progress'?<button className="danger" onClick={()=>updateMissionStatus(m.id,'completed')}><Square/>Terminer</button>:<button className="primary" onClick={()=>updateMissionStatus(m.id,'in_progress')}><Play/>Démarrer</button>}</section>
 <input ref={photoRef} hidden type="file" accept="image/*" capture="environment" onChange={photoChanged}/><section className="action-grid"><button onClick={()=>choosePhoto('before')}><Camera/><span>Photo avant</span></button><button onClick={()=>choosePhoto('after')}><Camera/><span>Photo après</span></button><button onClick={()=>document.getElementById('mission-note')?.focus()}><Mic/><span>Note</span></button><button onClick={()=>setPanel('material')}><PackagePlus/><span>Matériel</span></button><button onClick={()=>setPanel('expense')}><CircleDollarSign/><span>Dépense</span></button><button onClick={()=>setPanel('task')}><CheckCircle2/><span>Tâche</span></button></section>
 {panel&&panel!=='signature'&&<form className="form-card quick-panel" onSubmit={submitQuick}><strong>{panel==='material'?'Ajouter du matériel':panel==='expense'?'Ajouter une dépense':'Ajouter une tâche'}</strong><label>Libellé<input name="label" required autoFocus/></label>{panel==='material'&&<div className="two-cols"><label>Quantité<input name="quantity" type="number" step="0.01" defaultValue="1"/></label><label>Unité<input name="unit" defaultValue="u"/></label></div>}{panel==='expense'&&<label>Montant TTC (€)<input name="amount" type="number" step="0.01" required/></label>}<div className="button-row"><button type="button" className="ghost" onClick={()=>setPanel(null)}>Annuler</button><button className="primary">Ajouter</button></div></form>}
 <section className="detail-card"><div className="section-inline"><div><p className="eyebrow">Photos chantier</p><strong>{(m.photos??[]).length} photo(s)</strong></div></div>{(m.photos??[]).length===0?<small>Aucune photo. Utilise « Photo avant » ou « Photo après ».</small>:<div className="photo-grid">{(m.photos??[]).map(photo=><figure key={photo.id}><img src={photo.data_url}/><figcaption><span>{photo.category==='before'?'Avant':'Après'}</span><button onClick={()=>removeMissionPhoto(m.id,photo.id)} aria-label="Supprimer"><Trash2/></button></figcaption><input className="photo-caption" value={photo.caption} onChange={e=>updateMissionPhotoCaption(m.id,photo.id,e.target.value)} placeholder="Ajouter une légende…"/></figure>)}</div>}</section>
 <section className="detail-card"><p className="eyebrow">Note chantier</p><textarea id="mission-note" className="note-input" value={note} onChange={e=>setNote(e.target.value)} placeholder="Ex. Groupe de sécurité remplacé…"/><button className="primary full" onClick={saveNote}>Enregistrer la note</button></section>
 <section className="detail-grid"><article className="detail-card"><p className="eyebrow">Matériel</p>{(m.materials??[]).length===0?<small>Aucun matériel ajouté.</small>:(m.materials??[]).map(x=><div className="data-row" key={x.id}><span>{x.label}</span><b>{x.quantity} {x.unit}</b></div>)}</article><article className="detail-card"><p className="eyebrow">Dépenses</p>{(m.expenses??[]).map(x=><div className="data-row" key={x.id}><span>{x.label}</span><b>{x.amount.toFixed(2)} €</b></div>)}<div className="data-row total"><span>Total</span><b>{expenseTotal.toFixed(2)} €</b></div></article></section>
 <section className="detail-card"><div className="section-inline"><div><p className="eyebrow">Tâches</p><strong>{(m.tasks??[]).filter(t=>t.done).length}/{(m.tasks??[]).length} terminée(s)</strong></div></div>{(m.tasks??[]).length===0?<small>Aucune tâche.</small>:(m.tasks??[]).map(t=><div className="task-row" key={t.id}><label><input type="checkbox" checked={t.done} onChange={()=>toggleMissionTask(m.id,t.id)}/><span className={t.done?'done':''}>{t.label}</span></label><button onClick={()=>removeMissionTask(m.id,t.id)} aria-label="Supprimer la tâche"><Trash2/></button></div>)}</section>
 <section className="detail-card"><div className="section-inline"><div><p className="eyebrow">Signature client</p><strong>{m.signature?`Signé par ${m.signature.signer_name}`:'Non signé'}</strong></div>{!m.signature&&<button className="ghost" onClick={()=>setPanel(panel==='signature'?null:'signature')}>Faire signer</button>}</div>{panel==='signature'&&<SignaturePad onSave={(data,name)=>{saveMissionSignature(m.id,data,name);setPanel(null)}}/>}{m.signature&&<img className="saved-signature" src={m.signature.data_url}/>}</section>
 <div className="mission-final-actions"><Link className="primary full report-link" to={`/missions/${m.id}/closeout`}><ClipboardCheck/>Clôturer le chantier</Link><Link className="ghost full report-link" to={`/missions/${m.id}/report`}><FileText/>Ouvrir le rapport d’intervention</Link></div>
 <section className="detail-card"><p className="eyebrow">Description</p><p>{m.description||'Aucune description pour le moment.'}</p></section><section className="detail-card"><p className="eyebrow">Historique</p><div className="timeline"><div><i/><span><strong>Mission créée</strong><small>{new Date(m.created_at).toLocaleString('fr-FR')}</small></span></div>{m.started_at&&<div><i/><span><strong>Chantier démarré</strong><small>{new Date(m.started_at).toLocaleString('fr-FR')}</small></span></div>}{(m.notes??[]).map(n=><div key={n.id}><i/><span><strong>Note ajoutée</strong><small>{n.text} · {new Date(n.created_at).toLocaleString('fr-FR')}</small></span></div>)}{m.finished_at&&<div><i/><span><strong>Mission terminée</strong><small>{new Date(m.finished_at).toLocaleString('fr-FR')}</small></span></div>}</div></section></>;
}