import { BellRing, CheckCircle2, Cloud, DatabaseBackup, HardDrive, KeyRound, LockKeyhole, RefreshCw, ShieldCheck, Smartphone, Trash2, UserCog, WifiOff } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useV16Platform, type V16Permission } from '../context/V16PlatformContext';
import { useAppData } from '../context/AppDataContext';
import { useState } from 'react';

const labels:Record<V16Permission,string>={
 'dashboard.read':'Voir le pilotage','clients.write':'Modifier les clients','documents.write':'Créer devis/factures','missions.write':'Modifier les chantiers','planning.write':'Modifier le planning','finance.write':'Gérer les finances','team.manage':'Gérer les membres','settings.manage':'Modifier les réglages','cloud.manage':'Gérer la synchronisation','backup.restore':'Restaurer une sauvegarde'
};
const money=(n:number)=>n.toLocaleString('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0});
const total=(lines:{quantity:number;unit_price_ht:number}[],discount=0)=>lines.reduce((s,l)=>s+l.quantity*l.unit_price_ht,0)*(1-discount/100);

export function PlatformV16Page(){
 const {user,apiUrl,token}=useAuth();const data=useAppData();const p=useV16Platform();const [remote,setRemote]=useState<'idle'|'ok'|'error'|'loading'>('idle');const [tab,setTab]=useState<'overview'|'devices'|'rights'|'backup'|'security'>('overview');
 const receivables=data.invoices.filter(i=>i.status!=='paid').reduce((s,i)=>s+Math.max(0,total(i.lines,i.discount_percent)-i.payments.reduce((a,b)=>a+b.amount,0)),0);
 const active=data.missions.filter(m=>['planned','in_progress'].includes(m.status)).length;
 const testCloud=async()=>{setRemote('loading');try{const r=await fetch(`${apiUrl}/api/health`,{headers:token&&token!=='local-device'?{Authorization:`Bearer ${token}`}:{}});setRemote(r.ok?'ok':'error')}catch{setRemote('error')}};
 const tabs=[['overview','Vue globale'],['devices','Appareils'],['rights','Droits'],['backup','Sauvegardes'],['security','Sécurité']] as const;
 return <><div className="page-title v16-title"><div><p className="eyebrow">CLOSERFLOW 16</p><h1>Cloud & sécurité</h1><p>Comptes, appareils, permissions, sauvegardes et contrôle d’exploitation.</p></div><ShieldCheck/></div>
 <section className="v16-hero"><div><Cloud/><span><small>Mode</small><strong>{user?'Compte connecté':'Local'}</strong></span></div><div><small>Rôle</small><b>{p.role}</b></div><div><small>Alertes</small><b>{p.unread}</b></div><div><small>À encaisser</small><b>{money(receivables)}</b></div></section>
 <nav className="v16-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==='overview'&&<div className="v16-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">ÉTAT PLATEFORME</p><h2>Prêt multi-appareils</h2></div><Cloud/></div><div className="v16-kpis"><article><Smartphone/><span>Appareils</span><strong>{p.devices.filter(d=>!d.revoked).length}</strong></article><article><UserCog/><span>Permissions</span><strong>{p.permissions.length}</strong></article><article><DatabaseBackup/><span>Sauvegardes</span><strong>{p.backups.length}</strong></article><article><HardDrive/><span>Chantiers actifs</span><strong>{active}</strong></article></div><button className="primary" onClick={()=>void testCloud()}><RefreshCw/>{remote==='loading'?'Test…':'Tester le serveur cloud'}</button>{remote==='ok'&&<p className="form-success">Serveur accessible.</p>}{remote==='error'&&<p className="form-error">Serveur indisponible : le mode local continue de fonctionner.</p>}</section>
 <section className="panel"><div className="section-heading"><div><p className="eyebrow">CENTRE D’ALERTES</p><h2>{p.unread} non lue(s)</h2></div><BellRing/></div><div className="v16-notices">{p.notices.slice(0,6).map(n=><article key={n.id} className={`${n.level} ${n.read?'read':''}`}><div><strong>{n.title}</strong><small>{n.detail}</small></div>{n.route?<Link to={n.route}>Ouvrir</Link>:<button onClick={()=>p.markNoticeRead(n.id)}>Lu</button>}</article>)}{!p.notices.length&&<p>Aucune alerte.</p>}</div>{p.unread>0&&<button className="ghost" onClick={p.markAllRead}>Tout marquer comme lu</button>}</section></div>}
 {tab==='devices'&&<section className="panel"><div className="section-heading"><div><p className="eyebrow">APPAREILS</p><h2>Sessions et confiance</h2></div><Smartphone/></div><div className="v16-list">{p.devices.map(d=><article key={d.id} className={d.revoked?'muted':''}><div><strong>{d.label}</strong><small>{d.platform} · vu {new Date(d.lastSeenAt).toLocaleString('fr-FR')}</small></div><span className={`v16-chip ${d.trusted?'ok':'warn'}`}>{d.revoked?'Révoqué':d.trusted?'Approuvé':'À vérifier'}</span>{!d.revoked&&<><button className="ghost" onClick={()=>p.toggleDeviceTrust(d.id)}>{d.trusted?'Retirer confiance':'Approuver'}</button><button className="icon-button" onClick={()=>p.revokeDevice(d.id)} aria-label="Révoquer"><Trash2/></button></>}</article>)}</div></section>}
 {tab==='rights'&&<section className="panel"><div className="section-heading"><div><p className="eyebrow">RBAC</p><h2>Droits du rôle {p.role}</h2></div><KeyRound/></div><div className="v16-rights">{Object.entries(labels).map(([key,label])=><article key={key}><span>{p.can(key as V16Permission)?<CheckCircle2/>:<LockKeyhole/>}</span><div><strong>{label}</strong><small>{key}</small></div><b>{p.can(key as V16Permission)?'Autorisé':'Bloqué'}</b></article>)}</div><Link className="primary inline-action" to="/accounts">Gérer les comptes</Link></section>}
 {tab==='backup'&&<section className="panel"><div className="section-heading"><div><p className="eyebrow">RÉSILIENCE</p><h2>Sauvegardes locales v16</h2></div><DatabaseBackup/></div><button className="primary" onClick={()=>p.createBackup('Point de restauration v16')}><DatabaseBackup/>Créer une sauvegarde</button><div className="v16-list">{p.backups.map(b=><article key={b.id}><div><strong>{b.label}</strong><small>{new Date(b.createdAt).toLocaleString('fr-FR')} · {(b.bytes/1024).toFixed(0)} Ko</small></div><button className="ghost" disabled={!p.can('backup.restore')} onClick={()=>{if(confirm('Restaurer cette sauvegarde ? Les données locales actuelles seront remplacées.'))p.restoreBackup(b.id)}}>Restaurer</button><button className="icon-button" onClick={()=>p.deleteBackup(b.id)}><Trash2/></button></article>)}{!p.backups.length&&<p>Aucune sauvegarde v16. Crée un premier point de restauration.</p>}</div><Link className="ghost inline-action" to="/backup-center">Centre de sauvegarde avancé</Link></section>}
 {tab==='security'&&<section className="panel"><div className="section-heading"><div><p className="eyebrow">AUDIT</p><h2>Contrôle de sécurité local</h2></div><ShieldCheck/></div><button className="primary" onClick={()=>p.runSecurityAudit()}><ShieldCheck/>Lancer l’audit</button><div className="v16-security">{p.securityEvents.slice(0,20).map(e=><article key={e.id}><ShieldCheck/><div><strong>{e.type}</strong><small>{e.detail}</small></div><time>{new Date(e.createdAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</time></article>)}{!p.securityEvents.length&&<div className="v16-empty"><WifiOff/><p>Lance le contrôle pour analyser l’appareil, les sauvegardes et les données métier.</p></div>}</div></section>}
 </>;
}
