import { useEffect, useMemo, useState } from 'react';
import { Clock3, Play, Square, Trash2, TrendingUp } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAppData } from '../context/AppDataContext';
import { money } from '../lib/documents';

const minutesBetween=(start:string,end:string|null,now:number)=>Math.max(0,Math.round(((end?new Date(end).getTime():now)-new Date(start).getTime())/60000));

export function ProfitabilityPage(){
 const {missions,timeEntries,startTimer,stopTimer,addTimeEntry,deleteTimeEntry}=useAppData();
 const [now,setNow]=useState(Date.now()); const [missionId,setMissionId]=useState(missions[0]?.id??'');
 const [hourlyCost,setHourlyCost]=useState(35); const [manualMinutes,setManualMinutes]=useState(60); const [note,setNote]=useState('');
 useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),15000);return()=>window.clearInterval(id)},[]);
 const active=timeEntries.find(entry=>!entry.ended_at);
 const rows=useMemo(()=>missions.map(mission=>{const entries=timeEntries.filter(entry=>entry.mission_id===mission.id);const minutes=entries.reduce((sum,entry)=>sum+minutesBetween(entry.started_at,entry.ended_at,now),0);const labor=entries.reduce((sum,entry)=>sum+(minutesBetween(entry.started_at,entry.ended_at,now)/60)*entry.hourly_cost,0);const expenses=(mission.expenses??[]).reduce((sum,entry)=>sum+entry.amount,0);const costs=labor+expenses;const margin=mission.price_ht-costs;return {mission,minutes,labor,expenses,costs,margin,rate:mission.price_ht>0?margin/mission.price_ht*100:0}}).sort((a,b)=>b.mission.price_ht-a.mission.price_ht),[missions,timeEntries,now]);
 const totals=rows.reduce((acc,row)=>({revenue:acc.revenue+row.mission.price_ht,costs:acc.costs+row.costs,margin:acc.margin+row.margin,minutes:acc.minutes+row.minutes}),{revenue:0,costs:0,margin:0,minutes:0});
 const selected=missions.find(m=>m.id===missionId);
 return <><div className="page-title"><div><p className="eyebrow">V6 · PILOTAGE</p><h1>Rentabilité chantier</h1><p>Mesurez le temps, les coûts et la marge réelle.</p></div></div>
 <section className="metric-grid profitability-metrics"><article><span>Chiffre d’affaires HT</span><strong>{money(totals.revenue)}</strong><small>{rows.length} chantiers</small></article><article><span>Coûts suivis</span><strong>{money(totals.costs)}</strong><small>main-d’œuvre + dépenses</small></article><article className={totals.margin<0?'metric-warning':''}><span>Marge estimée</span><strong>{money(totals.margin)}</strong><small>{totals.revenue?Math.round(totals.margin/totals.revenue*100):0}% du CA</small></article><article><span>Temps enregistré</span><strong>{Math.floor(totals.minutes/60)} h {totals.minutes%60} min</strong><small>tous chantiers</small></article></section>
 <section className="card timer-card"><div className="section-heading"><div><p className="eyebrow">TEMPS RÉEL</p><h2>Chronomètre chantier</h2></div><Clock3/></div>
 {active?<div className="active-timer"><div><strong>{missions.find(m=>m.id===active.mission_id)?.title??'Mission'}</strong><span>{Math.floor(minutesBetween(active.started_at,null,now)/60)} h {minutesBetween(active.started_at,null,now)%60} min · {money(active.hourly_cost)}/h</span></div><button className="danger-button" onClick={()=>stopTimer(active.id)}><Square/>Arrêter</button></div>:<div className="timer-form"><label>Chantier<select value={missionId} onChange={e=>setMissionId(e.target.value)}>{missions.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><label>Coût horaire (€)<input type="number" min="0" value={hourlyCost} onChange={e=>setHourlyCost(Number(e.target.value))}/></label><label>Note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Pose, déplacement…"/></label><button className="primary-button" disabled={!selected} onClick={()=>{startTimer(missionId,hourlyCost,note);setNote('')}}><Play/>Démarrer</button></div>}
 <div className="manual-time"><strong>Ajouter du temps passé</strong><input type="number" min="1" value={manualMinutes} onChange={e=>setManualMinutes(Number(e.target.value))}/><span>minutes</span><button disabled={!selected} onClick={()=>{addTimeEntry(missionId,manualMinutes,hourlyCost,note);setNote('')}}>Ajouter</button></div></section>
 <div className="section-heading"><div><p className="eyebrow">ANALYSE</p><h2>Marge par chantier</h2></div><TrendingUp/></div>
 <div className="profitability-list">{rows.map(row=><article className="profitability-row" key={row.mission.id}><div className="profitability-main"><Link to={`/missions/${row.mission.id}`}><strong>{row.mission.title}</strong></Link><span>{Math.floor(row.minutes/60)} h {row.minutes%60} min · dépenses {money(row.expenses)}</span></div><div className="profitability-numbers"><span>CA {money(row.mission.price_ht)}</span><span>Coûts {money(row.costs)}</span><strong className={row.margin<0?'negative':''}>{money(row.margin)} · {Math.round(row.rate)}%</strong></div><details><summary>Détail du temps ({timeEntries.filter(e=>e.mission_id===row.mission.id).length})</summary>{timeEntries.filter(e=>e.mission_id===row.mission.id).map(entry=><div className="time-entry" key={entry.id}><span>{new Date(entry.started_at).toLocaleDateString('fr-FR')} · {minutesBetween(entry.started_at,entry.ended_at,now)} min · {money(entry.hourly_cost)}/h {entry.note&&`· ${entry.note}`}</span><button aria-label="Supprimer" onClick={()=>deleteTimeEntry(entry.id)}><Trash2/></button></div>)}</details></article>)}</div></>;
}
