import { useMemo, useState } from 'react';
import { Download, Plus, CheckCircle2, AlertTriangle, Euro, BriefcaseBusiness, ListTodo, Trash2 } from 'lucide-react';
import { useAppData } from '../context/AppDataContext';
import { createId } from '../lib/id';

type TaskPriority='low'|'normal'|'high';
type BusinessTask={id:string;title:string;due_at:string;priority:TaskPriority;done:boolean;client_id:string|null;created_at:string};
const KEY='closerflow.businessTasks.v8';
const money=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n||0);
const totalHT=(d:{lines:{quantity:number;unit_price_ht:number}[];discount_percent:number})=>d.lines.reduce((s,l)=>s+l.quantity*l.unit_price_ht,0)*(1-(d.discount_percent||0)/100);
const totalTTC=(d:{lines:{quantity:number;unit_price_ht:number}[];discount_percent:number;vat_rate:number})=>totalHT(d)*(1+(d.vat_rate||0)/100);
function loadTasks():BusinessTask[]{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return []}}
export function ProSuitePage(){
 const {clients,missions,quotes,invoices,inventory,businessExpenses,maintenanceContracts,company}=useAppData();
 const [tasks,setTasks]=useState<BusinessTask[]>(loadTasks); const [title,setTitle]=useState(''); const [due,setDue]=useState(new Date().toISOString().slice(0,10)); const [priority,setPriority]=useState<TaskPriority>('normal'); const [clientId,setClientId]=useState('');
 const save=(rows:BusinessTask[])=>{setTasks(rows);localStorage.setItem(KEY,JSON.stringify(rows))};
 const pipeline=useMemo(()=>[
  {label:'Prospects',count:missions.filter(m=>m.status==='prospect'||m.status==='visit').length,value:missions.filter(m=>m.status==='prospect'||m.status==='visit').reduce((s,m)=>s+m.price_ht,0)},
  {label:'Devis à suivre',count:quotes.filter(q=>q.status==='sent'||q.status==='draft').length,value:quotes.filter(q=>q.status==='sent'||q.status==='draft').reduce((s,q)=>s+totalHT(q),0)},
  {label:'Acceptés / planifiés',count:missions.filter(m=>['accepted','planned','in_progress'].includes(m.status)).length,value:missions.filter(m=>['accepted','planned','in_progress'].includes(m.status)).reduce((s,m)=>s+m.price_ht,0)},
  {label:'Terminés à facturer',count:missions.filter(m=>m.status==='completed').length,value:missions.filter(m=>m.status==='completed').reduce((s,m)=>s+m.price_ht,0)},
 ],[missions,quotes]);
 const receivable=invoices.filter(i=>i.status!=='paid').reduce((s,i)=>s+Math.max(0,totalTTC(i)-(i.payments||[]).reduce((p,x)=>p+x.amount,0)),0);
 const overdue=invoices.filter(i=>i.status==='overdue').reduce((s,i)=>s+Math.max(0,totalTTC(i)-(i.payments||[]).reduce((p,x)=>p+x.amount,0)),0);
 const recurring=maintenanceContracts.filter(c=>c.active).reduce((s,c)=>s+c.amount_ht*(c.frequency==='monthly'?12:c.frequency==='quarterly'?4:1),0);
 const unpaidExpenses=businessExpenses.filter(e=>!e.paid).reduce((s,e)=>s+e.amount_ht*(1+e.vat_rate/100),0);
 const lowStock=inventory.filter(i=>i.quantity<=i.minimum_quantity);
 const dataWarnings=[!company.siret&&'SIRET entreprise manquant',!company.address&&'Adresse entreprise manquante',clients.some(c=>c.customer_type==='business'&&!c.siren)&&'Certains clients B2B n’ont pas de SIREN',invoices.some(i=>!i.due_date)&&'Certaines factures n’ont pas d’échéance'].filter(Boolean) as string[];
 const addTask=()=>{if(!title.trim())return;save([{id:createId(),title:title.trim(),due_at:due,priority,done:false,client_id:clientId||null,created_at:new Date().toISOString()},...tasks]);setTitle('')};
 const exportCsv=()=>{const rows=[['Type','Libellé','Montant','État'],...pipeline.map(x=>['Pipeline',x.label,String(x.value),String(x.count)]),['Trésorerie','À encaisser',String(receivable),''],['Trésorerie','Impayé',String(overdue),''],['Trésorerie','Dépenses à payer',String(unpaidExpenses),'']];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='closerflow-pilotage-v8.csv';a.click();URL.revokeObjectURL(a.href)};
 return <><div className="page-title"><div><p className="eyebrow">CLOSERFLOW V8</p><h1>Pilotage Pro</h1><p>Commercial, trésorerie, conformité et actions réunis.</p></div><button className="secondary-button" onClick={exportCsv}><Download size={18}/> Export CSV</button></div>
 <div className="v8-kpis"><article><Euro/><span>À encaisser</span><strong>{money(receivable)}</strong><small>dont {money(overdue)} en retard</small></article><article><BriefcaseBusiness/><span>Revenu récurrent annuel</span><strong>{money(recurring)}</strong><small>{maintenanceContracts.filter(c=>c.active).length} contrat(s) actif(s)</small></article><article><AlertTriangle/><span>Sorties à prévoir</span><strong>{money(unpaidExpenses)}</strong><small>{lowStock.length} article(s) sous seuil</small></article><article><CheckCircle2/><span>Qualité des données</span><strong>{Math.max(0,100-dataWarnings.length*20)} %</strong><small>{dataWarnings.length} correction(s) prioritaire(s)</small></article></div>
 <section className="panel"><div className="section-heading"><div><p className="eyebrow">CRM</p><h2>Pipeline commercial</h2></div></div><div className="v8-pipeline">{pipeline.map((x,i)=><article key={x.label}><span>{i+1}</span><div><strong>{x.label}</strong><small>{x.count} dossier(s)</small></div><b>{money(x.value)}</b></article>)}</div></section>
 <div className="v8-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">ACTIONS</p><h2>Liste de tâches</h2></div></div><div className="v8-task-form"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Relancer le devis Dupont"/><input type="date" value={due} onChange={e=>setDue(e.target.value)}/><select value={priority} onChange={e=>setPriority(e.target.value as TaskPriority)}><option value="low">Faible</option><option value="normal">Normale</option><option value="high">Urgente</option></select><select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Sans client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name||`${c.first_name} ${c.last_name}`}</option>)}</select><button className="primary-button" onClick={addTask}><Plus size={18}/>Ajouter</button></div><div className="v8-task-list">{tasks.length===0?<p className="empty-state">Aucune tâche.</p>:tasks.map(t=><article className={t.done?'done':''} key={t.id}><button onClick={()=>save(tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x))}><CheckCircle2/></button><div><strong>{t.title}</strong><small>{t.due_at} · {t.priority==='high'?'Urgente':t.priority==='low'?'Faible':'Normale'}{t.client_id?' · '+(clients.find(c=>c.id===t.client_id)?.company_name||clients.find(c=>c.id===t.client_id)?.last_name||'Client'):''}</small></div><button onClick={()=>save(tasks.filter(x=>x.id!==t.id))}><Trash2/></button></article>)}</div></section>
 <section className="panel"><div className="section-heading"><div><p className="eyebrow">CONTRÔLES</p><h2>Centre d’attention</h2></div></div><div className="v8-alert-list">{dataWarnings.map(x=><article key={x}><AlertTriangle/><span>{x}</span></article>)}{lowStock.slice(0,5).map(x=><article key={x.id}><AlertTriangle/><span>Stock faible : {x.name} ({x.quantity} {x.unit})</span></article>)}{overdue>0&&<article><AlertTriangle/><span>{money(overdue)} de factures en retard</span></article>}{dataWarnings.length===0&&lowStock.length===0&&overdue===0&&<article className="ok"><CheckCircle2/><span>Aucune alerte critique détectée.</span></article>}</div></section></div>
 </>;
}
