import { useState } from 'react';
import { ClipboardCheck, Plus, Trash2 } from 'lucide-react';
import { useAppData } from '../context/AppDataContext';
import { createId } from '../lib/id';
type Reservation={id:string;mission_id:string;label:string;severity:'minor'|'major'|'blocking';status:'open'|'resolved';created_at:string};const KEY='closerflow.reservations.v7';
const load=():Reservation[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
export function ReservationsPage(){const {missions}=useAppData();const [rows,setRows]=useState<Reservation[]>(load);const [form,setForm]=useState({mission_id:missions[0]?.id||'',label:'',severity:'minor' as Reservation['severity']});const save=(x:Reservation[])=>{setRows(x);localStorage.setItem(KEY,JSON.stringify(x))};
 return <><div className="page-title"><div><p className="eyebrow">V7 · CHANTIER</p><h1>Réserves & levées</h1></div><ClipboardCheck/></div><div className="stats-grid"><div className="stat-card"><small>Ouvertes</small><strong>{rows.filter(x=>x.status==='open').length}</strong></div><div className="stat-card"><small>Bloquantes</small><strong>{rows.filter(x=>x.status==='open'&&x.severity==='blocking').length}</strong></div></div>
 <section className="panel"><h2>Nouvelle réserve</h2><div className="form-grid"><label>Chantier<select value={form.mission_id} onChange={e=>setForm({...form,mission_id:e.target.value})}>{missions.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><label>Description<input value={form.label} onChange={e=>setForm({...form,label:e.target.value})}/></label><label>Gravité<select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value as Reservation['severity']})}><option value="minor">Mineure</option><option value="major">Majeure</option><option value="blocking">Bloquante</option></select></label></div><button className="primary-button" onClick={()=>{if(!form.label||!form.mission_id)return;save([{...form,id:createId(),status:'open',created_at:new Date().toISOString()},...rows]);setForm({...form,label:''})}}><Plus/>Ajouter</button></section>
 <section className="panel"><div className="list-stack">{rows.map(r=>{const m=missions.find(x=>x.id===r.mission_id);return <article className="list-card" key={r.id}><div><strong>{r.label}</strong><small>{m?.title||'Chantier supprimé'} · {r.severity}</small></div><button className="secondary-button" onClick={()=>save(rows.map(x=>x.id===r.id?{...x,status:x.status==='open'?'resolved':'open'}:x))}>{r.status==='open'?'Lever':'Rouvrir'}</button><button className="icon-button danger" onClick={()=>save(rows.filter(x=>x.id!==r.id))}><Trash2/></button></article>})}</div></section></>}
