import { useMemo, useState } from 'react';
import { ArrowRight, BellRing, BrainCircuit, CheckCircle2, CircleDollarSign, Clock3, Flame, Mail, MessageSquareText, Phone, RefreshCw, Send, Sparkles, Target, TrendingUp, UserRoundCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAppData } from '../context/AppDataContext';
import { money, totals } from '../lib/documents';

type LeadStage='new'|'contacted'|'qualified'|'proposal'|'won'|'lost';
type LeadAction={id:string;clientId:string;label:string;kind:'call'|'email'|'message'|'task';dueAt:string;done:boolean;createdAt:string};
type LeadOverride={clientId:string;stage:LeadStage;note:string;updatedAt:string};
const ACTIONS_KEY='closerflow.v18.sales.actions';
const OVERRIDES_KEY='closerflow.v18.sales.overrides';
function read<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}}
function write<T>(key:string,value:T){localStorage.setItem(key,JSON.stringify(value))}
function uid(){return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
function daysSince(value:string|null|undefined){if(!value)return 999;return Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000))}
export function SalesAutopilotV18Page(){
 const {clients,quotes,invoices,missions,portalMessages,portalEvents,appointmentRequests,addPortalMessage}=useAppData();
 const [actions,setActions]=useState<LeadAction[]>(()=>read(ACTIONS_KEY,[]));
 const [overrides,setOverrides]=useState<LeadOverride[]>(()=>read(OVERRIDES_KEY,[]));
 const [selected,setSelected]=useState(clients[0]?.id??'');
 const [quickMessage,setQuickMessage]=useState('');
 const saveActions=(rows:LeadAction[])=>{setActions(rows);write(ACTIONS_KEY,rows)};
 const saveOverrides=(rows:LeadOverride[])=>{setOverrides(rows);write(OVERRIDES_KEY,rows)};
 const clientName=(id:string)=>{const c=clients.find(x=>x.id===id);return c?.company_name||`${c?.first_name??''} ${c?.last_name??''}`.trim()||'Client'};
 const leads=useMemo(()=>clients.map(client=>{
   const cq=quotes.filter(q=>q.client_id===client.id);const ci=invoices.filter(i=>i.client_id===client.id);const cm=missions.filter(m=>m.client_id===client.id);
   const ce=portalEvents.filter(e=>e.client_id===client.id);const msgs=portalMessages.filter(m=>m.client_id===client.id);const appts=appointmentRequests.filter(a=>a.client_id===client.id);
   const accepted=cq.filter(q=>q.status==='accepted');const openQuotes=cq.filter(q=>q.status==='sent'||q.status==='draft');
   const quoteValue=openQuotes.reduce((s,q)=>s+totals(q.lines,q.discount_percent,q.vat_rate).ttc,0);
   const wonValue=accepted.reduce((s,q)=>s+totals(q.lines,q.discount_percent,q.vat_rate).ttc,0);
   const unpaid=ci.filter(i=>i.status!=='paid').reduce((s,i)=>s+totals(i.lines,i.discount_percent,i.vat_rate).ttc-(i.payments??[]).reduce((p,x)=>p+x.amount,0),0);
   const lastDates=[client.created_at,...cq.map(x=>x.created_at),...ci.map(x=>x.created_at),...cm.map(x=>x.created_at),...ce.map(x=>x.created_at),...msgs.map(x=>x.created_at)].filter(Boolean).sort();
   const inactivity=daysSince(lastDates.at(-1));const engagement=ce.length+msgs.length*2+appts.length*3;
   let score=20+Math.min(25,openQuotes.length*12)+Math.min(20,engagement*3)+Math.min(15,cm.length*4)+Math.min(10,accepted.length*10);
   if(inactivity<=3)score+=10;else if(inactivity>30)score-=15;if(unpaid>0)score-=8;score=Math.max(0,Math.min(100,score));
   const autoStage:LeadStage=accepted.length?'won':openQuotes.length?'proposal':cm.some(m=>['planned','in_progress','completed'].includes(m.status))?'qualified':engagement?'contacted':'new';
   const override=overrides.find(o=>o.clientId===client.id);const stage=override?.stage??autoStage;
   const priority=score>=75?'hot':score>=50?'warm':'cold';
   const recommendation=stage==='proposal'?'Relancer le devis et traiter les objections':stage==='contacted'?'Qualifier le besoin et proposer un rendez-vous':stage==='new'?'Premier contact commercial':stage==='won'&&unpaid>0?'Sécuriser l’encaissement':'Entretenir la relation client';
   return {client,score,stage,priority,quoteValue,wonValue,unpaid,inactivity,engagement,recommendation,openQuotes,override};
 }).sort((a,b)=>b.score-a.score),[clients,quotes,invoices,missions,portalMessages,portalEvents,appointmentRequests,overrides]);
 const pipeline=leads.filter(l=>!['won','lost'].includes(l.stage));const pipelineValue=pipeline.reduce((s,l)=>s+l.quoteValue,0);const hot=leads.filter(l=>l.priority==='hot'&&!['won','lost'].includes(l.stage));const due=actions.filter(a=>!a.done&&new Date(a.dueAt).getTime()<=Date.now()+3*86400000).sort((a,b)=>a.dueAt.localeCompare(b.dueAt));
 const current=leads.find(l=>l.client.id===selected);
 function createAction(clientId:string,label:string,kind:LeadAction['kind']='task',days=0){const d=new Date();d.setDate(d.getDate()+days);saveActions([{id:uid(),clientId,label,kind,dueAt:d.toISOString().slice(0,10),done:false,createdAt:new Date().toISOString()},...actions])}
 function updateStage(clientId:string,stage:LeadStage){const existing=overrides.find(o=>o.clientId===clientId);const row={clientId,stage,note:existing?.note??'',updatedAt:new Date().toISOString()};saveOverrides([row,...overrides.filter(o=>o.clientId!==clientId)])}
 function automate(){const newActions:LeadAction[]=[];for(const l of leads){if(['won','lost'].includes(l.stage))continue;if(actions.some(a=>a.clientId===l.client.id&&!a.done))continue;if(l.stage==='proposal')newActions.push({id:uid(),clientId:l.client.id,label:'Relancer le devis',kind:'call',dueAt:new Date().toISOString().slice(0,10),done:false,createdAt:new Date().toISOString()});else if(l.priority==='hot')newActions.push({id:uid(),clientId:l.client.id,label:'Contacter ce prospect chaud',kind:'call',dueAt:new Date().toISOString().slice(0,10),done:false,createdAt:new Date().toISOString()});else if(l.inactivity>14)newActions.push({id:uid(),clientId:l.client.id,label:'Réactiver la relation commerciale',kind:'message',dueAt:new Date().toISOString().slice(0,10),done:false,createdAt:new Date().toISOString()})}saveActions([...newActions,...actions])}
 return <><div className="page-title"><div><p className="eyebrow">CLOSERFLOW 18 · SALES AUTOPILOT</p><h1>Machine commerciale intelligente</h1><p>Priorise les prospects, détecte les devis à relancer et transforme les signaux clients en actions concrètes.</p></div><button className="primary" onClick={automate}><Sparkles/>Générer les relances</button></div>
 <section className="crm-kpis"><article><Target/><span>Pipeline détecté</span><strong>{money(pipelineValue)}</strong></article><article><Flame/><span>Prospects chauds</span><strong>{hot.length}</strong></article><article><BellRing/><span>Actions ≤ 3 jours</span><strong>{due.length}</strong></article><article><TrendingUp/><span>Score moyen</span><strong>{leads.length?Math.round(leads.reduce((s,l)=>s+l.score,0)/leads.length):0}/100</strong></article></section>
 <section className="v18-layout"><div className="panel"><div className="section-heading"><div><p className="eyebrow">PRIORITÉS</p><h2>Opportunités classées automatiquement</h2></div><button className="ghost" onClick={()=>location.reload()}><RefreshCw/>Recalculer</button></div><div className="stack-list">{leads.map(l=><button key={l.client.id} className={`v18-lead ${selected===l.client.id?'active':''}`} onClick={()=>setSelected(l.client.id)}><div className="v18-score"><strong>{l.score}</strong><small>/100</small></div><div><strong>{clientName(l.client.id)}</strong><small>{l.recommendation}</small></div><div className={`v18-priority ${l.priority}`}>{l.priority==='hot'?'CHAUD':l.priority==='warm'?'TIÈDE':'FROID'}</div><ArrowRight/></button>)}</div></div>
 <div className="panel">{current?<><div className="section-heading"><div><p className="eyebrow">FICHE COMMERCIALE</p><h2>{clientName(current.client.id)}</h2></div><div className="v18-score large"><strong>{current.score}</strong><small>/100</small></div></div><div className="v18-metrics"><span><small>Devis ouverts</small><strong>{money(current.quoteValue)}</strong></span><span><small>Déjà gagné</small><strong>{money(current.wonValue)}</strong></span><span><small>À encaisser</small><strong>{money(Math.max(0,current.unpaid))}</strong></span><span><small>Signaux client</small><strong>{current.engagement}</strong></span></div><label>Étape commerciale<select value={current.stage} onChange={e=>updateStage(current.client.id,e.target.value as LeadStage)}><option value="new">Nouveau</option><option value="contacted">Contacté</option><option value="qualified">Qualifié</option><option value="proposal">Proposition</option><option value="won">Gagné</option><option value="lost">Perdu</option></select></label><div className="v18-recommendation"><BrainCircuit/><div><strong>Action recommandée</strong><p>{current.recommendation}</p></div></div><div className="crm-quick-actions"><button onClick={()=>createAction(current.client.id,'Appeler le client','call')}><Phone/>Appel</button><button onClick={()=>createAction(current.client.id,'Envoyer un e-mail','email')}><Mail/>E-mail</button><button onClick={()=>createAction(current.client.id,'Relance commerciale','message')}><MessageSquareText/>Relance</button></div><div className="inline-form"><input value={quickMessage} onChange={e=>setQuickMessage(e.target.value)} placeholder="Message client rapide"/><button className="primary compact" disabled={!quickMessage.trim()} onClick={()=>{addPortalMessage(current.client.id,'company',quickMessage);setQuickMessage('');createAction(current.client.id,'Message envoyé : suivi à prévoir','task',2)}}><Send/>Envoyer</button></div><Link className="ghost" to="/client-experience-v17"><UserRoundCheck/>Ouvrir la relation client 360°</Link></>:<p className="muted">Aucun client disponible.</p>}</div></section>
 <section className="panel"><div className="section-heading"><div><p className="eyebrow">EXÉCUTION</p><h2>File de relance</h2></div></div><div className="stack-list">{actions.filter(a=>!a.done).slice(0,12).map(a=><article className="portal-row" key={a.id}><div><strong>{clientName(a.clientId)} · {a.label}</strong><small><Clock3/> {new Date(a.dueAt).toLocaleDateString('fr-FR')}</small></div><button className="primary compact" onClick={()=>saveActions(actions.map(x=>x.id===a.id?{...x,done:true}:x))}><CheckCircle2/>Fait</button></article>)}{!actions.some(a=>!a.done)&&<p className="muted">Aucune action en attente. Lance « Générer les relances » pour créer le plan commercial.</p>}</div></section></>;
}
