import { useMemo, useState } from 'react';
import { CalendarPlus, CheckCircle2, Clock3, Plus, ShieldCheck, Trash2, Wrench } from 'lucide-react';
import { useAppData } from '../context/AppDataContext';

const today=()=>new Date().toISOString().slice(0,10);
const addYears=(date:string,years:number)=>{const d=new Date(date||Date.now());d.setFullYear(d.getFullYear()+years);return d.toISOString().slice(0,10)};
const clientName=(c:any)=>c?.company_name||[c?.first_name,c?.last_name].filter(Boolean).join(' ')||'Sans client';

export function SavMaintenancePage(){
 const {clients,team,maintenanceContracts,maintenanceVisits,warrantyRecords,addMaintenanceVisit,updateMaintenanceVisitStatus,deleteMaintenanceVisit,generateDueMaintenanceVisits,addWarrantyRecord,toggleWarrantyRecord,deleteWarrantyRecord}=useAppData();
 const [tab,setTab]=useState<'visits'|'warranties'>('visits');
 const [visitOpen,setVisitOpen]=useState(false); const [warrantyOpen,setWarrantyOpen]=useState(false);
 const [clientId,setClientId]=useState(''); const [contractId,setContractId]=useState(''); const [visitTitle,setVisitTitle]=useState('Visite d’entretien'); const [visitDate,setVisitDate]=useState(today()); const [techId,setTechId]=useState(''); const [duration,setDuration]=useState(60); const [visitNotes,setVisitNotes]=useState(''); const [parts,setParts]=useState('');
 const [equipment,setEquipment]=useState(''); const [serial,setSerial]=useState(''); const [installed,setInstalled]=useState(today()); const [warrantyEnd,setWarrantyEnd]=useState(addYears(today(),2)); const [supplier,setSupplier]=useState(''); const [warrantyNotes,setWarrantyNotes]=useState('');
 const planned=maintenanceVisits.filter(v=>v.status==='planned').length;
 const late=maintenanceVisits.filter(v=>v.status==='planned'&&new Date(v.scheduled_date).getTime()<new Date(today()).getTime()).length;
 const expiring=warrantyRecords.filter(w=>w.active&&new Date(w.warranty_end).getTime()<=Date.now()+90*86400000).length;
 const sortedVisits=useMemo(()=>[...maintenanceVisits].sort((a,b)=>a.scheduled_date.localeCompare(b.scheduled_date)),[maintenanceVisits]);
 const submitVisit=(e:React.FormEvent)=>{e.preventDefault();if(!visitTitle.trim())return;addMaintenanceVisit({contract_id:contractId||null,client_id:clientId||null,mission_id:null,title:visitTitle.trim(),scheduled_date:visitDate,status:'planned',technician_id:techId||null,duration_minutes:Math.max(15,duration),notes:visitNotes.trim(),parts:parts.split(',').map(x=>x.trim()).filter(Boolean)});setVisitOpen(false);setVisitNotes('');setParts('')};
 const submitWarranty=(e:React.FormEvent)=>{e.preventDefault();if(!equipment.trim())return;addWarrantyRecord({client_id:clientId||null,mission_id:null,equipment:equipment.trim(),serial_number:serial.trim(),installed_at:installed,warranty_end:warrantyEnd,supplier:supplier.trim(),notes:warrantyNotes.trim(),active:true});setWarrantyOpen(false);setEquipment('');setSerial('');setSupplier('');setWarrantyNotes('')};
 return <>
  <div className="section-heading"><div><p className="eyebrow">SERVICE APRÈS-VENTE</p><h1>SAV & maintenance v10.4</h1><p className="muted">Planifie les visites, suit les garanties et conserve l’historique des interventions.</p></div><div className="row-actions"><button className="secondary" onClick={()=>{const count=generateDueMaintenanceVisits(60);alert(count?`${count} visite(s) créée(s).`:'Aucune nouvelle échéance à générer.')}}><CalendarPlus/>Générer les échéances</button><button className="primary" onClick={()=>tab==='visits'?setVisitOpen(!visitOpen):setWarrantyOpen(!warrantyOpen)}><Plus/>Nouveau</button></div></div>
  <div className="kpi-grid"><article className="kpi-card"><span>Visites planifiées</span><strong>{planned}</strong></article><article className="kpi-card"><span>En retard</span><strong>{late}</strong></article><article className="kpi-card"><span>Garanties &lt; 90 jours</span><strong>{expiring}</strong></article><article className="kpi-card"><span>Contrats actifs</span><strong>{maintenanceContracts.filter(c=>c.active).length}</strong></article></div>
  <div className="tabs"><button className={tab==='visits'?'active':''} onClick={()=>setTab('visits')}><Wrench/>Interventions</button><button className={tab==='warranties'?'active':''} onClick={()=>setTab('warranties')}><ShieldCheck/>Garanties</button></div>
  {tab==='visits'&&<>
   {visitOpen&&<form className="form-card form-grid" onSubmit={submitVisit}><label>Client<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Sans client</option>{clients.map(c=><option key={c.id} value={c.id}>{clientName(c)}</option>)}</select></label><label>Contrat<select value={contractId} onChange={e=>{setContractId(e.target.value);const c=maintenanceContracts.find(x=>x.id===e.target.value);if(c){setClientId(c.client_id||'');setVisitTitle(c.title)}}}><option value="">Intervention libre</option>{maintenanceContracts.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Intitulé<input value={visitTitle} onChange={e=>setVisitTitle(e.target.value)}/></label><label>Date<input type="date" value={visitDate} onChange={e=>setVisitDate(e.target.value)}/></label><label>Technicien<select value={techId} onChange={e=>setTechId(e.target.value)}><option value="">Non affecté</option>{team.filter(t=>t.active).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Durée prévue (min)<input type="number" min="15" step="15" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label><label className="full-width">Pièces prévues, séparées par des virgules<input value={parts} onChange={e=>setParts(e.target.value)} placeholder="Joint, cartouche, filtre…"/></label><label className="full-width">Notes<textarea value={visitNotes} onChange={e=>setVisitNotes(e.target.value)}/></label><button className="primary">Planifier</button></form>}
   <div className="stack">{sortedVisits.length===0?<article className="empty-state"><Clock3/><h2>Aucune intervention SAV</h2><p>Crée une visite ou génère automatiquement celles des contrats arrivant à échéance.</p></article>:sortedVisits.map(v=>{const client=clients.find(c=>c.id===v.client_id);const tech=team.find(t=>t.id===v.technician_id);return <article className="list-card" key={v.id}><div><strong>{v.title}</strong><span>{clientName(client)} · {new Date(v.scheduled_date).toLocaleDateString('fr-FR')}</span><small>{tech?.name||'Non affecté'} · {v.duration_minutes} min{v.parts.length?` · Pièces : ${v.parts.join(', ')}`:''}</small>{v.notes&&<small>{v.notes}</small>}</div><div className="row-actions">{v.status==='planned'&&<button className="success small" onClick={()=>updateMaintenanceVisitStatus(v.id,'completed')}><CheckCircle2/>Terminer</button>}{v.status==='completed'&&<span className="status-pill success">Terminée</span>}{v.status==='cancelled'&&<span className="status-pill">Annulée</span>}<button className="icon-button danger" onClick={()=>deleteMaintenanceVisit(v.id)}><Trash2/></button></div></article>})}</div>
  </>}
  {tab==='warranties'&&<>
   {warrantyOpen&&<form className="form-card form-grid" onSubmit={submitWarranty}><label>Client<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Sans client</option>{clients.map(c=><option key={c.id} value={c.id}>{clientName(c)}</option>)}</select></label><label>Équipement<input value={equipment} onChange={e=>setEquipment(e.target.value)} placeholder="Chauffe-eau 200 L"/></label><label>N° de série<input value={serial} onChange={e=>setSerial(e.target.value)}/></label><label>Date de pose<input type="date" value={installed} onChange={e=>{setInstalled(e.target.value);setWarrantyEnd(addYears(e.target.value,2))}}/></label><label>Fin de garantie<input type="date" value={warrantyEnd} onChange={e=>setWarrantyEnd(e.target.value)}/></label><label>Fournisseur<input value={supplier} onChange={e=>setSupplier(e.target.value)}/></label><label className="full-width">Notes<textarea value={warrantyNotes} onChange={e=>setWarrantyNotes(e.target.value)}/></label><button className="primary">Enregistrer</button></form>}
   <div className="stack">{warrantyRecords.length===0?<article className="empty-state"><ShieldCheck/><h2>Aucune garantie suivie</h2><p>Enregistre les équipements posés, numéros de série et dates de fin de garantie.</p></article>:[...warrantyRecords].sort((a,b)=>a.warranty_end.localeCompare(b.warranty_end)).map(w=>{const client=clients.find(c=>c.id===w.client_id);const expired=new Date(w.warranty_end).getTime()<Date.now();return <article className="list-card" key={w.id}><div><strong>{w.equipment}</strong><span>{clientName(client)}{w.serial_number?` · Série ${w.serial_number}`:''}</span><small>Posé le {new Date(w.installed_at).toLocaleDateString('fr-FR')} · garantie jusqu’au {new Date(w.warranty_end).toLocaleDateString('fr-FR')}{w.supplier?` · ${w.supplier}`:''}</small>{w.notes&&<small>{w.notes}</small>}</div><div className="row-actions"><button className={w.active&&!expired?'success small':'secondary small'} onClick={()=>toggleWarrantyRecord(w.id)}>{expired?'Expirée':w.active?'Active':'Archivée'}</button><button className="icon-button danger" onClick={()=>deleteWarrantyRecord(w.id)}><Trash2/></button></div></article>})}</div>
  </>}
 </>
}
