import { useMemo, useRef, useState } from 'react';
import { Camera, PackageSearch, Plus, Minus } from 'lucide-react';
import { useAppData } from '../context/AppDataContext';

declare global { interface Window { BarcodeDetector?: new (options?:{formats?:string[]})=>{detect:(source:ImageBitmapSource)=>Promise<Array<{rawValue:string}>>}; } }

export function StockScannerPage(){
 const {inventory,adjustInventory}=useAppData(); const [code,setCode]=useState(''); const [message,setMessage]=useState(''); const fileRef=useRef<HTMLInputElement>(null);
 const item=useMemo(()=>inventory.find(row=>row.sku.trim().toLowerCase()===code.trim().toLowerCase())??null,[inventory,code]);
 async function scanFile(file:File){setMessage('');if(!window.BarcodeDetector){setMessage('Lecture automatique non disponible sur ce téléphone. Saisis la référence manuellement.');return}try{const detector=new window.BarcodeDetector({formats:['qr_code','ean_13','ean_8','code_128','code_39','upc_a','upc_e']});const bitmap=await createImageBitmap(file);const found=await detector.detect(bitmap);bitmap.close();if(found[0]?.rawValue){setCode(found[0].rawValue);setMessage('Code détecté.')}else setMessage('Aucun code détecté sur la photo.')}catch{setMessage('Impossible de lire ce code. Essaie avec une photo plus nette.')}}
 function move(type:'in'|'out'){if(!item)return;const quantity=Number(prompt(type==='in'?'Quantité reçue':'Quantité utilisée','1'));if(quantity>0)adjustInventory(item.id,quantity,type,`Scan ${code}`)}
 return <><div className="page-title"><div><p className="eyebrow">STOCK MOBILE</p><h1>Scanner un article</h1><p className="muted-copy">QR, EAN ou référence interne.</p></div><Camera/></div><section className="panel scanner-panel"><label>Référence ou code<input value={code} onChange={e=>setCode(e.target.value)} placeholder="Scanne ou saisis le SKU" autoCapitalize="off"/></label><input className="hidden-input" ref={fileRef} type="file" accept="image/*" capture="environment" onChange={e=>{const file=e.target.files?.[0];if(file)scanFile(file)}}/><button className="primary-button" onClick={()=>fileRef.current?.click()}><Camera/>Photographier le code</button>{message&&<p className="scanner-message">{message}</p>}</section>{code&&!item&&<div className="empty-card"><PackageSearch/><strong>Article introuvable</strong><span>Crée l’article dans Stock avec cette référence : {code}</span></div>}{item&&<article className={`scanner-result ${item.quantity<=item.minimum_quantity?'low-stock':''}`}><div><span>{item.sku}</span><h2>{item.name}</h2><p>{item.location}</p></div><div className="scanner-stock"><strong>{item.quantity}</strong><span>{item.unit}</span></div><div className="scanner-actions"><button onClick={()=>move('out')}><Minus/>Sortie</button><button onClick={()=>move('in')}><Plus/>Entrée</button></div></article>}</>;
}
