import { Download, Pencil, ShieldCheck, Trash2, UserPlus, Users, Wrench } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { useAppData } from '../context/AppDataContext';
import type { TeamMember, TeamRole } from '../types/domain';

const roleLabels:Record<TeamRole,string>={admin:'Administrateur',manager:'Chef de chantier',technician:'Technicien',employee:'Employé',subcontractor:'Sous-traitant'};
const minutesBetween=(start:string,end:string|null)=>Math.max(0,Math.round(((end?+new Date(end):Date.now())-+new Date(start))/60000));
const euro=(value:number)=>value.toLocaleString('fr-FR',{style:'currency',currency:'EUR'});

export function TeamPage(){
 const {team,missions,timeEntries,addTeamMember,updateTeamMember,deleteTeamMember,toggleTeamMember}=useAppData();
 const [open,setOpen]=useState(false); const [editing,setEditing]=useState<TeamMember|null>(null); const [query,setQuery]=useState('');
 const stats=useMemo(()=>team.map(member=>{const entries=timeEntries.filter(e=>e.user_id===member.id);const minutes=entries.reduce((sum,e)=>sum+minutesBetween(e.started_at,e.ended_at),0);const cost=entries.reduce((sum,e)=>sum+(minutesBetween(e.started_at,e.ended_at)/60)*e.hourly_cost,0);return {...member,missions:missions.filter(m=>m.assigned_user_id===member.id).length,minutes,cost,activeTimer:entries.some(e=>!e.ended_at)};}),[team,missions,timeEntries]);
 const filtered=stats.filter(m=>`${m.name} ${m.email} ${m.phone??''} ${(m.skills??[]).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 const totalMinutes=stats.reduce((s,m)=>s+m.minutes,0), totalCost=stats.reduce((s,m)=>s+m.cost,0);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const input={name:String(fd.get('name')),email:String(fd.get('email')||''),phone:String(fd.get('phone')||''),role:String(fd.get('role')) as TeamRole,active:editing?.active??true,color:String(fd.get('color')||'#2563eb'),hourly_cost:Number(fd.get('hourly_cost')||0),skills:String(fd.get('skills')||'').split(',').map(x=>x.trim()).filter(Boolean)};if(editing)updateTeamMember(editing.id,input);else addTeamMember(input);e.currentTarget.reset();setEditing(null);setOpen(false)}
 function edit(member:TeamMember){setEditing(member);setOpen(true);window.scrollTo({top:0,behavior:'smooth'})}
 function exportCsv(){const rows=[['Nom','Email','Téléphone','Rôle','Actif','Coût horaire','Compétences','Missions','Heures','Coût total'],...stats.map(m=>[m.name,m.email,m.phone??'',roleLabels[m.role],m.active?'Oui':'Non',String(m.hourly_cost??0),(m.skills??[]).join(' | '),String(m.missions),(m.minutes/60).toFixed(2),m.cost.toFixed(2)])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=`equipe-closerflow-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
 return <><div className="section-heading"><div><p className="eyebrow">ORGANISATION v9.3</p><h1>Gestion des équipes</h1><p className="muted-copy">Salariés, techniciens, responsables et sous-traitants avec coûts et activité.</p></div><div className="team-actions"><button className="secondary" onClick={exportCsv}><Download/>Exporter CSV</button><button className="primary small" onClick={()=>{setEditing(null);setOpen(v=>!v)}}><UserPlus/>Ajouter</button></div></div>
 <div className="report-kpis"><article><span>Membres actifs</span><strong>{team.filter(m=>m.active).length}</strong></article><article><span>Temps enregistré</span><strong>{Math.floor(totalMinutes/60)} h {totalMinutes%60} min</strong></article><article><span>Coût main-d’œuvre</span><strong>{euro(totalCost)}</strong></article><article><span>Chronos actifs</span><strong>{stats.filter(m=>m.activeTimer).length}</strong></article></div>
 {open&&<form className="form-card team-form team-form-v93" onSubmit={submit}><h2>{editing?'Modifier le membre':'Nouveau membre'}</h2><label>Nom<input name="name" required defaultValue={editing?.name}/></label><label>E-mail<input name="email" type="email" defaultValue={editing?.email}/></label><label>Téléphone<input name="phone" defaultValue={editing?.phone}/></label><label>Rôle<select name="role" defaultValue={editing?.role??'technician'}>{Object.entries(roleLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Coût horaire<input name="hourly_cost" type="number" min="0" step="0.5" defaultValue={editing?.hourly_cost??30}/></label><label>Couleur<input name="color" type="color" defaultValue={editing?.color??'#2563eb'}/></label><label className="wide">Compétences, séparées par des virgules<input name="skills" defaultValue={(editing?.skills??[]).join(', ')} placeholder="Plomberie, carrelage, électricité"/></label><button className="primary">{editing?'Enregistrer':'Créer le membre'}</button><button type="button" className="secondary" onClick={()=>{setOpen(false);setEditing(null)}}>Annuler</button></form>}
 <section className="panel team-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un membre ou une compétence…"/></section>
 <div className="stack">{filtered.map(member=><article className="team-card team-card-v93" key={member.id}><span className="team-color" style={{background:member.color}}/><div className="team-main"><strong>{member.name}{member.activeTimer&&<em className="live-chip">EN COURS</em>}</strong><small>{member.email||'Aucun e-mail'}{member.phone?` · ${member.phone}`:''}</small><div className="skill-list">{(member.skills??[]).map(skill=><span key={skill}><Wrench/>{skill}</span>)}</div></div><span className="role-chip">{member.role==='admin'?<ShieldCheck/>:<Users/>}{roleLabels[member.role]}</span><div className="team-metrics"><span>{member.missions} chantier(s)</span><span>{Math.floor(member.minutes/60)} h {member.minutes%60} min</span><strong>{euro(member.cost)}</strong></div><div className="team-row-actions"><button className="secondary" onClick={()=>edit(member)}><Pencil/></button><button className="secondary" onClick={()=>toggleTeamMember(member.id)}>{member.active?'Désactiver':'Réactiver'}</button><button className="icon-danger" disabled={member.role==='admin'&&team.filter(m=>m.role==='admin').length===1} onClick={()=>confirm(`Supprimer ${member.name} ?`)&&deleteTeamMember(member.id)}><Trash2/></button></div></article>)}</div></>
}
