import { useMemo, useState } from 'react';
import { AlertTriangle, BrainCircuit, Calculator, CheckCircle2, ClipboardList, FileText, Gauge, HardHat, PackageSearch, Sparkles, Trash2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAppData } from '../context/AppDataContext';
import { createId } from '../lib/id';
import type { DocumentLine } from '../types/domain';

type Rule={keys:string[];label:string;unit:string;material:number;hours:number;price:number;supplies:string[];risks:string[];tasks:string[]};
type Estimate={lines:DocumentLine[];hours:number;days:number;material:number;labour:number;travel:number;sale:number;margin:number;rate:number;risks:string[];tasks:string[];supplies:string[];missing:string[];assumptions:string[];confidence:number};

const rules:Rule[]=[
 {keys:['chauffe-eau','ballon'],label:'Remplacement de chauffe-eau',unit:'forfait',material:760,hours:7,price:1450,supplies:['Chauffe-eau','Groupe de sécurité','Raccords diélectriques','Évacuation PVC'],risks:['Vérifier le groupe de sécurité et l’évacuation','Contrôler la puissance électrique disponible'],tasks:['Couper les alimentations','Déposer l’ancien appareil','Poser et raccorder','Remettre en eau et contrôler']},
 {keys:['wc suspendu'],label:'Pose de WC suspendu avec habillage',unit:'u',material:480,hours:14,price:1150,supplies:['Bâti-support','Cuvette et plaque','Plaques hydrofuges','Raccords alimentation/évacuation'],risks:['Contrôler la portance du support','Prévoir l’accès de maintenance'],tasks:['Tracer et fixer le bâti','Raccorder eau et évacuation','Réaliser l’habillage','Tester l’étanchéité']},
 {keys:['douche','receveur'],label:'Création ou rénovation de douche',unit:'forfait',material:900,hours:24,price:2600,supplies:['Receveur','Bonde','Paroi','Kit d’étanchéité','Colonne de douche'],risks:['Traiter l’étanchéité sous carrelage','Contrôler les pentes et niveaux'],tasks:['Déposer et préparer','Reprendre les réseaux','Poser le receveur','Étancher, carreler et tester']},
 {keys:['salle de bain','sdb'],label:'Rénovation de salle de bain',unit:'forfait',material:3100,hours:82,price:7600,supplies:['Équipements sanitaires','Réseaux EF/EC','Évacuation','Étanchéité','Revêtements'],risks:['Coordonner plomberie, électricité et supports','Valider les choix clients avant commande'],tasks:['Protéger et déposer','Reprendre les réseaux','Refaire supports et étanchéité','Poser équipements et finitions']},
 {keys:['peinture'],label:'Travaux de peinture',unit:'m²',material:7,hours:.45,price:34,supplies:['Enduit','Abrasifs','Impression','Peinture de finition','Protections'],risks:['Diagnostiquer l’état des supports','Protéger les zones conservées'],tasks:['Protéger','Préparer les supports','Appliquer impression et finitions','Nettoyer et réceptionner']},
 {keys:['placo','cloison','doublage'],label:'Cloison ou doublage en plaques de plâtre',unit:'m²',material:24,hours:.8,price:72,supplies:['Rails et montants','Plaques de plâtre','Isolant','Vis','Bandes et enduit'],risks:['Repérer les réseaux existants','Vérifier les besoins acoustiques et coupe-feu'],tasks:['Tracer','Poser ossature et isolant','Visser les plaques','Réaliser les bandes']},
 {keys:['carrelage','faïence'],label:'Pose de carrelage ou faïence',unit:'m²',material:22,hours:.75,price:68,supplies:['Mortier-colle','Joints','Profilés','Primaire','Système de nivellement'],risks:['Contrôler planéité et humidité','Valider calepinage et largeur des joints'],tasks:['Préparer le support','Tracer le calepinage','Coller et poser','Jointoyer et nettoyer']},
 {keys:['fuite','dépannage'],label:'Recherche de fuite et réparation',unit:'forfait',material:45,hours:3,price:320,supplies:['Raccords de réparation','Joints','Consommables d’étanchéité'],risks:['Prévoir une réserve si la fuite est non visible','Photographier avant toute ouverture'],tasks:['Diagnostiquer','Isoler le réseau','Réparer','Remettre en service et contrôler']},
 {keys:['meuble vasque','vasque'],label:'Pose d’un meuble vasque',unit:'u',material:240,hours:5,price:650,supplies:['Meuble vasque','Siphon','Robinetterie','Fixations','Flexibles'],risks:['Vérifier la nature du mur','Contrôler les entraxes et évacuations'],tasks:['Tracer et fixer','Raccorder eau et évacuation','Régler et siliconer','Tester']}
];
const money=(v:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(v);
const firstArea=(text:string)=>{const m=text.match(/(\d+(?:[.,]\d+)?)\s*(?:m2|m²|mètres? carrés?)/i);return m?Math.max(1,Number(m[1].replace(',','.'))):null};
const countFor=(text:string,rule:Rule)=>{if(rule.unit==='m²')return firstArea(text)??1;const key=rule.keys.find(k=>text.toLowerCase().includes(k));if(!key)return 1;const before=text.slice(Math.max(0,text.toLowerCase().indexOf(key)-12),text.toLowerCase().indexOf(key));const m=before.match(/(\d+)\s*$/);return m?Math.max(1,Number(m[1])):1};

export function TradeEstimatorPage(){
 const {clients,addQuote}=useAppData(); const navigate=useNavigate();
 const [description,setDescription]=useState(''); const [clientId,setClientId]=useState(''); const [vat,setVat]=useState(10); const [hourlyCost,setHourlyCost]=useState(38); const [teamSize,setTeamSize]=useState(1); const [travel,setTravel]=useState(20); const [marginTarget,setMarginTarget]=useState(35); const [result,setResult]=useState<Estimate|null>(null);
 const title=useMemo(()=>description.trim().split(/[.!?\n]/)[0]?.slice(0,80)||'Estimation chantier',[description]);
 const recalc=(lines:DocumentLine[],base?:Estimate)=>{if(!base)return;const sale=lines.reduce((s,l)=>s+l.quantity*l.unit_price_ht,0);const cost=base.material+base.labour+base.travel;setResult({...base,lines,sale:Math.round(sale),margin:Math.round(sale-cost),rate:sale?Math.round((sale-cost)/sale*100):0})};
 function analyse(){
  const lower=description.toLowerCase(); const matched=rules.filter(r=>r.keys.some(k=>lower.includes(k))); const selected=matched.length?matched:[{keys:[],label:'Prestation à chiffrer',unit:'forfait',material:150,hours:8,price:850,supplies:['Fournitures à définir après visite'],risks:['Faire une visite technique avant engagement'],tasks:['Valider le besoin','Contrôler les accès et supports','Chiffrer les fournitures','Planifier l’intervention']}];
  const complexity=/(difficile|urgent|ancien|encastr|étage|accès difficile|amiante|occupé)/i.test(description)?1.18:1;
  const raw=selected.map(r=>{const quantity=countFor(description,r);return {rule:r,quantity}});
  const hours=raw.reduce((s,x)=>s+x.rule.hours*x.quantity,0)*complexity; const material=raw.reduce((s,x)=>s+x.rule.material*x.quantity,0)*complexity; const labour=hours*hourlyCost; const travelCost=Math.max(0,travel)*0.75; const cost=material+labour+travelCost;
  const catalogue=raw.reduce((s,x)=>s+x.quantity*x.rule.price*complexity,0); const target=cost/(1-Math.min(75,Math.max(5,marginTarget))/100); const suggested=Math.max(catalogue,target); const factor=suggested/Math.max(1,catalogue);
  const lines=raw.map(x=>({id:createId(),description:x.rule.label,quantity:x.quantity,unit:x.rule.unit,unit_price_ht:Math.round(x.rule.price*complexity*factor*100)/100}));
  const missing:string[]=[]; if(!clientId)missing.push('Client non sélectionné'); if(selected.some(r=>r.unit==='m²')&&!firstArea(description))missing.push('Surface exacte en m²'); if(!/(fourniture|fourni|matériel)/i.test(description))missing.push('Qui fournit les équipements et matériaux ?'); if(!/(dépose|existant|neuf)/i.test(description))missing.push('État de l’existant et dépose à prévoir'); if(!/(étage|rdc|rez-de-chaussée|accès)/i.test(description))missing.push('Conditions d’accès au chantier');
  const assumptions=[`${teamSize} personne${teamSize>1?'s':''}, base de 7 h/jour`,`Coût interne de main-d’œuvre : ${money(hourlyCost)}/h`,`Déplacement estimé : ${travel} km aller-retour`,complexity>1?'Majoration de complexité de 18 % appliquée':'Complexité standard retenue'];
  const margin=suggested-cost; setResult({lines,hours:Math.round(hours*10)/10,days:Math.round(hours/Math.max(1,teamSize)/7*10)/10,material:Math.round(material),labour:Math.round(labour),travel:Math.round(travelCost),sale:Math.round(suggested),margin:Math.round(margin),rate:Math.round(margin/suggested*100),risks:[...new Set(selected.flatMap(r=>r.risks))],tasks:[...new Set(selected.flatMap(r=>r.tasks))],supplies:[...new Set(selected.flatMap(r=>r.supplies))],missing,assumptions,confidence:matched.length?Math.min(96,62+matched.length*10+(missing.length===0?8:0)):38});
 }
 function createQuote(){if(!result)return;const q=addQuote({client_id:clientId||null,mission_id:null,title,status:'draft',vat_rate:vat,discount_percent:0,lines:result.lines});navigate(`/quotes/${q.id}`)}
 return <><div className="page-title"><div><p className="eyebrow">CLOSERFLOW V9.2</p><h1>Assistant IA métier</h1><p className="muted">Transforme une description en pré-devis, fournitures, temps, marge et questions à vérifier. Analyse locale, sans envoi externe.</p></div><BrainCircuit/></div>
 <section className="assistant-card"><h2>Décris le chantier librement</h2><textarea rows={7} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Exemple : rénovation d’une salle de bain de 6 m² avec douche, meuble vasque, 22 m² de faïence et peinture. 2e étage sans ascenseur, matériel fourni par l’artisan."/><div className="estimator-settings"><label>Client<select value={clientId} onChange={e=>setClientId(e.target.value)}><option value="">Sans client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.company_name||`${c.first_name} ${c.last_name}`}</option>)}</select></label><label>TVA<select value={vat} onChange={e=>setVat(Number(e.target.value))}><option value={0}>0 %</option><option value={5.5}>5,5 %</option><option value={10}>10 %</option><option value={20}>20 %</option></select></label><label>Coût horaire<input type="number" min="0" value={hourlyCost} onChange={e=>setHourlyCost(Number(e.target.value))}/></label><label>Équipe<input type="number" min="1" max="10" value={teamSize} onChange={e=>setTeamSize(Number(e.target.value))}/></label><label>Trajet A/R (km)<input type="number" min="0" value={travel} onChange={e=>setTravel(Number(e.target.value))}/></label><label>Marge cible<input type="number" min="5" max="75" value={marginTarget} onChange={e=>setMarginTarget(Number(e.target.value))}/></label></div><button className="primary" disabled={!description.trim()} onClick={analyse}><Sparkles/>Générer le pré-devis</button></section>
 {result&&<><div className="estimator-kpis"><article><Calculator/><span>Prix conseillé HT</span><strong>{money(result.sale)}</strong></article><article><HardHat/><span>Charge estimée</span><strong>{result.hours} h · {result.days} j</strong></article><article><Gauge/><span>Marge prévisionnelle</span><strong>{money(result.margin)} · {result.rate} %</strong></article><article><CheckCircle2/><span>Confiance</span><strong>{result.confidence} %</strong></article></div>
 <section className="assistant-card"><div className="estimator-heading"><div><h2>Pré-devis modifiable</h2><p className="muted">Matériaux {money(result.material)} · main-d’œuvre {money(result.labour)} · déplacement {money(result.travel)}</p></div><button className="primary" onClick={createQuote}><FileText/>Enregistrer comme devis</button></div><div className="estimator-lines">{result.lines.map((l,index)=><div key={l.id}><input value={l.description} onChange={e=>{const lines=result.lines.map((x,i)=>i===index?{...x,description:e.target.value}:x);recalc(lines,result)}}/><input type="number" min="0" step="0.1" value={l.quantity} onChange={e=>{const lines=result.lines.map((x,i)=>i===index?{...x,quantity:Number(e.target.value)}:x);recalc(lines,result)}}/><input value={l.unit} onChange={e=>{const lines=result.lines.map((x,i)=>i===index?{...x,unit:e.target.value}:x);recalc(lines,result)}}/><input type="number" min="0" step="0.01" value={l.unit_price_ht} onChange={e=>{const lines=result.lines.map((x,i)=>i===index?{...x,unit_price_ht:Number(e.target.value)}:x);recalc(lines,result)}}/><b>{money(l.quantity*l.unit_price_ht)}</b><button className="icon-button" title="Supprimer" onClick={()=>recalc(result.lines.filter((_,i)=>i!==index),result)}><Trash2/></button></div>)}</div><button className="secondary" onClick={()=>recalc([...result.lines,{id:createId(),description:'Nouvelle prestation',quantity:1,unit:'forfait',unit_price_ht:0}],result)}>Ajouter une ligne</button></section>
 {result.missing.length>0&&<section className="assistant-card warning-card"><h2><AlertTriangle/>Informations à confirmer avant envoi</h2>{result.missing.map(x=><p key={x} className="estimator-item">• {x}</p>)}</section>}
 <div className="estimator-columns"><section className="assistant-card"><h2><PackageSearch/>Fournitures suggérées</h2>{result.supplies.map(x=><p key={x} className="estimator-item">□ {x}</p>)}</section><section className="assistant-card"><h2><ClipboardList/>Hypothèses de calcul</h2>{result.assumptions.map(x=><p key={x} className="estimator-item">• {x}</p>)}</section></div>
 <div className="estimator-columns"><section className="assistant-card"><h2><AlertTriangle/>Points de vigilance</h2>{result.risks.map(x=><p key={x} className="estimator-item">• {x}</p>)}</section><section className="assistant-card"><h2><CheckCircle2/>Check-list suggérée</h2>{result.tasks.map(x=><p key={x} className="estimator-item">□ {x}</p>)}</section></div></>}
 </>;
}
