import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { demoClients, demoMissions } from '../lib/demo';
import type { Client, CompanyProfile, DocumentLine, DocumentRevision, Invoice, InvoicePayment, InvoiceStatus, InventoryItem, Mission, MissionStatus, Quote, QuoteStatus, TeamMember, TimeEntry, BusinessExpense, MaintenanceContract, EInvoiceTracking, EInvoiceStatus, SiteJournalEntry, SiteJournalCategory, ChecklistTemplate, QuoteApproval, ClientPortalMessage, PortalPaymentIntent, MaintenanceVisit, MaintenanceVisitStatus, WarrantyRecord, ClientPortalEvent, ClientAppointmentRequest } from '../types/domain';
import { createId } from '../lib/id';

export interface BackupPayload {
  version: 9; exported_at: string; company: CompanyProfile; clients: Client[];
  missions: Mission[]; quotes: Quote[]; invoices: Invoice[]; team: TeamMember[]; inventory: InventoryItem[]; timeEntries: TimeEntry[]; businessExpenses:BusinessExpense[]; maintenanceContracts:MaintenanceContract[]; eInvoiceTracking:EInvoiceTracking[]; siteJournalEntries:SiteJournalEntry[]; checklistTemplates:ChecklistTemplate[]; quoteApprovals:QuoteApproval[]; portalMessages:ClientPortalMessage[]; portalPaymentIntents:PortalPaymentIntent[]; maintenanceVisits:MaintenanceVisit[]; warrantyRecords:WarrantyRecord[]; portalEvents:ClientPortalEvent[]; appointmentRequests:ClientAppointmentRequest[];
}
interface AppData {
  company:CompanyProfile; clients:Client[]; missions:Mission[]; quotes:Quote[]; invoices:Invoice[]; team:TeamMember[]; inventory:InventoryItem[]; timeEntries:TimeEntry[]; businessExpenses:BusinessExpense[]; maintenanceContracts:MaintenanceContract[]; eInvoiceTracking:EInvoiceTracking[]; siteJournalEntries:SiteJournalEntry[]; checklistTemplates:ChecklistTemplate[]; quoteApprovals:QuoteApproval[]; portalMessages:ClientPortalMessage[]; portalPaymentIntents:PortalPaymentIntent[]; maintenanceVisits:MaintenanceVisit[]; warrantyRecords:WarrantyRecord[]; portalEvents:ClientPortalEvent[]; appointmentRequests:ClientAppointmentRequest[];
  updateCompany:(input:CompanyProfile)=>void; exportBackup:()=>BackupPayload; importBackup:(payload:BackupPayload)=>void;
  addInventoryItem:(input:Omit<InventoryItem,'id'|'created_at'|'movements'>)=>InventoryItem; updateInventoryItem:(id:string,input:Partial<Omit<InventoryItem,'id'|'created_at'|'movements'>>)=>void; adjustInventory:(id:string,quantity:number,type:'in'|'out'|'adjustment',note:string)=>void; deleteInventoryItem:(id:string)=>void;
  addTeamMember:(input:Omit<TeamMember,'id'|'created_at'>)=>TeamMember; updateTeamMember:(id:string,input:Partial<Omit<TeamMember,'id'|'created_at'>>)=>void; deleteTeamMember:(id:string)=>void; toggleTeamMember:(id:string)=>void; assignMission:(missionId:string,userId:string|null)=>void;
  addClient:(input:Omit<Client,'id'|'created_at'>)=>Client; updateClient:(id:string,input:Partial<Omit<Client,'id'|'created_at'>>)=>void; deleteClient:(id:string)=>void;
  addMission:(input:Omit<Mission,'id'|'created_at'|'client'|'notes'|'materials'|'expenses'|'tasks'>)=>Mission;
  updateMissionStatus:(id:string,status:MissionStatus)=>void; updateMissionSchedule:(id:string,start:string|null,end:string|null)=>void; addMissionNote:(id:string,note:string)=>void;
  addMissionMaterial:(id:string,label:string,quantity:number,unit:string)=>void; addMissionExpense:(id:string,label:string,amount:number)=>void;
  addMissionTask:(id:string,label:string)=>void; toggleMissionTask:(id:string,taskId:string)=>void; removeMissionTask:(id:string,taskId:string)=>void;
  addMissionPhoto:(id:string,dataUrl:string,category:'before'|'after',caption?:string)=>void; updateMissionPhotoCaption:(id:string,photoId:string,caption:string)=>void; removeMissionPhoto:(id:string,photoId:string)=>void;
  saveMissionSignature:(id:string,dataUrl:string,signerName:string)=>void; validateMissionCloseout:(id:string,validatedBy:string,customerComment:string,satisfaction:number)=>void;
  addQuote:(input:Omit<Quote,'id'|'number'|'created_at'>)=>Quote; updateQuote:(id:string,input:{client_id:string|null;title:string;vat_rate:number;discount_percent:number;lines:DocumentLine[]},reason?:string)=>void; updateQuoteStatus:(id:string,status:QuoteStatus)=>void; deleteQuote:(id:string)=>void;
  addInvoice:(input:Omit<Invoice,'id'|'number'|'created_at'|'paid_at'|'payments'>)=>Invoice; updateInvoiceDraft:(id:string,input:{client_id:string|null;title:string;vat_rate:number;discount_percent:number;lines:DocumentLine[];due_date?:string|null},reason?:string)=>void; createInvoiceCorrection:(id:string,reason:string)=>Invoice; updateInvoiceStatus:(id:string,status:InvoiceStatus)=>void; addInvoicePayment:(id:string,input:Omit<InvoicePayment,'id'>)=>void; removeInvoicePayment:(id:string,paymentId:string)=>void; deleteInvoice:(id:string)=>void;
  convertQuoteToInvoice:(quoteId:string,dueDate:string|null)=>Invoice;
  startTimer:(missionId:string,hourlyCost:number,note?:string,userId?:string|null)=>TimeEntry; stopTimer:(entryId:string)=>void; addTimeEntry:(missionId:string,minutes:number,hourlyCost:number,note?:string,userId?:string|null)=>TimeEntry; deleteTimeEntry:(entryId:string)=>void;
  addBusinessExpense:(input:Omit<BusinessExpense,'id'|'created_at'>)=>BusinessExpense; toggleBusinessExpensePaid:(id:string)=>void; deleteBusinessExpense:(id:string)=>void; addMaintenanceContract:(input:Omit<MaintenanceContract,'id'|'created_at'>)=>MaintenanceContract; toggleMaintenanceContract:(id:string)=>void; deleteMaintenanceContract:(id:string)=>void; updateEInvoiceTracking:(invoiceId:string,status:EInvoiceStatus,platform?:string,externalId?:string,message?:string)=>void; addSiteJournalEntry:(input:Omit<SiteJournalEntry,'id'|'created_at'>)=>SiteJournalEntry; toggleSiteJournalImportant:(id:string)=>void; deleteSiteJournalEntry:(id:string)=>void; addChecklistTemplate:(name:string,description:string,tasks:string[])=>ChecklistTemplate; deleteChecklistTemplate:(id:string)=>void; applyChecklistTemplate:(templateId:string,missionId:string)=>void; approveQuote:(quoteId:string,clientId:string,decision:'accepted'|'rejected',signerName:string,signatureDataUrl:string,comment?:string)=>void; addPortalMessage:(clientId:string,author:'client'|'company',text:string)=>void; markPortalMessagesRead:(clientId:string)=>void; requestPortalPayment:(invoiceId:string,clientId:string,amount:number,method:PortalPaymentIntent['method'],note?:string)=>PortalPaymentIntent; submitPortalPayment:(intentId:string,note?:string)=>void; confirmPortalPayment:(intentId:string)=>void; cancelPortalPayment:(intentId:string)=>void; addMaintenanceVisit:(input:Omit<MaintenanceVisit,'id'|'created_at'|'completed_at'>)=>MaintenanceVisit; updateMaintenanceVisitStatus:(id:string,status:MaintenanceVisitStatus)=>void; deleteMaintenanceVisit:(id:string)=>void; generateDueMaintenanceVisits:(daysAhead?:number)=>number; addWarrantyRecord:(input:Omit<WarrantyRecord,'id'|'created_at'>)=>WarrantyRecord; toggleWarrantyRecord:(id:string)=>void; deleteWarrantyRecord:(id:string)=>void; logPortalEvent:(clientId:string,type:ClientPortalEvent['type'],label:string)=>void; addAppointmentRequest:(clientId:string,missionId:string|null,preferredDate:string,preferredPeriod:ClientAppointmentRequest['preferred_period'],note?:string)=>ClientAppointmentRequest; updateAppointmentRequestStatus:(id:string,status:'accepted'|'rejected')=>void; resetDemo:()=>void;
}
const Ctx=createContext<AppData|null>(null); const uid=()=>createId();
const keys={company:'closerflow.company.v6',clients:'closerflow.clients.v6',missions:'closerflow.missions.v6',quotes:'closerflow.quotes.v6',invoices:'closerflow.invoices.v6',team:'closerflow.team.v1',inventory:'closerflow.inventory.v1',timeEntries:'closerflow.timeEntries.v6',businessExpenses:'closerflow.businessExpenses.v6',maintenanceContracts:'closerflow.maintenanceContracts.v6',eInvoiceTracking:'closerflow.eInvoiceTracking.v6',siteJournalEntries:'closerflow.siteJournalEntries.v7',checklistTemplates:'closerflow.checklistTemplates.v7_4',quoteApprovals:'closerflow.quoteApprovals.v7_5',portalMessages:'closerflow.portalMessages.v7_5',portalPaymentIntents:'closerflow.portalPaymentIntents.v10_2',maintenanceVisits:'closerflow.maintenanceVisits.v10_4',warrantyRecords:'closerflow.warrantyRecords.v10_4',portalEvents:'closerflow.portalEvents.v17',appointmentRequests:'closerflow.appointmentRequests.v17'};
function read<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}}
const normalizeMission=(m:Mission):Mission=>({...m,notes:m.notes??[],materials:m.materials??[],expenses:m.expenses??[],tasks:m.tasks??[],photos:m.photos??[],signature:m.signature??null,closeout:m.closeout??null});
const line=(description:string,quantity:number,unit:string,unit_price_ht:number):DocumentLine=>({id:uid(),description,quantity,unit,unit_price_ht});
const normalizeQuote=(q:any):Quote=>({...q,discount_percent:q.discount_percent??0,lines:q.lines??[line(q.title||'Prestation',1,'forfait',q.amount_ht??0)],updated_at:q.updated_at??null,revision:q.revision??1,revisions:q.revisions??[]});
const normalizeInvoice=(i:any):Invoice=>({...i,quote_id:i.quote_id??null,discount_percent:i.discount_percent??0,lines:i.lines??[line(i.title||'Prestation',1,'forfait',i.amount_ht??0)],payments:i.payments??[],updated_at:i.updated_at??null,revision:i.revision??1,revisions:i.revisions??[],corrected_invoice_id:i.corrected_invoice_id??null,correction_reason:i.correction_reason??null});
const snapshotRevision=(doc:{client_id:string|null;title:string;vat_rate:number;discount_percent:number;lines:DocumentLine[];revision?:number},reason:string):DocumentRevision=>({
 id:uid(),revision:doc.revision??1,saved_at:new Date().toISOString(),reason,
 client_id:doc.client_id,title:doc.title,vat_rate:doc.vat_rate,discount_percent:doc.discount_percent,
 lines:doc.lines.map(x=>({...x}))
});
const defaultCompany:CompanyProfile={name:'Mon entreprise',siret:'',vat_number:'',phone:'',email:'',address:''};
const defaultTeam:TeamMember[]=[{id:'u-admin',name:'Administrateur',email:'',role:'admin',active:true,color:'#2563eb',created_at:new Date().toISOString()}];
const seedQuotes:Quote[]=[{id:'q1',number:'DEV-2026-001',client_id:'c1',mission_id:'m1',title:'Remplacement chauffe-eau 200 L',status:'sent',vat_rate:10,discount_percent:0,lines:[line('Dépose de l’ancien chauffe-eau',1,'forfait',180),line('Fourniture et pose chauffe-eau 200 L',1,'forfait',1620)],created_at:new Date().toISOString()}];
const seedInventory:InventoryItem[]=[{id:'stock-1',name:'Raccord PER 16',sku:'PER16-R',unit:'pièce',quantity:18,minimum_quantity:10,location:'Atelier',movements:[],created_at:new Date().toISOString()},{id:'stock-2',name:'Silicone sanitaire blanc',sku:'SIL-BL',unit:'cartouche',quantity:3,minimum_quantity:5,location:'Véhicule 1',movements:[],created_at:new Date().toISOString()}];
const seedInvoices:Invoice[]=[{id:'i1',number:'FAC-2026-001',client_id:'c2',mission_id:null,quote_id:null,title:'Dépannage plomberie',status:'overdue',vat_rate:10,discount_percent:0,lines:[line('Recherche de fuite et réparation',1,'forfait',381.82)],due_date:new Date(Date.now()-8*86400000).toISOString(),created_at:new Date().toISOString(),paid_at:null,payments:[]}];

export function AppDataProvider({children}:{children:ReactNode}){
 const [company,setCompany]=useState<CompanyProfile>(()=>read(keys.company,defaultCompany));
 const [clients,setClients]=useState<Client[]>(()=>read(keys.clients,demoClients));
 const [missions,setMissions]=useState<Mission[]>(()=>read(keys.missions,demoMissions.map(normalizeMission)));
 const [quotes,setQuotes]=useState<Quote[]>(()=>read(keys.quotes,seedQuotes).map(normalizeQuote));
 const [invoices,setInvoices]=useState<Invoice[]>(()=>read(keys.invoices,seedInvoices).map(normalizeInvoice));
 const [team,setTeam]=useState<TeamMember[]>(()=>read(keys.team,defaultTeam));
 const [inventory,setInventory]=useState<InventoryItem[]>(()=>read(keys.inventory,seedInventory));
 const [timeEntries,setTimeEntries]=useState<TimeEntry[]>(()=>read(keys.timeEntries,[]));
 const [businessExpenses,setBusinessExpenses]=useState<BusinessExpense[]>(()=>read(keys.businessExpenses,[]));
 const [maintenanceContracts,setMaintenanceContracts]=useState<MaintenanceContract[]>(()=>read(keys.maintenanceContracts,[]));
 const [maintenanceVisits,setMaintenanceVisits]=useState<MaintenanceVisit[]>(()=>read(keys.maintenanceVisits,[]));
 const [warrantyRecords,setWarrantyRecords]=useState<WarrantyRecord[]>(()=>read(keys.warrantyRecords,[]));
 const [eInvoiceTracking,setEInvoiceTracking]=useState<EInvoiceTracking[]>(()=>read(keys.eInvoiceTracking,[]));
 const [siteJournalEntries,setSiteJournalEntries]=useState<SiteJournalEntry[]>(()=>read(keys.siteJournalEntries,[]));
 const [quoteApprovals,setQuoteApprovals]=useState<QuoteApproval[]>(()=>read(keys.quoteApprovals,[]));
 const [portalMessages,setPortalMessages]=useState<ClientPortalMessage[]>(()=>read(keys.portalMessages,[]));
 const [portalPaymentIntents,setPortalPaymentIntents]=useState<PortalPaymentIntent[]>(()=>read(keys.portalPaymentIntents,[]));
 const [portalEvents,setPortalEvents]=useState<ClientPortalEvent[]>(()=>read(keys.portalEvents,[]));
 const [appointmentRequests,setAppointmentRequests]=useState<ClientAppointmentRequest[]>(()=>read(keys.appointmentRequests,[]));
 const [checklistTemplates,setChecklistTemplates]=useState<ChecklistTemplate[]>(()=>read(keys.checklistTemplates,[{id:'tpl-reception',name:'Réception de chantier',description:'Contrôles avant remise au client',tasks:['Nettoyer la zone de travail','Tester le bon fonctionnement','Vérifier l’absence de fuite ou défaut','Présenter les travaux au client','Recueillir la signature client'],created_at:new Date().toISOString()}]));
 useEffect(()=>localStorage.setItem(keys.company,JSON.stringify(company)),[company]);
 useEffect(()=>localStorage.setItem(keys.clients,JSON.stringify(clients)),[clients]);
 useEffect(()=>localStorage.setItem(keys.missions,JSON.stringify(missions)),[missions]);
 useEffect(()=>localStorage.setItem(keys.quotes,JSON.stringify(quotes)),[quotes]);
 useEffect(()=>localStorage.setItem(keys.invoices,JSON.stringify(invoices)),[invoices]);
 useEffect(()=>localStorage.setItem(keys.team,JSON.stringify(team)),[team]);
 useEffect(()=>localStorage.setItem(keys.inventory,JSON.stringify(inventory)),[inventory]);
 useEffect(()=>localStorage.setItem(keys.timeEntries,JSON.stringify(timeEntries)),[timeEntries]);
 useEffect(()=>localStorage.setItem(keys.businessExpenses,JSON.stringify(businessExpenses)),[businessExpenses]);
 useEffect(()=>localStorage.setItem(keys.maintenanceContracts,JSON.stringify(maintenanceContracts)),[maintenanceContracts]);
 useEffect(()=>localStorage.setItem(keys.maintenanceVisits,JSON.stringify(maintenanceVisits)),[maintenanceVisits]);
 useEffect(()=>localStorage.setItem(keys.warrantyRecords,JSON.stringify(warrantyRecords)),[warrantyRecords]);
 useEffect(()=>localStorage.setItem(keys.eInvoiceTracking,JSON.stringify(eInvoiceTracking)),[eInvoiceTracking]);
 useEffect(()=>localStorage.setItem(keys.siteJournalEntries,JSON.stringify(siteJournalEntries)),[siteJournalEntries]);
 useEffect(()=>localStorage.setItem(keys.checklistTemplates,JSON.stringify(checklistTemplates)),[checklistTemplates]);
 useEffect(()=>localStorage.setItem(keys.quoteApprovals,JSON.stringify(quoteApprovals)),[quoteApprovals]);
 useEffect(()=>localStorage.setItem(keys.portalMessages,JSON.stringify(portalMessages)),[portalMessages]);
 useEffect(()=>localStorage.setItem(keys.portalPaymentIntents,JSON.stringify(portalPaymentIntents)),[portalPaymentIntents]);
 useEffect(()=>localStorage.setItem(keys.portalEvents,JSON.stringify(portalEvents)),[portalEvents]);
 useEffect(()=>localStorage.setItem(keys.appointmentRequests,JSON.stringify(appointmentRequests)),[appointmentRequests]);

 const value=useMemo<AppData>(()=>({company,clients,missions,quotes,invoices,team,inventory,timeEntries,businessExpenses,maintenanceContracts,eInvoiceTracking,siteJournalEntries,checklistTemplates,quoteApprovals,portalMessages,portalPaymentIntents,maintenanceVisits,warrantyRecords,portalEvents,appointmentRequests,
  updateCompany:setCompany,
  exportBackup:()=>({version:9,exported_at:new Date().toISOString(),company,clients,missions,quotes,invoices,team,inventory,timeEntries,businessExpenses,maintenanceContracts,eInvoiceTracking,siteJournalEntries,checklistTemplates,quoteApprovals,portalMessages,portalPaymentIntents,maintenanceVisits,warrantyRecords,portalEvents,appointmentRequests}),
  importBackup:(payload)=>{if(![1,2,3,4,5,6,7,8,9].includes((payload as any).version)||!Array.isArray(payload.clients)||!Array.isArray(payload.missions))throw new Error('Sauvegarde incompatible');setCompany(payload.company??defaultCompany);setClients(payload.clients);setMissions(payload.missions.map(normalizeMission));setQuotes((payload.quotes??[]).map(normalizeQuote));setInvoices((payload.invoices??[]).map(normalizeInvoice));setTeam((payload as any).team??defaultTeam);setInventory((payload as any).inventory??seedInventory);setTimeEntries((payload as any).timeEntries??[]);setBusinessExpenses((payload as any).businessExpenses??[]);setMaintenanceContracts((payload as any).maintenanceContracts??[]);setEInvoiceTracking((payload as any).eInvoiceTracking??[]);setSiteJournalEntries((payload as any).siteJournalEntries??[]);setChecklistTemplates((payload as any).checklistTemplates??[]);setQuoteApprovals((payload as any).quoteApprovals??[]);setPortalMessages((payload as any).portalMessages??[]);setPortalPaymentIntents((payload as any).portalPaymentIntents??[]);setMaintenanceVisits((payload as any).maintenanceVisits??[]);setWarrantyRecords((payload as any).warrantyRecords??[]);setPortalEvents((payload as any).portalEvents??[]);setAppointmentRequests((payload as any).appointmentRequests??[])},
  addInventoryItem:(input)=>{const row={...input,id:uid(),created_at:new Date().toISOString(),movements:[]};setInventory(items=>[row,...items]);return row},
  updateInventoryItem:(id,input)=>setInventory(items=>items.map(item=>item.id===id?{...item,...input}:item)),
  adjustInventory:(id,quantity,type,note)=>setInventory(items=>items.map(item=>{if(item.id!==id)return item;const next=type==='in'?item.quantity+quantity:type==='out'?Math.max(0,item.quantity-quantity):quantity;return {...item,quantity:next,movements:[{id:uid(),quantity,type,note,created_at:new Date().toISOString()},...(item.movements??[])]}})),
  deleteInventoryItem:(id)=>setInventory(items=>items.filter(item=>item.id!==id)),
  addTeamMember:(input)=>{const row={...input,id:uid(),created_at:new Date().toISOString()};setTeam(x=>[...x,row]);return row},
  updateTeamMember:(id,input)=>setTeam(rows=>rows.map(row=>row.id===id?{...row,...input}:row)),
  deleteTeamMember:(id)=>{setTeam(rows=>rows.filter(row=>row.id!==id));setMissions(rows=>rows.map(row=>row.assigned_user_id===id?{...row,assigned_user_id:null}:row))},
  toggleTeamMember:(id)=>setTeam(rows=>rows.map(member=>member.id===id?{...member,active:!member.active}:member)),
  assignMission:(missionId,userId)=>setMissions(rows=>rows.map(m=>m.id===missionId?{...m,assigned_user_id:userId}:m)),
  addClient:(input)=>{const row={...input,id:uid(),created_at:new Date().toISOString()};setClients(x=>[row,...x]);return row},
  updateClient:(id,input)=>setClients(rows=>rows.map(c=>c.id===id?{...c,...input}:c)),
  deleteClient:(id)=>{setClients(rows=>rows.filter(c=>c.id!==id));setMissions(rows=>rows.map(m=>m.client_id===id?{...m,client_id:null,client:null}:m))},
  addMission:(input)=>{const client=clients.find(c=>c.id===input.client_id)??null;const row={...input,id:uid(),created_at:new Date().toISOString(),client,notes:[],materials:[],expenses:[],tasks:[],photos:[],signature:null};setMissions(x=>[row,...x]);return row},
  updateMissionStatus:(id,status)=>setMissions(rows=>rows.map(m=>m.id!==id?m:{...m,status,started_at:status==='in_progress'&&!m.started_at?new Date().toISOString():m.started_at,finished_at:status==='completed'?new Date().toISOString():m.finished_at})),
  updateMissionSchedule:(id,start,end)=>setMissions(rows=>rows.map(m=>m.id===id?{...m,scheduled_start:start,scheduled_end:end,status:start&&m.status==='accepted'?'planned':m.status}:m)),
  addMissionNote:(id,note)=>setMissions(rows=>rows.map(m=>m.id===id?{...m,notes:[...(m.notes??[]),{id:uid(),text:note,created_at:new Date().toISOString()}]}:m)),
  addMissionMaterial:(id,label,quantity,unit)=>setMissions(rows=>rows.map(m=>m.id===id?{...m,materials:[...(m.materials??[]),{id:uid(),label,quantity,unit,created_at:new Date().toISOString()}]}:m)),
  addMissionExpense:(id,label,amount)=>setMissions(rows=>rows.map(m=>m.id===id?{...m,expenses:[...(m.expenses??[]),{id:uid(),label,amount,created_at:new Date().toISOString()}]}:m)),
  addMissionTask:(id,label)=>setMissions(rows=>rows.map(m=>m.id===id?{...m,tasks:[...(m.tasks??[]),{id:uid(),label,done:false,created_at:new Date().toISOString()}]}:m)),
  toggleMissionTask:(id,taskId)=>setMissions(rows=>rows.map(m=>m.id===id?{...m,tasks:(m.tasks??[]).map(t=>t.id===taskId?{...t,done:!t.done}:t)}:m)),
  removeMissionTask:(id,taskId)=>setMissions(rows=>rows.map(m=>m.id===id?{...m,tasks:(m.tasks??[]).filter(t=>t.id!==taskId)}:m)),
  addMissionPhoto:(id,dataUrl,category,caption='')=>setMissions(rows=>rows.map(m=>m.id===id?{...m,photos:[...(m.photos??[]),{id:uid(),data_url:dataUrl,category,caption,created_at:new Date().toISOString()}]}:m)),
  updateMissionPhotoCaption:(id,photoId,caption)=>setMissions(rows=>rows.map(m=>m.id===id?{...m,photos:(m.photos??[]).map(photo=>photo.id===photoId?{...photo,caption}:photo)}:m)),
  removeMissionPhoto:(id,photoId)=>setMissions(rows=>rows.map(m=>m.id===id?{...m,photos:(m.photos??[]).filter(photo=>photo.id!==photoId)}:m)),
  saveMissionSignature:(id,dataUrl,signerName)=>setMissions(rows=>rows.map(m=>m.id===id?{...m,signature:{data_url:dataUrl,signer_name:signerName,signed_at:new Date().toISOString()}}:m)),
  validateMissionCloseout:(id,validatedBy,customerComment,satisfaction)=>setMissions(rows=>rows.map(m=>m.id===id?{...m,status:'completed',finished_at:m.finished_at??new Date().toISOString(),closeout:{validated_at:new Date().toISOString(),validated_by:validatedBy,customer_comment:customerComment,satisfaction}}:m)),
  addQuote:(input)=>{const row:Quote={...input,id:uid(),number:`DEV-${new Date().getFullYear()}-${String(quotes.length+1).padStart(3,'0')}`,created_at:new Date().toISOString(),updated_at:null,revision:1,revisions:[]};setQuotes(x=>[row,...x]);return row},
  updateQuote:(id,input,reason='Modification du devis')=>setQuotes(rows=>rows.map(q=>q.id!==id?q:{...q,...input,revision:(q.revision??1)+1,updated_at:new Date().toISOString(),revisions:[...(q.revisions??[]),snapshotRevision(q,reason)]})),
  updateQuoteStatus:(id,status)=>setQuotes(rows=>rows.map(q=>q.id===id?{...q,status}:q)),
  deleteQuote:(id)=>setQuotes(rows=>rows.filter(q=>q.id!==id)),
  addInvoice:(input)=>{const row:Invoice={...input,id:uid(),number:`FAC-${new Date().getFullYear()}-${String(invoices.length+1).padStart(3,'0')}`,created_at:new Date().toISOString(),paid_at:null,payments:[],updated_at:null,revision:1,revisions:[],corrected_invoice_id:null,correction_reason:null};setInvoices(x=>[row,...x]);return row},
  updateInvoiceDraft:(id,input,reason='Modification du brouillon')=>setInvoices(rows=>rows.map(i=>{
    if(i.id!==id)return i;
    if(i.status!=='draft')return i;
    return {...i,...input,revision:(i.revision??1)+1,updated_at:new Date().toISOString(),revisions:[...(i.revisions??[]),snapshotRevision(i,reason)]};
  })),
  createInvoiceCorrection:(id,reason)=>{const source=invoices.find(i=>i.id===id);if(!source)throw new Error('Facture introuvable');const row:Invoice={id:uid(),number:`FAC-${new Date().getFullYear()}-${String(invoices.length+1).padStart(3,'0')}`,client_id:source.client_id,mission_id:source.mission_id,quote_id:source.quote_id,title:`Correction — ${source.title}`,status:'draft',vat_rate:source.vat_rate,discount_percent:source.discount_percent,lines:source.lines.map(x=>({...x,id:uid()})),due_date:source.due_date,created_at:new Date().toISOString(),paid_at:null,payments:[],updated_at:null,revision:1,revisions:[],corrected_invoice_id:source.id,correction_reason:reason||`Correction de ${source.number}`};setInvoices(x=>[row,...x]);return row},
  updateInvoiceStatus:(id,status)=>setInvoices(rows=>rows.map(i=>i.id===id?{...i,status,paid_at:status==='paid'?new Date().toISOString():status==='partial'?i.paid_at:null}:i)),
  addInvoicePayment:(id,input)=>setInvoices(rows=>rows.map(i=>{if(i.id!==id)return i;const payment={...input,id:uid()};const payments=[...(i.payments??[]),payment];const total=i.lines.reduce((sum,l)=>sum+l.quantity*l.unit_price_ht,0)*(1-(i.discount_percent??0)/100)*(1+i.vat_rate/100);const paid=payments.reduce((sum,p)=>sum+p.amount,0);return {...i,payments,status:paid>=total-0.005?'paid':'partial',paid_at:paid>=total-0.005?input.paid_at:null}})),
  removeInvoicePayment:(id,paymentId)=>setInvoices(rows=>rows.map(i=>{if(i.id!==id)return i;const payments=(i.payments??[]).filter(p=>p.id!==paymentId);const total=i.lines.reduce((sum,l)=>sum+l.quantity*l.unit_price_ht,0)*(1-(i.discount_percent??0)/100)*(1+i.vat_rate/100);const paid=payments.reduce((sum,p)=>sum+p.amount,0);const overdue=!!i.due_date&&new Date(i.due_date).getTime()<Date.now();return {...i,payments,status:paid<=0?(overdue?'overdue':'sent'):paid>=total-0.005?'paid':'partial',paid_at:paid>=total-0.005?i.paid_at:null}})),
  deleteInvoice:(id)=>setInvoices(rows=>rows.filter(i=>i.id!==id)),
  convertQuoteToInvoice:(quoteId,dueDate)=>{const quote=quotes.find(q=>q.id===quoteId);if(!quote)throw new Error('Devis introuvable');const row:Invoice={id:uid(),number:`FAC-${new Date().getFullYear()}-${String(invoices.length+1).padStart(3,'0')}`,client_id:quote.client_id,mission_id:quote.mission_id,quote_id:quote.id,title:quote.title,status:'draft',vat_rate:quote.vat_rate,discount_percent:quote.discount_percent,lines:quote.lines.map(x=>({...x,id:uid()})),due_date:dueDate,created_at:new Date().toISOString(),paid_at:null,payments:[]};setInvoices(x=>[row,...x]);setQuotes(x=>x.map(q=>q.id===quote.id?{...q,status:'accepted'}:q));return row},
  startTimer:(missionId,hourlyCost,note='',userId=null)=>{if(timeEntries.some(entry=>!entry.ended_at&&entry.user_id===userId))throw new Error('Ce collaborateur a déjà un chronomètre actif');const row:TimeEntry={id:uid(),mission_id:missionId,user_id:userId,started_at:new Date().toISOString(),ended_at:null,hourly_cost:Math.max(0,hourlyCost),note,created_at:new Date().toISOString()};setTimeEntries(rows=>[row,...rows]);return row},
  stopTimer:(entryId)=>setTimeEntries(rows=>rows.map(entry=>entry.id===entryId&&!entry.ended_at?{...entry,ended_at:new Date().toISOString()}:entry)),
  addTimeEntry:(missionId,minutes,hourlyCost,note='',userId=null)=>{const end=new Date();const start=new Date(end.getTime()-Math.max(1,minutes)*60000);const row:TimeEntry={id:uid(),mission_id:missionId,user_id:userId,started_at:start.toISOString(),ended_at:end.toISOString(),hourly_cost:Math.max(0,hourlyCost),note,created_at:new Date().toISOString()};setTimeEntries(rows=>[row,...rows]);return row},
  deleteTimeEntry:(entryId)=>setTimeEntries(rows=>rows.filter(entry=>entry.id!==entryId)),
  addBusinessExpense:(input)=>{const row:BusinessExpense={...input,id:uid(),created_at:new Date().toISOString()};setBusinessExpenses(rows=>[row,...rows]);return row},
  toggleBusinessExpensePaid:(id)=>setBusinessExpenses(rows=>rows.map(x=>x.id===id?{...x,paid:!x.paid}:x)),
  deleteBusinessExpense:(id)=>setBusinessExpenses(rows=>rows.filter(x=>x.id!==id)),
  addMaintenanceContract:(input)=>{const row:MaintenanceContract={...input,id:uid(),created_at:new Date().toISOString()};setMaintenanceContracts(rows=>[row,...rows]);return row},
  toggleMaintenanceContract:(id)=>setMaintenanceContracts(rows=>rows.map(x=>x.id===id?{...x,active:!x.active}:x)),
  deleteMaintenanceContract:(id)=>setMaintenanceContracts(rows=>rows.filter(x=>x.id!==id)),
  updateEInvoiceTracking:(invoiceId,status,platform='',externalId='',message='')=>setEInvoiceTracking(rows=>[{invoice_id:invoiceId,status,platform,external_id:externalId,updated_at:new Date().toISOString(),message},...rows.filter(x=>x.invoice_id!==invoiceId)]),
  addSiteJournalEntry:(input)=>{const row:SiteJournalEntry={...input,id:uid(),created_at:new Date().toISOString()};setSiteJournalEntries(rows=>[row,...rows]);return row},
  toggleSiteJournalImportant:(id)=>setSiteJournalEntries(rows=>rows.map(x=>x.id===id?{...x,important:!x.important}:x)),
  deleteSiteJournalEntry:(id)=>setSiteJournalEntries(rows=>rows.filter(x=>x.id!==id)),
  addChecklistTemplate:(name,description,tasks)=>{const row={id:uid(),name,description,tasks,created_at:new Date().toISOString()};setChecklistTemplates(x=>[row,...x]);return row},
  deleteChecklistTemplate:(id)=>setChecklistTemplates(x=>x.filter(t=>t.id!==id)),
  applyChecklistTemplate:(templateId,missionId)=>{const tpl=checklistTemplates.find(t=>t.id===templateId);if(!tpl)return;setMissions(rows=>rows.map(m=>m.id===missionId?{...m,tasks:[...(m.tasks??[]),...tpl.tasks.map(label=>({id:uid(),label,done:false,created_at:new Date().toISOString()}))]}:m))},
  approveQuote:(quoteId,clientId,decision,signerName,signatureDataUrl,comment='')=>{const row:QuoteApproval={quote_id:quoteId,client_id:clientId,signer_name:signerName,signature_data_url:signatureDataUrl,decision,comment,decided_at:new Date().toISOString()};setQuoteApprovals(rows=>[row,...rows.filter(x=>x.quote_id!==quoteId)]);setQuotes(rows=>rows.map(q=>q.id===quoteId?{...q,status:decision}:q));},
  addPortalMessage:(clientId,author,text)=>{const clean=text.trim();if(!clean)return;setPortalMessages(rows=>[{id:uid(),client_id:clientId,author,text:clean,created_at:new Date().toISOString(),read:author==='company'},...rows])},
  markPortalMessagesRead:(clientId)=>setPortalMessages(rows=>rows.map(m=>m.client_id===clientId&&m.author==='company'?{...m,read:true}:m)),
  requestPortalPayment:(invoiceId,clientId,amount,method,note='')=>{const row:PortalPaymentIntent={id:uid(),invoice_id:invoiceId,client_id:clientId,amount:Math.max(0,amount),method,note:note.trim(),status:'requested',created_at:new Date().toISOString(),submitted_at:null,confirmed_at:null};setPortalPaymentIntents(rows=>[row,...rows.filter(x=>x.invoice_id!==invoiceId||!['requested','submitted'].includes(x.status))]);return row},
  submitPortalPayment:(intentId,note='')=>setPortalPaymentIntents(rows=>rows.map(x=>x.id===intentId?{...x,status:'submitted',note:note.trim()||x.note,submitted_at:new Date().toISOString()}:x)),
  confirmPortalPayment:(intentId)=>{const intent=portalPaymentIntents.find(x=>x.id===intentId);if(!intent)return;setPortalPaymentIntents(rows=>rows.map(x=>x.id===intentId?{...x,status:'confirmed',confirmed_at:new Date().toISOString()}:x));const invoice=invoices.find(x=>x.id===intent.invoice_id);if(invoice){const paid=(invoice.payments??[]).reduce((sum,p)=>sum+p.amount,0);const remaining=Math.max(0,intent.amount-paid);if(remaining>0){const method=intent.method==='transfer'?'transfer':intent.method==='cash'?'cash':intent.method==='check'?'check':'card';const payment:InvoicePayment={id:uid(),amount:remaining,method,note:intent.note||'Paiement confirmé depuis le portail client',paid_at:new Date().toISOString()};setInvoices(rows=>rows.map(i=>{if(i.id!==invoice.id)return i;const payments=[...(i.payments??[]),payment];const total=i.lines.reduce((sum,l)=>sum+l.quantity*l.unit_price_ht,0)*(1-(i.discount_percent??0)/100)*(1+i.vat_rate/100);const sum=payments.reduce((acc,p)=>acc+p.amount,0);return {...i,payments,status:sum>=total-0.005?'paid':'partial',paid_at:sum>=total-0.005?payment.paid_at:null}}))}}},
  cancelPortalPayment:(intentId)=>setPortalPaymentIntents(rows=>rows.map(x=>x.id===intentId?{...x,status:'cancelled'}:x)),
  addMaintenanceVisit:(input)=>{const row:MaintenanceVisit={...input,id:uid(),created_at:new Date().toISOString(),completed_at:null};setMaintenanceVisits(rows=>[row,...rows]);return row},
  updateMaintenanceVisitStatus:(id,status)=>setMaintenanceVisits(rows=>rows.map(v=>v.id===id?{...v,status,completed_at:status==='completed'?new Date().toISOString():null}:v)),
  deleteMaintenanceVisit:(id)=>setMaintenanceVisits(rows=>rows.filter(v=>v.id!==id)),
  generateDueMaintenanceVisits:(daysAhead=60)=>{const limit=Date.now()+Math.max(1,daysAhead)*86400000;const due=maintenanceContracts.filter(c=>c.active&&new Date(c.next_due_date).getTime()<=limit);let created=0;setMaintenanceVisits(rows=>{const next=[...rows];for(const c of due){const exists=next.some(v=>v.contract_id===c.id&&v.scheduled_date===c.next_due_date&&v.status!=='cancelled');if(!exists){next.unshift({id:uid(),contract_id:c.id,client_id:c.client_id,mission_id:null,title:c.title,scheduled_date:c.next_due_date,status:'planned',technician_id:null,duration_minutes:60,notes:c.notes,parts:[],created_at:new Date().toISOString(),completed_at:null});created++}}return next});return created},
  addWarrantyRecord:(input)=>{const row:WarrantyRecord={...input,id:uid(),created_at:new Date().toISOString()};setWarrantyRecords(rows=>[row,...rows]);return row},
  toggleWarrantyRecord:(id)=>setWarrantyRecords(rows=>rows.map(w=>w.id===id?{...w,active:!w.active}:w)),
  deleteWarrantyRecord:(id)=>setWarrantyRecords(rows=>rows.filter(w=>w.id!==id)),
  logPortalEvent:(clientId,type,label)=>setPortalEvents(rows=>[{id:uid(),client_id:clientId,type,label,created_at:new Date().toISOString()},...rows].slice(0,500)),
  addAppointmentRequest:(clientId,missionId,preferredDate,preferredPeriod,note='')=>{const row:ClientAppointmentRequest={id:uid(),client_id:clientId,mission_id:missionId,preferred_date:preferredDate,preferred_period:preferredPeriod,note:note.trim(),status:'pending',created_at:new Date().toISOString(),answered_at:null};setAppointmentRequests(rows=>[row,...rows]);setPortalEvents(rows=>[{id:uid(),client_id:clientId,type:'appointment_request',label:`Demande de rendez-vous ${preferredDate}`,created_at:new Date().toISOString()},...rows]);return row},
  updateAppointmentRequestStatus:(id,status)=>setAppointmentRequests(rows=>rows.map(r=>r.id===id?{...r,status,answered_at:new Date().toISOString()}:r)),
  resetDemo:()=>{setCompany(defaultCompany);setClients(demoClients);setMissions(demoMissions.map(normalizeMission));setQuotes(seedQuotes);setInvoices(seedInvoices);setTeam(defaultTeam);setInventory(seedInventory);setTimeEntries([]);setBusinessExpenses([]);setMaintenanceContracts([]);setEInvoiceTracking([]);setSiteJournalEntries([]);setChecklistTemplates([]);setQuoteApprovals([]);setPortalMessages([]);setPortalPaymentIntents([]);setMaintenanceVisits([]);setWarrantyRecords([]);setPortalEvents([]);setAppointmentRequests([])}
 }),[company,clients,missions,quotes,invoices,team,inventory,timeEntries,businessExpenses,maintenanceContracts,eInvoiceTracking,siteJournalEntries,checklistTemplates,quoteApprovals,portalMessages,portalPaymentIntents,maintenanceVisits,warrantyRecords,portalEvents,appointmentRequests]);
 return <Ctx.Provider value={value}>{children}</Ctx.Provider>
}
export function useAppData(){const value=useContext(Ctx);if(!value)throw new Error('useAppData must be used inside AppDataProvider');return value}
