import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import type { AuditEntry, AutomationRule, Organization, PurchaseOrder, PurchaseReceipt, Supplier, Warehouse } from '../types/domain';
import { useAppData } from './AppDataContext';
import { useAuth } from './AuthContext';
import { createId } from '../lib/id';

interface V4PlatformValue {
  organizations:Organization[]; activeOrganization:Organization; activeOrganizationId:string;
  warehouses:Warehouse[]; suppliers:Supplier[]; purchaseOrders:PurchaseOrder[]; purchaseReceipts:PurchaseReceipt[]; automations:AutomationRule[]; audit:AuditEntry[];
  setActiveOrganization:(id:string)=>void; addOrganization:(input:Omit<Organization,'id'|'created_at'>)=>void;
  addWarehouse:(input:Omit<Warehouse,'id'|'organization_id'|'created_at'>)=>void; toggleWarehouse:(id:string)=>void;
  addSupplier:(input:Omit<Supplier,'id'|'organization_id'|'created_at'>)=>void;
  addPurchaseOrder:(input:Omit<PurchaseOrder,'id'|'organization_id'|'number'|'created_at'>)=>void; updatePurchaseOrderStatus:(id:string,status:PurchaseOrder['status'])=>void; receivePurchaseOrder:(id:string,quantities:Record<string,number>,note?:string)=>void;
  addAutomation:(input:Omit<AutomationRule,'id'|'organization_id'|'created_at'>)=>void; toggleAutomation:(id:string)=>void;
}
const Ctx=createContext<V4PlatformValue|null>(null); const uid=()=>createId();
const keys={orgs:'closerflow.v4.organizations',active:'closerflow.v4.activeOrganization',warehouses:'closerflow.v4.warehouses',suppliers:'closerflow.v4.suppliers',orders:'closerflow.v4.purchaseOrders',receipts:'closerflow.v7.purchaseReceipts',automations:'closerflow.v4.automations',audit:'closerflow.v4.audit'};
function read<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}}
export function V4PlatformProvider({children}:{children:ReactNode}){
 const {company,updateCompany,inventory,adjustInventory,addInventoryItem}=useAppData(); const {displayName}=useAuth();
 const seedOrg:Organization={id:'org-main',name:company.name,siret:company.siret,vat_number:company.vat_number,phone:company.phone,email:company.email,address:company.address,created_at:new Date().toISOString()};
 const [organizations,setOrganizations]=useState<Organization[]>(()=>read(keys.orgs,[seedOrg]));
 const [activeOrganizationId,setActiveOrganizationId]=useState(()=>read(keys.active,'org-main'));
 const [warehouses,setWarehouses]=useState<Warehouse[]>(()=>read(keys.warehouses,[{id:'wh-main',organization_id:'org-main',name:'Dépôt principal',type:'warehouse',address:company.address,active:true,created_at:new Date().toISOString()},{id:'wh-van',organization_id:'org-main',name:'Véhicule 1',type:'vehicle',address:'',active:true,created_at:new Date().toISOString()}]));
 const [suppliers,setSuppliers]=useState<Supplier[]>(()=>read(keys.suppliers,[]));
 const [purchaseOrders,setPurchaseOrders]=useState<PurchaseOrder[]>(()=>read(keys.orders,[]));
 const [purchaseReceipts,setPurchaseReceipts]=useState<PurchaseReceipt[]>(()=>read(keys.receipts,[]));
 const [automations,setAutomations]=useState<AutomationRule[]>(()=>read(keys.automations,[{id:'auto-overdue',organization_id:'org-main',name:'Alerte facture en retard',trigger:'invoice_overdue',action:'notify',active:true,created_at:new Date().toISOString()},{id:'auto-stock',organization_id:'org-main',name:'Préparer un réassort si stock faible',trigger:'stock_low',action:'create_purchase_order',active:false,created_at:new Date().toISOString()}]));
 const [audit,setAudit]=useState<AuditEntry[]>(()=>read(keys.audit,[]));
 const activeOrganization=organizations.find(o=>o.id===activeOrganizationId)??organizations[0];
 const log=(action:string,entity:string,detail:string,org=activeOrganizationId)=>setAudit(rows=>[{id:uid(),organization_id:org,actor:displayName||'Utilisateur',action,entity,detail,created_at:new Date().toISOString()},...rows].slice(0,500));
 useEffect(()=>localStorage.setItem(keys.orgs,JSON.stringify(organizations)),[organizations]); useEffect(()=>localStorage.setItem(keys.active,JSON.stringify(activeOrganizationId)),[activeOrganizationId]);
 useEffect(()=>localStorage.setItem(keys.warehouses,JSON.stringify(warehouses)),[warehouses]); useEffect(()=>localStorage.setItem(keys.suppliers,JSON.stringify(suppliers)),[suppliers]); useEffect(()=>localStorage.setItem(keys.orders,JSON.stringify(purchaseOrders)),[purchaseOrders]); useEffect(()=>localStorage.setItem(keys.receipts,JSON.stringify(purchaseReceipts)),[purchaseReceipts]); useEffect(()=>localStorage.setItem(keys.automations,JSON.stringify(automations)),[automations]); useEffect(()=>localStorage.setItem(keys.audit,JSON.stringify(audit)),[audit]);
 const value=useMemo<V4PlatformValue>(()=>({organizations,activeOrganization,activeOrganizationId,warehouses:warehouses.filter(x=>x.organization_id===activeOrganizationId),suppliers:suppliers.filter(x=>x.organization_id===activeOrganizationId),purchaseOrders:purchaseOrders.filter(x=>x.organization_id===activeOrganizationId),purchaseReceipts:purchaseReceipts.filter(x=>x.organization_id===activeOrganizationId),automations:automations.filter(x=>x.organization_id===activeOrganizationId),audit:audit.filter(x=>x.organization_id===activeOrganizationId),
  setActiveOrganization:(id)=>{const org=organizations.find(o=>o.id===id);if(!org)return;setActiveOrganizationId(id);updateCompany({name:org.name,siret:org.siret,vat_number:org.vat_number,phone:org.phone,email:org.email,address:org.address});log('changement','entreprise',`Espace actif : ${org.name}`,id)},
  addOrganization:(input)=>{const row={...input,id:uid(),created_at:new Date().toISOString()};setOrganizations(x=>[...x,row]);log('création','entreprise',row.name,row.id)},
  addWarehouse:(input)=>{const row={...input,id:uid(),organization_id:activeOrganizationId,created_at:new Date().toISOString()};setWarehouses(x=>[...x,row]);log('création','emplacement',row.name)},toggleWarehouse:(id)=>setWarehouses(rows=>rows.map(x=>{if(x.id!==id)return x;log('modification','emplacement',`${x.name} : ${x.active?'désactivé':'activé'}`);return {...x,active:!x.active}})),
  addSupplier:(input)=>{const row={...input,id:uid(),organization_id:activeOrganizationId,created_at:new Date().toISOString()};setSuppliers(x=>[...x,row]);log('création','fournisseur',row.name)},
  addPurchaseOrder:(input)=>{const row={...input,lines:input.lines.map(l=>({...l,received_quantity:l.received_quantity??0})),id:uid(),organization_id:activeOrganizationId,number:`BC-${new Date().getFullYear()}-${String(purchaseOrders.filter(x=>x.organization_id===activeOrganizationId).length+1).padStart(3,'0')}`,created_at:new Date().toISOString()};setPurchaseOrders(x=>[row,...x]);log('création','bon de commande',row.number)},updatePurchaseOrderStatus:(id,status)=>setPurchaseOrders(rows=>rows.map(x=>{if(x.id!==id)return x;log('modification','bon de commande',`${x.number} → ${status}`);return {...x,status}})),
  receivePurchaseOrder:(id,quantities,note='')=>{const order=purchaseOrders.find(x=>x.id===id);if(!order)throw new Error('Bon de commande introuvable');const receiptLines=[] as PurchaseReceipt['lines'];const nextLines=order.lines.map(line=>{const remaining=Math.max(0,line.quantity-(line.received_quantity??0));const qty=Math.min(remaining,Math.max(0,Number(quantities[line.id]||0)));if(qty<=0)return line;let itemId=line.inventory_item_id??null;if(itemId&&inventory.some(i=>i.id===itemId))adjustInventory(itemId,qty,'in',`Réception ${order.number}`);else{const existing=inventory.find(i=>line.sku&&i.sku.toLowerCase()===line.sku.toLowerCase());if(existing){itemId=existing.id;adjustInventory(existing.id,qty,'in',`Réception ${order.number}`)}else{const created=addInventoryItem({name:line.description,sku:line.sku||`ACH-${Date.now().toString().slice(-6)}`,unit:line.unit,quantity:qty,minimum_quantity:0,location:warehouses.find(w=>w.id===order.warehouse_id)?.name||'Dépôt'});itemId=created.id}}receiptLines.push({purchase_order_line_id:line.id,description:line.description,quantity:qty,inventory_item_id:itemId});return {...line,inventory_item_id:itemId,received_quantity:(line.received_quantity??0)+qty}});if(!receiptLines.length)throw new Error('Aucune quantité à réceptionner');const complete=nextLines.every(l=>(l.received_quantity??0)>=l.quantity);const receipt:PurchaseReceipt={id:uid(),organization_id:activeOrganizationId,purchase_order_id:id,number:`BR-${new Date().getFullYear()}-${String(purchaseReceipts.filter(x=>x.organization_id===activeOrganizationId).length+1).padStart(3,'0')}`,received_at:new Date().toISOString(),note,lines:receiptLines,created_at:new Date().toISOString()};setPurchaseReceipts(rows=>[receipt,...rows]);setPurchaseOrders(rows=>rows.map(x=>x.id===id?{...x,lines:nextLines,status:complete?'received':'partial'}:x));log('réception','bon de commande',`${order.number} · ${receipt.number}`)},
  addAutomation:(input)=>{const row={...input,id:uid(),organization_id:activeOrganizationId,created_at:new Date().toISOString()};setAutomations(x=>[...x,row]);log('création','automatisation',row.name)},toggleAutomation:(id)=>setAutomations(rows=>rows.map(x=>{if(x.id!==id)return x;log('modification','automatisation',`${x.name} : ${x.active?'désactivée':'activée'}`);return {...x,active:!x.active}}))
 }),[organizations,activeOrganization,activeOrganizationId,warehouses,suppliers,purchaseOrders,purchaseReceipts,automations,audit,displayName,updateCompany,inventory,adjustInventory,addInventoryItem]);
 return <Ctx.Provider value={value}>{children}</Ctx.Provider>
}
export function useV4Platform(){const value=useContext(Ctx);if(!value)throw new Error('useV4Platform must be used inside V4PlatformProvider');return value}
